### ISSUE TITLE
Security patch level outdated

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/volla-os-beta-test#10]
As the Volla Phone stands for privacy and security the security patch level of the VollaOS should be updated regularly.
As of now the patch level is february 2020.

![Screenshot_20200901-203610](https://user-images.githubusercontent.com/67801045/91893422-60b4d480-ec94-11ea-8959-004fdfecf6fc.png)

**Comment by gbdomubpkm** [comment]
Some news on this very important point of security ?

**Comment by saidinesh5** [comment]
AOSP 10 based build is in the works.. will take a little longer than it should have but it will be available.

**Comment by ymer66** [comment]
My Volla Phone shows October 19, 2020....sorry folks but this is not acceptable - AOSP patches must be applied much faster...current patch level is https://source.android.com/security/bulletin/2021-03-01

**Comment by wurzer** [comment]
We are working on a major update, that will be published in the next couple of weeks.

**Comment by ymer66** [comment]
Thanks for the feedback, good to read! Looking forward to get some downloads from ota.volla.tech soon.
I hope you get patches out in the future as fast as AndroidOne certified phones do get - I like the Volla quite a bit but privacy good security go hand in hand.

**Comment by wurzer** [comment]
Thanks our plan. And we are hiring to do so. We thank all contributors and backers, to make a start possible.

**Comment by gbdomubpkm** [comment]
@wurzer Hello.
I think that if you want to have a small chance that your job ad will attract attention here, it would be better to leave the issue open, especially because 
** this issue update has not been officially done yet **.
Sincerely

**Comment by gbdomubpkm** [comment]
I seen today an update VollaOS 9.0 in the update manager  dated May 28,2021. 1.1 Go.  Good to download and install ? What does it fix?

**Comment by saidinesh5** [comment]
It will make it possible for you to download the upcoming Volla OS 10.0

**Comment by gbdomubpkm** [comment]
@saidinesh5 ok. No problem to download and install ? Just follow what it says on the screen ?

**Comment by saidinesh5** [comment]
ONLY if you didn't flash TWRP recovery. (Especially when switching from ubports to Volla OS etc..)
Otherwise simply ignore this update

**Comment by gbdomubpkm** [comment]
I installed it. Everything went well. Update Android 9 dated May 9,2021.

**Comment by wurzer** [comment]
Fine. This is an intermediate update. The major update will follow soon.

**Comment by gbdomubpkm** [comment]
1,1 Gb anyway ! Not so small !
What should be the size of the major update ?

**Comment by wurzer** [comment]
it will be similar. The recent build has 930 MB

**Comment by gbdomubpkm** [comment]
Is the Volla OS 10 update called on that of OTA-18 UT or is Volla  OS 10 imminent ?

**Comment by wurzer** [comment]
Volla OS is another operating system than Ubuntu Touch. OTA-18 is the release name of Ubuntu Touch and not related to Volla OS.

**Comment by gbdomubpkm** [comment]
Of course!!! 😄 😄 You didn't understand me ! I was asking you if you were waiting for UBports OTA-18 to be released in some weeks i think, to, at the same time, promote and deliver to users Volla OS 10 that 'you' are developing... Or you want to deliver Volla OS 10 quickly now or in some days ?

**Comment by wurzer** [comment]
We will publish the Volla OS 10 update independently from OTA-18. The reason for the delay was a migration and re-organization of our repositories on another continuous integration and deployment infrastructure to prepare more frequent security updates and the publication of the source code afterwards. We are sorry for that delay but we think, that is was worth for the objective behind that effort.

**Comment by gbdomubpkm** [comment]
Thank you for your answer. You are right and it is quite understandable and desirable to consolidate the structure in order to allow Volla OS to be perennial. But what can question the Volla OS users is to have a superposition of announcements of report on report on report....
So, if I translate your words, it will be AFTER the release of OTA-18. So it is likely that there will be another communication in this sense on Indiegogo. If so, i think it should be done as soon as possible i think...

**Comment by wurzer** [comment]
Both processes are independent. Ubuntu Touch touch is maintained by the UBports foundation. They decide, when an update is released. The team of Hallo Welt Systeme contributes to the Ubuntu Touch development, sometime device specific, sometimes for general features and bug fixing.

I'm happy to tell you, that the Volla OS has passed the final test for the release we want to publish. It will come soon. I'm confident, that we will have a more detailed release plan with schedules for our users and community in the future.

**Comment by gbdomubpkm** [comment]
Congratulations. Do not hesitate to let us know a precise date...

**Comment by gbdomubpkm** [comment]
Hello.
The Volla OS 10.0 update went well, thank you.

But something that surprises me. Once the update was done, the update manager proposed again the installation of Volla OS 10.0, which I did again thinking that it was a new update....

Going again in the update manager, I deleted this time the 1 GB file. The manager suggests to download the update again...

Is this all on purpose or is it a bug?

**Comment by wurzer** [comment]
Hello, you mean, that the installation is still offered as an option in the update app? I can conform this and agree, that this could confuse some users. I think we should fix this. However I don't get a notification on my productive device or test devices.

**Comment by gbdomubpkm** [comment]
Yes, here a screenchot got after whai i said :
![image20210727_181133180](https://user-images.githubusercontent.com/50362604/127189909-5fea447f-c21f-4419-9cd6-754380cf398d.jpg)

**Comment by gbdomubpkm** [comment]
An other little thing : Simple Thank You (heart, Tibor Kaputa) is no longer shown on the launcher for me. And you ?

**Comment by wurzer** [comment]
Yes, It's a hidden app, because it is not for everyday use, but you can open it in the settings.

**Comment by wurzer** [comment]
Regarding the update. Yes, the update is still shown after installation. We can have a look at it. However you can just ignore it. You can derive from the information about the currently installed system, that your system is up to date.

**Comment by gbdomubpkm** [comment]
Small new thing i noticed with this update : the screen woken  (lit) BUT locked,  remains lit a too short time in my opinion: 10 seconds approx. I do not think that this parameter is adjustable (not found). In my opinion, between 20 and 30 seconds would be more appropriate if you can do something about that.
With UT, this time is much longer than 10 seconds.

**Comment by wurzer** [comment]
I think you mean the display setting how long it should take to darken the display?

**Comment by gbdomubpkm** [comment]
I mean when the screen is like this first (power button pressed so as to light the screen) 
![image20210728_130938665](https://user-images.githubusercontent.com/50362604/127313830-15a6dd02-ea20-4a35-8270-0b2a5bc02913.jpg)
...and 10 seconds later the screen is black.

**Comment by wurzer** [comment]
Yes, I mean this setting. Sorry for the German screenshot. I took my personal device on my desk
![Screenshot_20210728-161809](https://user-images.githubusercontent.com/7789612/127338878-541e6c62-158d-4828-a1fa-56ae5fe7bc5e.png)
![Screenshot_20210728-161836](https://user-images.githubusercontent.com/7789612/127338896-9750aba7-bc75-49cb-ad7f-a615031e03ef.png)

**Comment by gbdomubpkm** [comment]
I had of course seen and tried this before but NO, changing this setting does not work WHEN the PHONE (screen) is LOCKED (padlock): the delay is always 10 seconds. You should see that.

**Comment by wurzer** [comment]
How many seconds would you prefer?

**Comment by gbdomubpkm** [comment]
I think maybe 30 seconds would be fine.

**Comment by gbdomubpkm** [comment]
Hello.
What is it ? I saw a new VollaOS 10.00 dated august 16. should we update? If so, what does it fix?

**Comment by wurzer** [comment]
Indeed, it fixes critical issues:

1. Font issues of non latin keyboards and default font in the web browser
2. Fix for crashes or errors while opening, exporting or moving files
3. Fix for custom sounds, that have been lost after reboot.

**Comment by gbdomubpkm** [comment]
Done. Thanks for 2. confirmed fixed  with this update !!

**Comment by gbdomubpkm** [comment]
Hello.
Is the august 23 release the same that august 15 release or there are new fixes in this (new ?) release ? I don't see infos about the Aug 23 release in Wiki. Thanks

**Comment by wurzer** [comment]
The update from 23 August includes an important fix to enable further updates. Further thinks are not changed. We recommand to install that update. Afterwards you will see, that date of the system keeps the same.

**Comment by gbdomubpkm** [comment]
ok, so I do. A wiki update would be probably usefull.
Small aside: will the Volla X be available through the Indiegogo vector in some times ?

**Comment by gbdomubpkm** [comment]
I get this AFTER updating
![image20210903_182310416](https://user-images.githubusercontent.com/50362604/132038369-7d6c633d-8941-424d-a3d4-1bd42c8d3bcb.jpg)
If i understood you well, it is normal ?

**Comment by wurzer** [comment]
That's correct. The date is not updated because of a minor but essential fix.

**Comment by gbdomubpkm** [comment]
Hello.
First of all, thanks for the very regular updates.
I updated today (27 september update), and i don't find where is  the setting  improvement ''Startup wizard with including restore option'.  Can you provide screenshots (if there are) ? Thanks.

**Comment by wurzer** [comment]
You should find the backup feature in the system settings and system and backup. If you tap on this option, you will get a screen with words, that you need to write down to recover the apps and data later if necessary. The setup wizard is only shown, if you do a factory reset. We are investigating, why the setu for the backuo is not shown on all devices after update

![Screenshot_20211001-101844](https://user-images.githubusercontent.com/7789612/135588730-7b150043-6339-4ce9-9c90-665dee792f68.png)
![Screenshot_20211001-101857](https://user-images.githubusercontent.com/7789612/135588736-a504dc69-3394-4543-acba-8ec575637497.png)

**Comment by gbdomubpkm** [comment]
Ok. I thought I was in the right place. And you confirm that it is 'normal' not to see the backup settings after the update. Thank you.

**Comment by wurzer** [comment]
It's not normal but a known issue on some devices. It would appear after a factory reset, but that's not a solution. We are already investigating in this issue

**Comment by wurzer** [comment]
Hello. Yes, your system is up to date! Enjoy your day!

**Comment by gbdomubpkm** [comment]
Hello.
I don't have this problem but I wonder: does the installation of a new system update or the reinstallation of the last built installed by the update manager make it possible to start again on a clean system free of any nuisance (malware, virus...) in case of corrupted system?

**Comment by wurzer** [comment]
The security is almost done. We have update 90% of the repositories.
During an update the system will is exchanges, but the user image (partition) will be kept. So if you have installed malware apps, they will still exist. In this case you should remove not trustworthy apps.

I you have rooted your device I recommend a factory reset. If you have a reason to think, that your device was hacked I recommend a factory reset anyway.

**Comment by gbdomubpkm** [comment]
I don't have any problems or dubious apps installed. The questions were just for a good understanding in case. Thank you for the clarification.

**Comment by gbdomubpkm** [comment]
> The security is almost done. We have update 90% of the repositories.

Is there a date planned when the update will be pushed?

**Comment by wurzer** [comment]
Hello, our goal ist to publish the update this month. Enjoy your day.

**Comment by ymer66** [comment]
Another patch down the line: https://research.checkpoint.com/2021/looking-for-vulnerabilities-in-mediatek-audio-dsp/

**Comment by gbdomubpkm** [comment]
> https://research.checkpoint.com/2021/looking-for-vulnerabilities-in-mediatek-audio-dsp/

For the update, this will surely be taken into account if it has to be ?

**Comment by gbdomubpkm** [comment]
@wurzer update a little deferred ?

**Comment by wurzer** [comment]
All updates to the operating system repositories have been made, so we will be testing a release candidate this weekend.

**Comment by gbdomubpkm** [comment]
Is the update rolling out ?

**Comment by wurzer** [comment]
Yes, the release candidate was approved yesterday. We included another fix for VPN

**Comment by gbdomubpkm** [comment]
Done thanks.
The issue of backup option not shown is not solved it seems ?

**Comment by wurzer** [comment]
This is indeed an open issue, that a developer is working on now. We just discussed it in our developer conference at Friday

**Comment by gbdomubpkm** [comment]
Ok. Thanks for the info and confirmation. This is probably the last very important point for you to fix..

**Comment by gbdomubpkm** [comment]
Hello.
What about backup issue ?

**Comment by wurzer** [comment]
We will offer a fix for Volla OS 10 in the next update. However you can activate the backup feature yourself:

    # adb shell bmgr enable true
    # adb shell bmgr transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport

All new devices and devices after a factory reset should not have this issue.

**Comment by gbdomubpkm** [comment]
Thank you for your answer.
But, what do you mean by 'activate the backup feature' by command lines : does it mean that the backup feature will be after the procedure visible in system / backup on the phone ?
Or did you plan already a date for the next update ?

**Comment by wurzer** [comment]
The backup feature is already installed and available on VollaOS 10. It's just not visible in some cases, if people updated the system from an older version, where the backup feature was not implemented.

**Comment by gbdomubpkm** [comment]
Can you please clarify the entire procedure?
Is it to enable OEM unlock + USB debugging on the Volla then, plug it into my latlop ubuntu 20.04 and adb devices and run your two commands ONLY? I don't want to make any mistakes. Thanks

**Comment by wurzer** [comment]
You don't need an OEM unlock, just an ADB connection:

1. Go to the system settings
2. Tap on "About the phone"
3. Tap on the build number 5 times
4. Go back to the system settings and select "System"
5. Tap on more options
6. Tap on developer settings
7. Enable ADB debugging.
8. Connect your Volla Phone with your PC or Mac
9. Enter the commands above in the command line or terminal app

Please note, that you need to install Android Tools on your PC or Mac to execute the commands. However we plan the next update with a fix this month.

**Comment by gbdomubpkm** [comment]
Done. Thanks !

**Comment by gbdomubpkm** [comment]
Hello.
Thanks for the new update Volla OS.
I updated this night : what's new inside ?

**Comment by wurzer** [comment]
Thanks for your comment. I have updated the relase notes now:
https://github.com/HelloVolla/volla-os-beta-test/wiki/Volla-OS-Release-Notes

**Comment by gbdomubpkm** [comment]
Hello.
It seems to me a bit ambiguous to inform the Volla OS 11.1 update for April 20 regarding the Volla (ok for Volla X i think) in the wiki. Isn't it ?

**Comment by wurzer** [comment]
The Volla OS 11.1 release will be from April 20th für both devices. However we need to publish an intermediate release of Volla OS 10 and 10.1 first to enable a major update.

**Comment by gbdomubpkm** [comment]
Hello.
I done today the intermediate release Volla OS 10.0. No problem.
But before doing the future 11.1 update, what does the two following issues concretely mean? Are they blocking? Does the Volla hotspot with Volla OS 11.1 work (securely) curently because I absolutely need it?
  - Missing IMS registration for parallel phone calls and data transfer.
  - Missing IP-Address for other devices using the hotspot feature.

Thanks in advance for enlightening me.

**Comment by wurzer** [comment]
Please have a look at the release notes: https://github.com/HelloVolla/volla-os-beta-test/wiki/Volla-OS-Release-Notes

Please note, that this is a closed ticket.

**Comment by gbdomubpkm** [comment]
> Please have a look at the release notes: 
https://github.com/HelloVolla/volla-os-beta-test/wiki/Volla-OS-Release-Notes

I had consulted this link but I do not understand what the 2 points that I mentioned above to you concretely mean.

> Please note, that this is a closed ticket.

You are right. But I found it more practical to use this link permanently than to open a new ticket each time I have remarks or questions about a new update. But I can do as you wish of course

**Comment by wurzer** [comment]
Good morning,

For general questions about releases, You are invited to contact our customer service at https://volla.online/de/support/

Regarding the release notes:

For Volla OS 11.1 on the Volla Phone, IMS registration and tethering is not working. We prepare another update with a fix, that is expected for early next week. That means, that you can't make phone calls and browse web for the same time and you cant use the Volla Phone for a hotspot.

For both devices we realized limited file access of apps as an impact of more strict permissions in the recent Android 11 release. That means for instance, that you need to store maps in the download directory if you use an external microSD card storage. 

Enjoy the day!

**Comment by gbdomubpkm** [comment]
Hello.
Thank you for your answer which enlightened me.
So I think, in addition to your technical explanations, it would be helpful for users if you succinctly specify in some simple words in the wiki what is not concretely working.
Have a good day.
