### ISSUE TITLE
Android Auto Error 22

### ISSUE THREAD

**Issue by CAMongrel** [HelloVolla/volla-os-beta-test#101]
Device: Volla Phone 22
Version: 12.1

With MicroG enabled Android Auto installs fine, but it's a non system app resulting in error 22 when trying to connect to a car (Volkswagen in my case).

See this XDA-thread:
https://forum.xda-developers.com/t/gsi-fix-communication-error-22-on-android-auto.4456645/

I understand that a pre-installed Android Auto app as a system app is problematic, but for me a proper car integration is an  important feature. Is there any way to support this officially? (moving Android Auto to "priv-apps")
I'm willing to beta test changes if necessary.

Thanks!

**Comment by wurzer** [comment]
Looks like, that Android Auto app needs to be pre-installed. Since this app is a proprietary app, we are not allowed to install it on Volla OS. 

You may have a look at alternatives.
https://www.makeuseof.com/best-android-auto-alternatives/

**Comment by CAMongrel** [comment]
Sorry to bump this again:
Not sure if this is properly answered elsewhere, but does rooting the device void the warranty? 
Either way, is there a guide somewhere? Since the bootloader is already unlocked, it should be much simpler.

**Comment by wurzer** [comment]
I strongly recomment, not to root the device to avoid a significant security risk. If you brick your device, it will be out of warrenty, but you can recover your device a paid service.  If you are living in the EU, you could ship your device to phone-service.de/volla. For customers in Switzerland we have a new partner MobileZone https://www.mobilezone.ch/de/handy-shop-reparatur/overview

To root the device you could use twrp for instance. If you just want to replace the OS, unlocking the bootloader should be sufficient. With Ubuntu Touch you can force root permissions with sudo command.
