### ISSUE TITLE
Screen freezing and random input without touching the screen

### ISSUE THREAD

**Issue by nutcracker22** [HelloVolla/volla-os-beta-test#103]
**Phone**

- Device: Volla phone
- OS: VollaOS 11.1 (happened on older OS versions, as well)

**Steps to reproduce**

No action causes the issue.

**Expected behavior**

Screen should react to touches and apps should only open when clicked.

**Actual behavior**

As described in [https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/126](https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/126).

Sometimes the screen simply "freezes" and does not respond to touches, anymore. In other cases, it is as if a "magic invisible hand" touches the screen, leading to 
- random keyboard input,
- apps being opened,
- apps being switched,
- in-app actions being executed (in most annoying cases: emails being deleted).

It can be stopped by pressing the power button to lock the screen. Sometimes unlocking the screen afterwards does not solve the problem, so it needs to be locked and unlocked several times in order to make the phone work properly, again.

Since it happens both on Ubuntu Touch, as reported in the above linked issue, and on VollaOS, I am wondering, whether it is OS-related or not.

**Comment by wurzer** [comment]
Dear user. This is mnost likely a hardwareissue. Pleaee open a ticket at volla.online/en/support
