### ISSUE TITLE
MicroG constantly crashing

### ISSUE THREAD

**Issue by TFleury** [HelloVolla/volla-os-beta-test#106]
Device : Volla Phone 22 (mt6768)
Version VollaOS : 12-20230831-BETA-mimameid
![Screenshot_20230912-100447_Paramètres_1](https://github.com/HelloVolla/volla-os-beta-test/assets/7600804/536625be-b625-47e0-a797-37992d1199eb)

**Comment by TFleury** [comment]
Can someone confirm this issue or is it only my device ?
@wurzer any update on this bug ? Is there a new release under way ?
It's realy uncomfortable to have this popup regularly.

**Comment by wurzer** [comment]
Looks like it is only on your device. However I recommend to switch to the recent stable release. You are on a beta release.

**Comment by TFleury** [comment]
Sorry, I did not see there was newer stable releases.
It seems to be fixed.

**Comment by wurzer** [comment]
You need to switch back to the stable channel in the Volla channel switcher app .
