### ISSUE TITLE
FM radio stops sound output when switching to another app 

### ISSUE THREAD

**Issue by Achim242** [HelloVolla/volla-os-beta-test#107]
Vollaphone X23
Volla OS 12.1 
12-20230907-STABLE-vidofnir

Interesting discovery made :

Plugged in headphones, zapped around a bit on FM radio, set a few favorites. Music possible via headphones, as well as via speakers. 
If you switch to another app, the sound goes away, and suddenly system-wide. No sound anymore, neither for local music or video files, nor for corresponding files in messengers.
Neither via headphones, nor via the speaker. 

Clear cache / force quit does nothing, only a reboot helps.
Have tried it with two different headphones, once inEar and once OverEar.

Greetings.

**Comment by tux4us** [comment]
VollaPhone 22
VollaOS 12.1
12-20230909-STABLE-mimameid

Can't reproduce this issue in VollaPhone 22. Works fine here.

**Comment by Jplrp** [comment]
Vollaphone X23
Volla OS 12.1
12-20230911-STABLE-vidofnir

Same for me when i open Radio FM, it says "Indisponible actuellement" when i plug headphones, then no media sound working, other sounds working fine. Only reboot helps.

**Comment by wurzer** [comment]
Kann ich bestätigen. Nehme ich auf

**Comment by Jplrp** [comment]
If it helps, I've also found that when I listen to the radio via Fennec with headphones, if my alarm goes off and I turn it off, the sound is produced both on the speaker and on the headphones. Also, the media sound no longer works as soon as I open the radio application, even if I'm listening to something on Fennec beforehand.

**Comment by Achim242** [comment]
BTW:
The problem was fixed with the update from 02.11.2023. Thank you, the ticket can be closed.

**Comment by Achim242** [comment]
The problem was fixed with the update from 02.11.2023. Thank you, the ticket can be closed.
