### ISSUE TITLE
12. September 2023 update

### ISSUE THREAD

**Issue by toby63** [HelloVolla/volla-os-beta-test#108]
I would like to know why this update is only 1 GB in size while the former update is 1,5 GB?

And is it necessary for everyone to install?
"package cache" doesn't really tell me much.

**Comment by wurzer** [comment]
It's a different build. Package cache means, that the the cache for packages (mainly apps) are removed for the update to avaoid conflicts of modified datamodels.

**Comment by gbdomubpkm** [comment]
A great app i use to clean cache : https://f-droid.org/en/packages/com.github.bmx666.appcachecleaner
