### ISSUE TITLE
Hotspot does not use the custom DNS

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#109]
I install a custom DNS on the Volla (CLOUDFLARE). I activate connection sharing (HOTSPOT). I control the DNS on my Ubuntu laptop ( https://ipleak.net ) : the DNS on my laptop is that of my internet provider and not cloudflare. Is this normal ? Android 12 currently.

What about sharing DNS with hotspot on android ? I couldn't find a clear answer on the internet.

With UT on a Volla, I can share (hotspot) a custom DNS (cloudflare).

**Comment by wurzer** [comment]
You need to configure a custom DNS server in the system settings of the Volla Phone, if you PC is configured to the DNS of the internet access point. It shold also be possible to force using another DNS server on your PC, so only the pure IP call are used for the hotspot.
