### ISSUE TITLE
Per app battery usage not available in system settings

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/volla-os-beta-test#11]
In the system settings the battery usage per app isn't available/not shown.

![Screenshot_20200903-054928.png](https://user-images.githubusercontent.com/67801045/92069514-d5c5fe00-eda9-11ea-9847-d0809ae52dc7.png)

**Comment by wurzer** [comment]
Use the three-dot-menu in the upper right corner to see per app battery usage.
