### ISSUE TITLE
USB-C to HDMI Cable | Phone to TV HDMI cord | Mobile Phone to HDMI Connection

### ISSUE THREAD

**Issue by kungfooman** [HelloVolla/volla-os-beta-test#110]
Hi, I consider buying this phone for Linux support (since I'm developing on Linux for many years), now I also wonder if I can use it with phone mirroring:

1) It allows e.g. to run presentations on your phone only.
2) Using it as mobile desktop station.

E.g. example here: https://youtu.be/2xPp4KpkSwU?t=106 (timestamped)

Did anyone try this?

**Comment by wurzer** [comment]
Thanks for your interst in our Volla Phones. Like other Android bases system you can 

- Run apps for presentation
- Mirror or stream the screen with Miracast or Chromecast
- Connect a display, that support DispayPort.
