### ISSUE TITLE
22 vs x23 - Screen breakability and battery radiation

### ISSUE THREAD

**Issue by kungfooman** [HelloVolla/volla-os-beta-test#111]
https://volla.online/de/volla-phone-22/
https://volla.online/de/volla-phone-x23/

The 22 link claims:

![image](https://github.com/HelloVolla/volla-os-beta-test/assets/5236548/a376f01b-9bf5-4f56-9e86-f54cd62370e7)

Translated: Long-life and durable 4500 mAh lithium polymer battery for self-replacement. Extremely low radiation values of 0.29 W/kg at the head.

I don't understand this in the first place - a battery has radiation levels?

My wife and I both want to buy a new phone because an iPhone glass just broke and it's a bit older already, but we still have two questions:

1) A battery has radiation levels? If so, what about the X23, are they also lower than other smartphones and which EMF meter do you use to measure this?

2) About breakability: my wife rather wants a white/pink phone ("black is ugly"), but the x23 looks more stable and it shouldn't break. Is the 22 just as breakable as any other smartphone? Does it break more often than x23? I guess the ideal case would be more colors for x23...

Thank you for all your work!

Best regards,
Hermann Rolfes

**Comment by wurzer** [comment]
- The first statement refers to SAR values of the device, not the battery
- The Volla Phone 22 is our sleek, lightweight flagship model. To protect the disolay, you can order a display protector. 
- The Volla Phone X23 is as a rugged variant the successor model of the Volla Phone X with Gorilla Glass 5 and a resistance to military standard MIL-STD-810H and IP68 dust and waterproof
- You can buy for both devices felt sleeves for additional protection. For Volla Phone 22 we offer a hardcover book case.
