### ISSUE TITLE
Alarm volume decreases from maximum to silent sometime

### ISSUE THREAD

**Issue by p-heeb** [HelloVolla/volla-os-beta-test#113]
Sometimes the alarm volume which I had set to maximum is in the morning on silent and the alarm does not ring anymore. This volume setting change is unexpected and issues some delay in the morning :)

**Comment by wurzer** [comment]
I use the alarm daily and can't reproduce it. Please post the device and os version with uts publication date. You may also check the sound systems settings for alarm and the selected alarm tone.

**Comment by p-heeb** [comment]
I've been using Volla Phone 22 with the VollaOS 12.1 from September 11th, 2023. The sound system settings for the alarm are on the maximum of the volume bar and the alarm tone works. It's not an everyday problem but sometimes it occurs. Not sure if it's only a problem if the phone is upside down or not.

**Comment by wurzer** [comment]
Did you change the sound or do you use the devault one?
Did you check increasing volume in the clock settings?

**Comment by p-heeb** [comment]
I have the Oxygen Sound which is I guess the default one and the increasing ring volume is disabled.

**Comment by wurzer** [comment]
volla_alarm is the default alarm tone. You may try another sound.

**Comment by p-heeb** [comment]
The same with the alarm tone "Barium".

**Comment by wurzer** [comment]
Unfortunately I can't reproduce this issue on a Volla Phone 22 with Volla OS 12.1 from Setember 11th. I'm using the volla_alarm sound. You can try to reset app setting in the system settings. Are you able to reproduce this issue with another alarm app?

**Comment by p-heeb** [comment]
I've only used this alarm app, but I will try it with another one.

**Comment by wurzer** [comment]
See #146
