### ISSUE TITLE
Battery drain due to Security mode

### ISSUE THREAD

**Issue by RinkebyDanceKids** [HelloVolla/volla-os-beta-test#115]
Hey again, I hope this form of report fits the forum better.

So I discovered that as soon as i put on Security mode. I get battery drain from Android-System. So I assume the operation of removing/hiding the apps from the system causes the system to go confused with the connections to the apps. (Just a guess). But the battery drain happens in both Volla and Trebuchet. And my battery is up in two days again, from just a few hours.

Problem is, now my apps cant be shut down in that way either. A problem that must be fixed.

**Comment by wurzer** [comment]
I use the securoty mode daily. An increasing battery drain can't be caused by the securoty mode. It's the oppositve. If you activate the securoty mode, the battery drain is less, if apps are blocked. 

I recommend to check your apps and processes. that are running in the brackground, in particualar additional apps. Please post for any issues the device mpodel and the Volla OS version date. 

There was a battery drain issue with the beta version of Volla Os because of the extending loggingn in the background.

**Comment by RinkebyDanceKids** [comment]
Sorry to say, for me is the opposite. And it got nothing to do with the apps draining more or less battery. I is simply something that cause "Android-System" to constantly drain battery with security on.

Either this is because of a certain app that starts Android-System to bug out. Or something deeper.

But it is proven for me that its caused by Security Mode on.

**Comment by wurzer** [comment]
Please make sure, that you don't use a Volla OS beta version but the recent public release from September 11th.

**Comment by RinkebyDanceKids** [comment]
Yes,

This is the version I use


12-20230911-STABLE-vidofnir

**Comment by RinkebyDanceKids** [comment]
> Yes, This is the version I use 12-20230911-STABLE-vidofnir

And to help you guys, and possibly me. I am going to add one app at the time to Security Mode. Single out the one or ones that causes these drain.

**Comment by wurzer** [comment]
By deaktivating app by app you may derive which app causes the mort battery. But this should also be visible in the battery report. What you also can do is to activate developer mode and investigate in the running services.

**Comment by RinkebyDanceKids** [comment]
Hi,

So here it is.

I made a screen shot of what my problem is. And perhaps others who have not discovered it yet. 

What I have done here is to have NO apps in the Security modes lock list. To simply turn Security mode On, to see the battery drain double. I let it idle like that for a while, to turn it back off.

However. Good to know. Turning Security mode Off doesn't stop the drain it started. But you have to turn it off, charge it while booting for a few seconds. To see the effect by idle without charging for a good while.

Spell is now broken. And I tested it a few times.

I use QI charger, and I didn't use Trebuchet during this test.

And I hope you see the zick zack pattern i marked.

Don't see this as critique as you have a lot to do. But as help to see if you can recreate this. Every user should. 

"Dr. Jörg Wurzer" ***@***.***> skrev: (28 oktober 2023 17:36:25 CEST)

**Comment by RinkebyDanceKids** [comment]
I add the picture for GitHub too.
![drain-01](https://github.com/HelloVolla/volla-os-beta-test/assets/147806721/9dc67fb3-8ff3-4c28-a1de-6ca4186b3a46)

**Comment by wurzer** [comment]
So it's most likely not caused by the securoty mode. Please check the running processes in the developer settings. You are welcome to change the screenshots here.

**Comment by RinkebyDanceKids** [comment]
I understand that security mode is not the very thing that drain the system. But certainly seem to be a trigger to something in the system.

However, fixing it seem to be more about rebooting. Charging it turned off. So I keep searching. Heads up though.

**Comment by wurzer** [comment]
You may also check the new  update with new firmware and patched Kernel

**Comment by RinkebyDanceKids** [comment]
The result of the new update have the same effect. Security mode on triggers something to drain battery with 100℅ consistency. And Android- System climbs the list of battery draining apps.

Two screenshots. One moment before putting on security mode. The other one 2 or 3 hours later. And I already lost 20 hours of battery.

**Comment by RinkebyDanceKids** [comment]
Well, now i cant upload images for some reason

**Comment by RinkebyDanceKids** [comment]
![signal-2023-10-31-191839](https://github.com/HelloVolla/volla-os-beta-test/assets/147806721/152b137c-db46-4e1e-afac-4f089b9bffb5)
![signal-2023-10-31-191844](https://github.com/HelloVolla/volla-os-beta-test/assets/147806721/4beb0dad-6a59-4b9c-bdd2-ed19c46461a2)

**Comment by wurzer** [comment]
I exclude a causal connection between the energy consumption and the safety modes. 

Please check the active processes in the developer settings to get a differentiated picture of the CPU and system load. 

How did you configure the safety mode? Are you using a white list or black list? Are you using templates for the domains or have you done the defniition yourself?

Could you share a logcat?

**Comment by RinkebyDanceKids** [comment]
I understand how you are thinking, that the problem can be solved elseware than security mode. However not really my table is it?

But the logcat sounds like the approach then. However, does that give up sensitive data from me? And how do I fetch it?

**Comment by wurzer** [comment]
Unfortunately, I can't reproduce this issue. Please let me know:

* A report of active processes 
* Your confirugation of the security mode
* Your logcat, if you are familiar with Android Platform Tools

You send the report via volla.online/en/support

**Comment by gbdomubpkm** [comment]
Just an idea : could this not be due to a weakened battery ?

**Comment by RinkebyDanceKids** [comment]
No its not. Its fairly new. And I got great battery life without security mode. Witch is sad. The problem is that the guys cant recreate my problem. And I am going to hand over info when I got the time.

**Comment by gbdomubpkm** [comment]
Ok. Another idea : Maybe also testing  if being only on wifi or mobile data changes anything.

**Comment by franco-bez** [comment]
there's a thread in the german language forum where users complain about reduced runtime since the last update
[https://forum.volla.online/viewtopic.php?p=4427](https://forum.volla.online/viewtopic.php?p=4427)

**Comment by RinkebyDanceKids** [comment]
I saw that the latest volla update had battery drain as a fix. Is it this one?

**Comment by franco-bez** [comment]
> I saw that the latest volla update had battery drain as a fix. Is it this one?

I assume it's up to you to test whether the update fixes your problem.

**Comment by RinkebyDanceKids** [comment]
Yeah. I think I saw two complaints about battery drain. And to the look of if it. My remains.

**Comment by franco-bez** [comment]
so far the two people in the german language forum that complained about battery drain gave a positive feedback.
"looks promising" is the current statement.
But both of them did not see any connection to the secure mode.

**Comment by RinkebyDanceKids** [comment]
Thanks for informing me. Yeah my problem seems to be down to my phone and falls between many shairs how to fix it.

**Comment by RinkebyDanceKids** [comment]
So, long time no see and a few monthlies of updates. I can say that the problem is cured. I want to use that word as I dont know if it will come back. But with the new switch in trebuchet  for security mode on/off. and rebooting when I see a battery drain seems to stabilize the drainage. So, all the good things at once! Really smooth on and off, and no extra problems! 

Thanks.

**Comment by RinkebyDanceKids** [comment]
I want to add. If the problem reoccur for someone else. The solution is to charge via cable. Make sure the battery is fully charged a few times via cable, not wireless as I did.

Something hides in wireless charging rather in security mode.

**Comment by RinkebyDanceKids** [comment]
Done
