### ISSUE TITLE
Orange State after installing 12-20231028-STABLE-vidofnir

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/volla-os-beta-test#118]
today I installed the latest VollaOS Update on my X23
Since then I get a Orange State warning on startup and also dual boot for ubuntu touch is completely broken.
see also [https://forum.volla.online/viewtopic.php?f=4&p=4354#p4354](https://forum.volla.online/viewtopic.php?f=4&p=4354#p4354)

The bootloader has never been unlocked.

**Comment by wurzer** [comment]
The orange state is not related to the update. It's just warning, that the boot loader is unlocked. If you switched the operating system from Ubuntu Touch to Volla OS as a primary system, you can lock the bootloader in the fastboot mode of the device with the command `fastboot flashing lock`.

**Comment by franco-bez** [comment]
primary system has always been volla os.
Ubuntu touch is only on SD card for dual boot.

I will try the fastboot command.

30.10.2023 18:31:56 Dr. Jörg Wurzer ***@***.***>:

**Comment by wurzer** [comment]
Please not, that the user date will be deleted, if you lock or unlock the bootloader.

**Comment by franco-bez** [comment]
now deleting the user data is of course not what I want to do.

And still I insist that the Orange State was not there before the VollaOS Update and appeared right on the first reboot after the update.
Bootloader was never unlocked on the device, primary OS was always VollaOS.

30.10.2023 18:38:53 Dr. Jörg Wurzer ***@***.***>:

**Comment by franco-bez** [comment]
![Screenshot_20231030-192925_Trebuchet](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/611c6eb9-293b-4d07-adf3-61d8f399b1ef)
even now the bootloader unlock is disabled.

**Comment by wurzer** [comment]
We'll investigate.Can you ckeck `fastboot getvar unlocked` in the fastboot mode?

**Comment by franco-bez** [comment]
no problem

here's the output of the command
***@***.***:~$ fastboot getvar unlocked/
/unlocked: no/
/Finished. Total time: 0.018s/

Am 30.10.23 um 19:56 schrieb Dr. Jörg Wurzer:

**Comment by wurzer** [comment]
I'm glad. That's good news. Then the warning is a false positive warning. We'll invetigate

**Comment by franco-bez** [comment]
fixed with 12-20231102-STABLE-vidofnir

no longer shows Orange state warning - good job
