### ISSUE TITLE
Dual boot of UT broken after after installing 12-20231028-STABLE-vidofnir

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/volla-os-beta-test#119]
since I updated volla os to 12-20231028-STABLE-vidofnir on my X23 the Ubuntu touch does no longer boot.
I even tried a clean reinstall of Ubuntu Touch on a fresh SD card - same effect

![IMG_20231030_154932](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/9c975e54-7657-4a99-8133-ccae0146fd61)

after some 30seconds the small text (going to map ramdisk etc.) disappears but UT never boots.
I waited 10 minutes but nothing happens

**Comment by wurzer** [comment]
The log output is not expected.

**Comment by RinkebyDanceKids** [comment]
Same here. Not working after update. Same log.

**Comment by luka177** [comment]
Hi,
Thanks for issue report. Error you are seeing at installation is safe to ignore. Issue you are having is a result of firmware update shipped with latest update. You will need to update/reinstall Ubuntu touch when new build of Ubuntu touch is available, I hope it will happen tomorrow or on wensday. Sorry for inconvenience.
Best regards,
Luka

**Comment by RinkebyDanceKids** [comment]
Sounds good though. I was waiting for a new fresh install anyway.

**Comment by franco-bez** [comment]
today I could install the Ubuntu Touch update in VollaBootManager.

Now dual boot is working again - good job

The Orange State warning is still there.

**Comment by franco-bez** [comment]
> The log output is not expected.

The output is precisely the same now after the update.
Just now Ubuntu Touch boots up after this message.

**Comment by RinkebyDanceKids** [comment]
> today I could install the Ubuntu Touch update in VollaBootManager.
> 
> Now dual boot is working again - good job
> 
> The Orange State warning is still there.

I asked about that too. Its something you have to fix yourself with ADB. Configure the boot a bit. Or turn it in.

**Comment by franco-bez** [comment]
> I asked about that too. Its something you have to fix yourself with ADB. Configure the boot a bit. Or turn it in.


What do you mean, fixing the Ubuntu Touch on the SD Card?
Or do you mean getting rid of the Orange State warning?

**Comment by wurzer** [comment]
Fix of false positive warning of orange state is in progress. UT update is prepared. Please check updating UT inside the Volla Boot Manager. Tap on the system partition and select update.

**Comment by RinkebyDanceKids** [comment]
After putting external storage as first partition, and OS system partition after it, followed with User partition, I got UT working well with the new updates. Sim works, Libertine works, waydroid works, and so far pretty stable! So thank you guys. Hope to see a better version of waydroid soon!

**Comment by wurzer** [comment]
Good morning. We'll re-publish soon the update for Volla Phone X23. Ubuntu Touch for download is also updated to match the updated firmware. My tests have been successfull so far.

**Comment by franco-bez** [comment]
fixed with Update of VollaOS to 12-20231102-STABLE-vidofnir

no longer shows Orange state warning - good job

**Comment by franco-bez** [comment]
After booting into Ubuntu Touch I got offered the Update 197
I suspect that it is not a good idea installing the update in a DualBoot szenario, is it?
![screenshot20231102_115422929](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/642057c3-49e8-48df-849e-80d82728ebaf)

**Comment by wurzer** [comment]
You can't update Ubuntu Touch as a 2nd operating system in its system settings. You can oly update Ubuntu Touch as a 2nd operating system in the Volla Boot Manager. If you trigger an update inside the Ubuntu Touch system updat, it's won't start any more.

**Comment by RinkebyDanceKids** [comment]
welp, my phone was shiped with orange state. So its still there after updates :S
