### ISSUE TITLE
Notch hides the status bar in the middle

### ISSUE THREAD

**Issue by tux4us** [HelloVolla/volla-os-beta-test#12]
VollaOS 9.0 

The Notch hides the status bar in the middle and makes it impossible or very tricky to start the application underneath as an icon.
Is there a plan to design the status bar in relation to the notch?

**Comment by tux4us** [comment]
The camera app in particular requires the entire status bar to display the icons, depending on the activated options, and thus the icons located under the notch are practically impossible to operate.

**Comment by wurzer** [comment]
Only, it two much status icons are used
