### ISSUE TITLE
Time until battery is full charged is inconsistent

### ISSUE THREAD

**Issue by Danfro** [HelloVolla/volla-os-beta-test#122]
On the lock screen and in system settings one can see the time until the battery is fully charged. Those times do not match.
This is the case on VOS11 and VOS12.1.

Lockscreen VOS12.1

![grafik](https://github.com/HelloVolla/volla-os-beta-test/assets/37637312/45d1e685-2bd2-4331-83ce-aa031386f00b)

System settings VOS12.1

![grafik](https://github.com/HelloVolla/volla-os-beta-test/assets/37637312/8052a275-3145-4571-b70a-34f4f33c7004)

**Comment by wurzer** [comment]
Please note, that the device needs to support the protocoll of fast charging and vice versa. The estimation also depends on the current CPU load and will be adjusted, if the CPU load is going down.
