### ISSUE TITLE
typos in app list

### ISSUE THREAD

**Issue by Danfro** [HelloVolla/volla-os-beta-test#124]
In the [list of preinstalled apps](https://github.com/HelloVolla/volla-os-beta-test/wiki/Curated-Pre-Installed-System-Apps) there are several typos:

"Messanger" and "Mesaanger" should be both "Messenger"

K0 should be K9, the email app

Galery should be Gallery

Calender should be Calendar

Also I am not sure why on this page it says that the list "is a proposal". When proposing something, it is not done yet. But most of the apps are preinstalled. Guessing on what it may try to say, I suggest this wording:
"The following list shows pre-installed core apps of Volla OS and apps that are proposed to become preinstalled."

**Comment by wurzer** [comment]
I can't find any of the mentioned strings. To which version are you referring?

**Comment by Danfro** [comment]
I am refering to the strings on the github page. Please follow the link and see the words in the table. For instance:

![image](https://github.com/HelloVolla/volla-os-beta-test/assets/37637312/0841858c-479b-418b-8a63-6d4bd1967e25)

**Comment by wurzer** [comment]
No I got it. Thanks! I have updated the Wiki page
