### ISSUE TITLE
Volla X latest 12.1 stable Volume loudness

### ISSUE THREAD

**Issue by owalskie** [HelloVolla/volla-os-beta-test#125]
Hi. I noticed that on my Volla X with latest VollaOS 12.1 (stable)  it is now super difficult to regulate the volume.  The max-loudness is just fine but now it's far too quiet at the bottom.  Could this be adjusted with a fix?
Regards

**Comment by wurzer** [comment]
For which use case? Media playback or calls. With internal regular speaker, hands free speaker, wired or wireless headset?

**Comment by owalskie** [comment]
This problem occures while Media playback and calls with the internal regular speaker. I guess, it’s a global problem for all output sources. I’ll test it with Bluetooth Headset.RegardsGesendet mit der mobilen Mail AppAm 09.11.23 um 14:31 schrieb Dr. Jörg Wurzer
                
            
            
                
                    Von: "Dr. Jörg Wurzer" ***@***.***>Datum: 9. November 2023An: "HelloVolla/volla-os-beta-test" ***@***.***>Cc: "Author" ***@***.***>,"owalskie" ***@***.***>Betreff: Re: [HelloVolla/volla-os-beta-test] Volla X latest 12.1 stable Volume loudness (Issue #125)
                
                
For which use case? Media playback or calls. With internal regular speaker, hands free speaker, wired or wireless headset?

**Comment by wurzer** [comment]
I can't conform any issue to control the volume for a Youtube Video for instance.

**Comment by wurzer** [comment]
Might be related to #146
