### ISSUE TITLE
contacts in springboard should be labelled contact favourites

### ISSUE THREAD

**Issue by Danfro** [HelloVolla/volla-os-beta-test#126]
The predefined entry "contacts" in the springboard does **only** list contacts that are marked as favourites. This is not intuitive for the user to know/understand. It would be clearer if that entry would be labelled "contact favourites" or "favourite contacts". Then users will instinctively know that not all contacts are supposed to appear there.

**Comment by wurzer** [comment]
The basic idea of the "collections" is quick access to the most important in the sense of recent or selected content. The purpose is a reduction that keeps the head clear and creates an overview. The collection of contacts shows not only the favorites, but also the contacts with whom a user was last in contact through a call or exchange of messages. All contacts are displayed in the Contacts app and are also included in the text field when you start typing a name.
