### ISSUE TITLE
X23 -  After update, the 48MP option is missing in the camera 

### ISSUE THREAD

**Issue by Achim242** [HelloVolla/volla-os-beta-test#127]
X23, VOS12.1
12-20231102-STABLE-vidofnir

 After the update, the option to set the image resolution to 48 MP is missing in the camera.
The maximum resolution is now only 12 MP. 
Switching on the button in the top right-hand corner brings the following steps: Main camera - Wide angle - Selfie camera - and again from the beginning. 

The problem also applies to the Open Camera from the F-Droid Store.

Here is a screenshot of the settings:

**Comment by Achim242** [comment]
![Screenshot_20231111-173227_Kamera](https://github.com/HelloVolla/volla-os-beta-test/assets/140107687/9a838322-0960-4398-869b-d0fce93e2f88)

**Comment by Achim242** [comment]
![Screenshot_20231112-142950_Open Camera](https://github.com/HelloVolla/volla-os-beta-test/assets/140107687/7c5bc966-cfac-400f-962f-9325fdd101f7)
Open Camera

**Comment by wurzer** [comment]
Obviously a library for the specific camera support is missing in the new firmware. Thanks for the report

**Comment by Achim242** [comment]
The problem has been fixed with the beta update from 16.11.23.

I'm closing the thread. Thank you. ✌️
