### ISSUE TITLE
X23 - Torch only lights up dimly. 

### ISSUE THREAD

**Issue by Achim242** [HelloVolla/volla-os-beta-test#128]
X23 / VOS12.1
12-20231102-STABLE-vidofnir

After the last update, the torch only lights up with reduced power, very weak. 
However, the flash light is at full power when taking photos. 
Two other X23 users from the Telegram group report the same. 
Below is a short video from one user, where the light is fully on one time and only dimly on the next.

**Comment by Achim242** [comment]
https://github.com/HelloVolla/volla-os-beta-test/assets/140107687/674746e4-2e21-45b9-b313-5f046e846670

In my case, however, the light is permanently dim.

**Comment by Lumine269** [comment]
I can confirm this on my x23.

**Comment by rachyandco** [comment]
i can confirm on x23 with latest update:  12-20231102-STABLE-vidofnir

**Comment by franco-bez** [comment]
I can confirm this on my X23 - first time activated - the flash light is bright - starting from the second time it's dim.
12-20231102-STABLE-vidofnir

after a reboot the torch light is bright again, but only once

**Comment by franco-bez** [comment]
Just updated to VollaOS 12-20231128-STABLE-vidofnir

The bug is still there

**Comment by wurzer** [comment]
Yes, as expeceted. We didn't fix it yet.

**Comment by Achim242** [comment]
fixed in Beta Release 23.01.2023

Thank you.
