### ISSUE TITLE
unclear UI and difficult handling

### ISSUE THREAD

**Issue by Danfro** [HelloVolla/volla-os-beta-test#130]
The UI for the volla phone specific settings is not clear about different handling of entries. Also the first two entries are difficult to use in my opinion.

As you can see on the screenshot below, all entries look exactly the same. All entries, except the first two, open some sort of list when tapping on them. But there is no indication at all, that the first two behave entirely different than the others. 

The first two entries need to be used with press&hold. But that is not clear. Intuitively a new user will try to tap them. This only results in a kind of flicker but nothing happens. Actually I first thought something is broken there, so I did a system update first.

Also when press&hold, the actions are obscured by you hand. But you can't move the hand away since it needs to keep holding down the finger. One needs to kind of look around ones own hand. Not great.

Why not make "Sicherheitsmodus" a toogle? That would be clear and much easier to use?
The theme could be a chooser component the same as search engines. Tap to open the list, show three options, only allow to select one.

![image](https://github.com/HelloVolla/volla-os-beta-test/assets/37637312/9d7da96a-4052-46af-9455-e874d142a55a)

**Comment by wurzer** [comment]
Yes, there are different kind of settings with different was of interaction.

**Comment by Danfro** [comment]
Vielleicht ist mein Anliegen auf Deutsch besser formulierbar bzw. verständlich. 

Bitte entschuldigen Sie Herr Dr. Wurzer, aber mir ist schon klar, dass es sich um unterschiedliche Komponenten handelt. Ich erstelle selbst Apps und Code. Es geht mir darum, Rückmeldung zu geben, an Stellen wo aus meiner Sicht Verbesserungspotential besteht.

Ihr Kommentar löst das Problem keinesfalls. Wenn ich sage, als neuer Nutzer dachte ich zuerst es handelt sich hier um einen Softwarefehler, meine ich das Ernst, genau so ging es mir. 

1. Fehler
Ich habe diese obersten zwei Elemente angetippt, so wie die anderen. Der Bildschirm hat kurz geflackert, mehr ist nicht passiert. Erst nach dem Update und herumprobieren ist mir aufgefallen, dass hier bei gedrückt halten ein anderes Verhalten stattfindet.

2. Fehler
Intuitiv drückt man auf den Bereich mit der Schrift, nicht rechts daneben. Der bei gedrückt halten aufgehende rot hinterlegte Bereich öffnet sich nach unten. Die Fläche wird somit immer zunächst von der Hand verdeckt, wenn der Finger auf dem Tippelement ruht. Er muss ja die ganze Zeit gedrückt halten. Der Nutzer muss dann um die eigene Hand "irgendwie herumschauen". Das ist unpraktisch.

3. Sache
Was ich auch nicht verstehe ist, welche Bedeutung das Schlosssymbol neben "Sicherheitsmodus AN" hat. Dieses ist auch bei deaktiviertem Sicherheitsmodus vorhanden. Wenn es nur sichbar wäre, wenn der Sicherheitsmodus an ist, ok (Schloss = Gerät ist gesichert). Aber es ist ja immer zu sehen.

Aus meiner Sicht ist dieses Verhalten hier vor allem schlichtweg nicht nötig. Ich erkenne auch keinen Mehrwert durch Verwendung der aktuell implementierten Komponenten.

Für den ersten Punkt der Themen/Modus Auswahl kann die gleiche Komponente verwendet werden wie für die Suchmaschine. Antippen öffnet drei Zeilen mit den Themen. Nur ein Thema kann ausgewählt werden. Konsistentes Verhalten erreicht.

Für den Sicherheitsmodus kann ein Schalter verwendet werden. "Sicherheitsmodus aktiv .... SCHALTER". Keine Notwendigkeit überhaupt erst ein Untermenü zu öffnen. Alternativ die gleiche Komponente wie für den Modus/die Suchmaschine.
Man könnte sogar das Schloss als Symbol bzw. Schalterdarstellung verwenden. Ein durchgestrichenes Schlosssymbol für ungesichert/"nicht abgeschlossen" = Sicherheitsmodus deaktiviert und das Schlosssymbol für gesichert/"abgeschlossen" für Sicherheitsmodus aktiviert.

**Comment by wurzer** [comment]
Analog zum roten Punkte, verwendet die Volla App eine vereinfachte Gestenbedienung: Berürhren, Bewegen, Loslassen. Das gilt für alle rot hinterlefgten Menüs. 

Das geschlossene Schloss bedeutet, dass der Sicherheitsmodus an ist, das geöffnete Schloss, dass der Sicherheitsmodus ausgeschaltet ist.

**Comment by Danfro** [comment]
Das mit den Schlössern klappt aber so nicht. Hier ist der Sicherheitsmodus aus, aber es wird hinter "Sicherheitsmodus AN" ein geschlossenes Schloss angezeigt.

![image](https://github.com/HelloVolla/volla-os-beta-test/assets/37637312/3c8c8934-f8a0-4317-843b-2fa021038ec9)

**Comment by wurzer** [comment]
Kann ich bestätigen. Dass offene Schloss wird nicht gezeigt. Schaue ich mir an.
