### ISSUE TITLE
Belgium KBC App

### ISSUE THREAD

**Issue by ruditimmermans** [HelloVolla/volla-os-beta-test#131]
We have a problem here in Belgum we have an Bank app called KBC Mobile it's not possible to test it becoss you need a bank account into Belgium, but when i install the app works, but when i add an bank account i get a small pop-up the app would not be downloaded from Google Play Store, i have talked with Rahul from AuroraStore and he told me this become of the packagename Which would be

"[com.aurora.store](http://com.aurora.store/)" for Aurora Store
"[com.android](http://com.android/).vending" for Play Store

This difference in installer packagename is what app dev check & warn you. Its not something that could be fixed from store its behaviour of the os.

This is the link to the App:

https://play.google.com/store/apps/details?id=com.kbc.mobile.android.phone.kbc

**Comment by wurzer** [comment]
We discussed the topic as a team. If we were to change the source of the installation on the system side, this would lead to a loss of security. Currently, app sources must be explicitly authorized.

**Comment by ruditimmermans** [comment]
Yes i understand that but then the problem would be for Belgium people as there are a lot users that have this bank, and you can not ask them to change from bank when the buy a phone so this is a big problem....

Into other words it would be verry hard for Belgium people to use a Volla Phone.....

**Comment by wurzer** [comment]
If we find the responsible developer of the app, we may can convince him to include Aurora as a valid source, because the app comes directly from Google Play Store.
