### ISSUE TITLE
X23- issues with the "search-button" 

### ISSUE THREAD

**Issue by Achim242** [HelloVolla/volla-os-beta-test#132]
X23 / VOS12.1
12-20231102-STABLE-vidofnir

The orange button on the left side, is called the "search button". 

1) In the settings there is a slider labelled "Wake up device". If this means "Wake up display", this does not work. There is also no option to switch on the display in the following two submenus "short press" and "long press". (see screenshot) 
The options for "short press" all work, I am currently using the button to switch off the screen. But I would like to wake up the screen. 

2) The options under "long press" do not work. A long press does not result in any action, regardless of whether you select a double assignment with "short press" or "no action" for "short press". 

One wish of us X23 users for the future would be to be able to configure this button individually. 

Thank you. 

![Screenshot_20231120-194824_LineageOS-Einstellungen_1](https://github.com/HelloVolla/volla-os-beta-test/assets/140107687/613360e0-0148-4e3b-bc63-014d199029a5)

**Comment by wurzer** [comment]
1. Yes "search button" is the correct name from Android
2. Wake up works for the volume button. See the headline ot this group of settings.
3. Any app can offer a feature for this button, but it must be implemented by the developer.
4. I can confirm, that long press is not working

**Comment by Achim242** [comment]
>     3. Any app can offer a feature for this button, but it must be implemented by the developer.
> 

Okay, Thanks for the info. 
But could it be possible in the future to switch on the screen with this button?

**Comment by franco-bez** [comment]
wake up with search button and long press action is working now with VollaOS 12-20231228-STABLE-vidofnir

**Comment by Achim242** [comment]
Yeahh, everything is working fine now. I am now closing this thread. 

Many thanks to the whole team! 
Best regards

**Comment by Achim242** [comment]
Yeahh, everything is working fine now. I am now closing this thread. 

Many thanks to the whole team! 
Best regards
