### ISSUE TITLE
apps can access the network even when network access is disabled

### ISSUE THREAD

**Issue by Danfro** [HelloVolla/volla-os-beta-test#133]
With current VollaOS 12.1, Volla22, the setting "Netzwerkzugriff erlauben" for apps does not work. According to [Mr. Aurel in Telegram](https://t.me/hello_volla/96104)  this has been done deliberately, the function has been bridged.

**This is a severe security vulnerability in my opinion.** If a user sets network access for an app to disabled, it is expected to have no network access anymore. Many apps send private data, and preventing them to access the network is an easy way to achieve more privacy.

If the option would be greyed out and all access enabled, it would at least be clear for the user that they need to find other means to block network access. But this solution (bridging but leaving the option functional) is simply wrong! The user has no idea that the app can still fully access the network.

**Comment by tux4us** [comment]
After the problem was discussed today and I became aware of it, I tested it and can confirm the concern of the problem report here.

VollaOS 12.1 stable

**Comment by wurzer** [comment]
See #112

**Comment by wurzer** [comment]
We disables this feature to support the VPN susystem settings for contineous and exclusive VPN connection. Looks like we can only support one of the two features.

**Comment by Danfro** [comment]
I am sorry, I missed the old post. Thanks for the link.
