### ISSUE TITLE
Feature request: Move the SD card option "Internal memory expansion" to developer mode 

### ISSUE THREAD

**Issue by Achim242** [HelloVolla/volla-os-beta-test#134]
Hello again,

Since there is always trouble from users who accidentally set up their SD card as "internal memory extension" instead of "mobile memory", we hereby ask whether it would be possible to deactivate this option or move it to the developer options.

Greetings from the support team of the Telegram / Matrix channel "Volla User Community"

**Comment by wurzer** [comment]
I also thought about this conclusion. We'll definately discuss it

**Comment by wurzer** [comment]
Almost hidden option in Volla OS 13
