### ISSUE TITLE
Replace SimpleMobileTools applications

### ISSUE THREAD

**Issue by je-nix** [HelloVolla/volla-os-beta-test#135]
With the acquisition of the SimpleMobileTools applications by ZipoApps (see https://github.com/SimpleMobileTools/General-Discussion/issues/241), future development of the apps is unclear. The open source builds will probably become unmaintained as the business model of ZipoApps is bundling the app with adware (which already happened with the play store versions). There already are a lot of discussions about the legal aspect of this move, so lets focus on the impact to Volla OS here.

As Volla OS uses some of the apps from the SimpleMobileTools suite I believe it is a good moment to start looking (and then implementing) alternatives. While the current state does not mean that the apps stop working instantly, without maintenance there always is a risk of unfixed issues or incompatibilities with newer Android versions.

The current best alternative seems to be https://github.com/FossifyOrg , a fork of the original project by naveensingh, one of the SimpleMobileTools contributors. As it is probably to early to determine which fork / project will prevail, I'll leave this issue here a a reminder.

**Comment by wurzer** [comment]
We will have a look at it. We may replace the app or kepp the open source version/fork.

**Comment by gbdomubpkm** [comment]
I completely agree with this. Integrating SimpleMobileTools into the Volla system no longer makes sense, buggy and not updated, takes up unnecessary space. https://github.com/FossifyOrg is a good option and even more so for the new Volla tablet.

**Comment by wurzer** [comment]
We are working on that. But It's not trivial. We need a migration path for apps with relevant data like contacts and calendars
