### ISSUE TITLE
Error msg in Email app: 'No app supports this kind of attachement'

### ISSUE THREAD

**Issue by Dricc123** [HelloVolla/volla-os-beta-test#14]
Steps are:
- start a new email
- click on the trombone icon to attach a file
- choose 'File'
error appears (screenshot below)

Note: i found another way: choose 'Photo' instead of 'File', then take the sandwich icon to browse the phone content and select my document.

Comment: it is counterintuitive to choose 'Photo' when what I really want is not a photo.

![Screenshot_20201205-224446](https://user-images.githubusercontent.com/75565258/101277759-f0e44780-37b6-11eb-9805-372540cfa95b.png)

**Comment by wurzer** [comment]
We switched to K9 app for newer deivces. The Mail app of AOSP is deprecated
