### ISSUE TITLE
missing Volla Security Mode toggle in quick settings

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/volla-os-beta-test#140]
my X23 is running 12-20231217-BETA-vidofnir.

in the realease notes you can read the announcement:

_16. Dezember (beta)
  Introduction of Volla Board beta for speech to text
  **Introduction of Volla Security Mode toggle in quick settings**
  Android December security update
  APN Database update for LTE data connection
  Fix for long press of extra button (Volla Phone X23)_

there is no way to to toggle Volla Security Mode in quick settings, at least I can not find anything.

**Comment by wurzer** [comment]
Yes, if you tap on the pencil button of the quick settings you find a tile, that you can move to the top and toggle securoty mode afterwards. We are still working on necessary improvments. But it works.

**Comment by franco-bez** [comment]
how does this tile look like, what's it called?
I have looked at all tiles available on my X23 and could not find anything suitable.

**Comment by wurzer** [comment]
The icon is confusing. We need to replace it. It wasd taken from an oder concept. You see a pctzrogram of a parent and child.

**Comment by franco-bez** [comment]
the icon is not there - these are all I got:

![Screenshot_20231221-150117_FairEmail](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/542f7885-4ed0-458b-9cea-96203233d04c)
![Screenshot_20231221-150104_FairEmail](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/8ba2d52d-b784-43f9-b9bb-a040f8bc8dfe)
![Screenshot_20231221-150050_FairEmail](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/5a0ef671-f497-4b56-baf8-60779e95674e)
![Screenshot_20231221-150031_FairEmail](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/2d686996-3b09-420a-a517-c0d06c1c174a)

**Comment by wurzer** [comment]
Re-scheduled for the January update

**Comment by franco-bez** [comment]
in the most recent beta realease the issue is fixed
