### ISSUE TITLE
Alarm is delayed

### ISSUE THREAD

**Issue by StaffanMelin** [HelloVolla/volla-os-beta-test#142]
The alarm clock is not precise. Last morning, it chimed three minutes after the set time.

Might be related to https://github.com/HelloVolla/volla-os-beta-test/issues/141.

**Comment by wurzer** [comment]
Please activate server time iin the system settings.

**Comment by StaffanMelin** [comment]
Thank you for your quick answer. But why did you close the issue?

Where can I find "server time"? Do you mean Settings > System > Date and time > "Set time automatically"? It has been set to "on" for as long as I have owned the phone.

**Comment by StaffanMelin** [comment]
This is also reported on the forum, https://forum.volla.online/viewtopic.php?f=4&t=1062, where the advice is to install another alarm app. I will try that one. If that works maybe the current standard Clock app should be fixed or removed?

**Comment by wurzer** [comment]
It's not reproducable

**Comment by StaffanMelin** [comment]
OK, but it seems to be reported by more than me.

What did you mean by "server time"? Where can I find that setting?

Thanks!

**Comment by wurzer** [comment]
1. Open system settings
2. Select date & time
3. Enable automatic time

I also use the clock and alarm app daily to wake up on time. You can also configure the interval time and max reminder time in the clock app.

**Comment by StaffanMelin** [comment]
Yes, as I wrote I already have that one enabled (it has always been on).

**Comment by wurzer** [comment]
Ok, haben Sie vielleicht die Domäne oder IP-Adresse des Zeit-Servers gesperrt? Mit dem neuen Volla OS Release im Januar sind wir zu einem Zeit-Server von Hetzner gewechselt.

**Comment by StaffanMelin** [comment]
Danke. Keine IP-Adresse sind gesperrt. Ich kann es mit Ping versuchen, wenn Sie mir IP an aktuelle Zeitserver senden, bitte.

Vielen dank! :) (And excuse my rusty German, I am Swedish.)

**Comment by wurzer** [comment]
Sorry for mixing up the languages. The time servier is definately called after a reboot. You can checl it with Wireshark. Is the time and date exact, that is whon in the clock app or status bar?

**Comment by StaffanMelin** [comment]
Yes, the status bar shows the correct time and date.

An example of my problem: I set the alarm for 7:30. When the alarm goes off I look at the time of the phone and it shows 7:34.

I used the open source tool/app PCAPdroid to capture network traffic at restart of my X23, and can see in Wireshark that it makes a query to https://time.akamai.com/. Is that the correct call to set the time?

**Comment by StaffanMelin** [comment]
```
No.	Time	Source	Destination	Protocol	Length	Info
30	1.081495	10.215.173.1	10.215.173.2	DNS	61	Standard query 0x0c28 A time.akamai.com
31	1.092148	10.215.173.2	10.215.173.1	DNS	157	Standard query response 0x0c28 A time.akamai.com CNAME time.akamai.com.edgekey.net CNAME e1534.dscb.akamaiedge.net A 23.40.124.221

```

**Comment by wurzer** [comment]
No we are not using hetzner. You need to filter the time protocil. Anyway. I'm using the ore instralled clock app to wake up in the morning or other notifications. I didn't notify any delay. Are you using the reminder or some other intervall?

**Comment by StaffanMelin** [comment]
I found a call to akamai, not hetzner, as you can see in the log. Is Volla OS currently using an akamai-service?

And, this was not a reminder, it was the original wakeup call.

Did you see my link (https://github.com/HelloVolla/volla-os-beta-test/issues/142#issuecomment-1911604072) where another user recommend switching to another Clock app? I don't seem to be alone with this problem.

I will try https://f-droid.org/en/packages/com.better.alarm/ and see if that app is more accurate.

BTW All my apps as well as Volla OS are updated to the latest version.

**Comment by wurzer** [comment]
Unfortunately I can't reproduce the issue. I use the alarm app each day. Maybe resetting the alarm clock app helps.

**Comment by StaffanMelin** [comment]
I tried the https://f-droid.org/en/packages/com.better.alarm/ app, the Simple* guy, and it woke me on the right minute. So problem solved.

And I learned a new tool for tracing network traffick in the process.

Anyway, thank you for your help! And in genereal I am VERY pleased by my X23. Thank you for making it! :)
