### ISSUE TITLE
 Volla Security Mode - DNS

### ISSUE THREAD

**Issue by huseyinkogo** [HelloVolla/volla-os-beta-test#143]
Hi,

Note i accidentally post this issue on the wrong repo, im sorry about that. https://github.com/HelloVolla/android-launcher-qt/issues/213#issue-2091293835

Version: 12-20231228-STABLE-mimameid

Recently i have updated my firewall settings on my business & home networks. Where i have disabled DNS lookup to every device, where i just want all the devices to use local DNS.

PROBLEM:
Yesterday I was playing with the Security Mode, when it is ON. The device is only using the 1.1.1.1 DNS.

How can this be disabled?

**Comment by wurzer** [comment]
@erfanoabdi Can you check this behaviour

**Comment by huseyinkogo** [comment]
sorry any update? @erfanoabdi

**Comment by wurzer** [comment]
Yes, the security mode must use another locaal DNS service, becuase it filters domains.

**Comment by huseyinkogo** [comment]
@wurzer on my VLAN, the DNS servers are set 10.1x.xx, 10.1.x.xx. on the security mode, it forces the phone 1.1.1.1 DNS, where i can't access my local hosted instances. (they are accessible via locally, they are not public)
