### ISSUE TITLE
Can not upgrade to UT OTA-4 in new Volla boot manager

### ISSUE THREAD

**Issue by RinkebyDanceKids** [HelloVolla/volla-os-beta-test#144]
Hi.

So, I can not seem to be able to upgrate Ubuntu Touch as before. Nor droidboot as it crashed 

![Screenshot_20240207-231203_Volla Boot Manager](https://github.com/HelloVolla/volla-os-beta-test/assets/147806721/033005f3-1d43-48c2-b12c-377839507240)
Clicking download. And it crashes.

![Screenshot_20240207-231215_Volla Boot Manager](https://github.com/HelloVolla/volla-os-beta-test/assets/147806721/cd23bf98-467b-425d-85d1-6d20b1c1eca4)
Dont understand interface. But no option to upgrade.

![Screenshot_20240207-231226_Volla Boot Manager](https://github.com/HelloVolla/volla-os-beta-test/assets/147806721/56e70e94-de0a-44d3-856d-897cae00aa87)
Closrs I get is backup and restore. To later choose flash image. But no image to download?

So. How do I do this? Whipe all out and start from begining by backing up the home image?

**Comment by RinkebyDanceKids** [comment]
And. Really. I cant find a manual for such critical operation. And nobody wants to answer on volla forum, or here?

**Comment by wurzer** [comment]
OTA-4 is not available yet for Ubuntu Touch as a second operating system. You will be able to update Ubuntu Touch in the Volla Boot Manager.

**Comment by RinkebyDanceKids** [comment]
OK, then I will cool my jets. Thanks!
