### ISSUE TITLE
Streaming the screen to an external monitor does not work

### ISSUE THREAD

**Issue by tux4us** [HelloVolla/volla-os-beta-test#147]
VollaOS 13-20240213-BETA-mimameid
VollaPhone 22

Streaming the screen to an external monitor does not work to Blaupunkt TV (Miracast)

With the update to VollaOS 13 beta, the streaming function is unfortunately no longer active. The connection is displayed as "connected" under connected devices - connection settings - streaming. However, there is no screen transmission.
Searching for the device to be connected again, rebooting the phone, deleting the connection and reconnecting does not improve the situation.

**Comment by wurzer** [comment]
I'm hapy to confirm, that I can't reproduce it for the next beta release, that will be soon published

**Comment by tux4us** [comment]
Thanks

**Comment by wurzer** [comment]
I can stream Miracast on Volla Phone 22 and X23. It's a known issue for Volla Phone 1 and Volla Phone X
