### ISSUE TITLE
app switcher stops working 

### ISSUE THREAD

**Issue by Lotechus** [HelloVolla/volla-os-beta-test#149]
App switcher eventually stops working. Force closing trebuchet fixes it until it happens again.

**Comment by wurzer** [comment]
What do you mean by app switcher?

**Comment by Lotechus** [comment]
That's what its called in the menu. Where you can switch between all apps. I use it mapped to the side red button. Occasionally an app will go white or clear and then I can no longer get to that menu until I force close trebuchet. 
Jarette Senek

**Comment by wurzer** [comment]
It's a trebuchet feature? I can't find a red button or menu in trebuchet.

**Comment by Lotechus** [comment]
It is in system, buttons.
I attached a picture. 

It must be related to trebuchet as force closing trebuchet fixes the glitch of the apps switcher no longer working. 
Jarette Senek

**Comment by wurzer** [comment]
I can't find an app switch feature in system settings, buttons.

**Comment by Lotechus** [comment]
I'm using Volla OS but not Volla Launcher. I'm using trebuchet as a launcher and I guarantee it's in there.

**Comment by Lotechus** [comment]
![Screenshot_20240420-121350_Trebuchet_1](https://github.com/HelloVolla/volla-os-beta-test/assets/10366147/1756c1d0-9bdd-4cc9-8431-c8198fe96083)

**Comment by wurzer** [comment]
Verstehe, auf meinem Volla Phone X23 mit Volla 13 von März kann ich keinen Fehler reproduzieren.
