### ISSUE TITLE
No option to share by email

### ISSUE THREAD

**Issue by Dricc123** [HelloVolla/volla-os-beta-test#15]
> We have no insights to the source code of the e foundation. Usually this feature is defined int he manifest of an app. We are currently working on an update of Volla OS, that is based on Android 10, that likely with include your requested feature.

Am 05.12.2020 um 12:53 schrieb Cedric D <cedricoola@free.fr>:

Do you know why it is working on e.foundation OS based on AOSP as well? Can you ask the developers?
Regards,

On Dec 5, 2020 12:09, "Dr. Jörg Wurzer" <info@volla.online> wrote:
It’s mainly the pure AOSP email app.

Am 05.12.2020 um 12:01 schrieb Cedric D <cedricoola@free.fr <mailto:cedricoola@free.fr>>:

Isn't your Email app derived from K9? Looks like it. Volla made the fork, so Volla configured it, so Volla can rethink this setting, isn't that right?

On Dec 5, 2020 11:19, "Dr. Jörg Wurzer" <info@volla.online <mailto:info@volla.online>> wrote:
It’s a limit of the E-Mail app. For Android each app has to provide it’s options to receive shared content.

Am 04.12.2020 um 23:52 schrieb Cedric D <cedricoola@free.fr <mailto:cedricoola@free.fr>>:

Why is it not possible to share a picture from within the Galerie? I was used to this use case. Very practical, especially when using the app 'Send Reduce' from the F-droid store that reduces the file size of the selected image and opens a new email with the reduced image attached.
Cedric

On Dec 4, 2020 22:52, "Dr. Jörg Wurzer" <info@volla.online <mailto:info@volla.online>> wrote:
Thanks correct. You need to add a photo as an attachment within the email app.

Am 04.12.2020 um 20:41 schrieb Cedric D <cedricoola@free.fr <mailto:cedricoola@free.fr>>:

In the image gallery when i press the share icon, i can share with different apps but the Email app is not listed...

**Comment by Dricc123** [comment]
Neither is there an option in the 'Share' icon menu to 'Copy to clipboard' :-(

**Comment by wurzer** [comment]
Long press on any text and copy the selection to the clipboard. Other media than text is must shared by the sharing menu and the each app developer decides, which kind of content the app can share with other apps and which kind of content the app can receive from other apps. This is build in standard feature of Android, that works with Volla OS.

**Comment by wurzer** [comment]
We switched from AOSP App to K9-App in Volla Os for Volla Phone 22. This app can also be installed on Volla OS for the other devices with F-Droid.
