### ISSUE TITLE
Upgrade to VollaOS 13 might lead to data loss in Contacts App

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/volla-os-beta-test#151]
Several Reports in the Volla User TG group and the forum.
It seems that when upgrading to VollaOS 13 the contacts stored in the "Phone" target might get lost.
The target "Phone" ist no longer present in the contacts app.

Workaround is to clear the cache and storage of the contacts app and import the contacts from a vcf backup.
If no backup is present, data is lost.

The import does no longer offer a target named "Phone", instead there is a target named "DEVICE" which works just the same as "Phone" did under VOS 12.

It seems that mainly Volla X23 are affected.

Here one user report in the forum
https://forum.volla.online/viewtopic.php?p=5161

**Comment by Achim242** [comment]
I can confirm this exactly on X23.

**Comment by wurzer** [comment]
This is unlikely. Volla OS 13 didn't change the contact app or the contact data in user space. I updated my Volla Phone 22 with more than two thousand contacts with no issue. 

Please specify, where the contacts have been stored (system or app) and wether the contacts are synchronized. If they are synchronized please specify the sync method and app.

**Comment by franco-bez** [comment]
I can only contribute the details of my own case.
I updated on Feb 21 to VOS 13 Beta in order to test the network access.
https://github.com/HelloVolla/volla-os-beta-test/issues/112#issuecomment-1957718971.
Several days later I noticed that the adressbook was missing data.
I did not at first see any connection to the update so I merely imported my backup vcf file and almost forgot about it.
Before the upgrade my contacts were in the "Phone" target, they had been imported via vcf file and were/are not synced to any account.

When I heard about someone complaining about the loss of contacts in the TG group I remembered the issue.
Now there are several known cases in the TG group.
It seems that mainly, if not exclusively X23 are affected.
In the TG group there are also several reports of people who state NOT to be affected and that the upgrade went well. It's just not clear if all of them are V22 users.

**Comment by franco-bez** [comment]
Since the upgrade the target "Phone" is gone, and the target "DEVICE" appeared after clearing cache and data of the contacts app.
![Screenshot_20240404-143319_Trebuchet](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/70c2928e-86ac-48d7-9c0d-945980f9e0dd)

**Comment by wurzer** [comment]
The reason is an updated data base scheme of Android 13. We are investigatin gin a migration solution. This affects contacts that are stored in the system database and are not synchronized. These users should should export the contacts and re-import them after the updatel

**Comment by toby63** [comment]
I also once lost all contacts on update. 
I thought that it had something to do with the contacts app at first, but they said that it is stored in Android directly.

**Comment by franco-bez** [comment]
There are several new reports in the TG group.
One user reported to have three targets, two of them appear to be the same target with different names.
https://t.me/hello_volla/109615

**Comment by franco-bez** [comment]
Additionally the user states that the contacts did not get lost immediately after the upgrade, but several days later

**Comment by babinos87** [comment]
This is what happened to me as well after upgrading my X23 to Volla OS 13. Most contacts are gone (I still have some because I have them in other messaging apps as contacts). Loading from a `.vcf` file loads the contacts without any names, all I have now is a massive phone book with no names.

**Comment by wurzer** [comment]
This issue is not solved with the recent April release. Looks like that the contact lost was triggered once another app synchronized contacts, than the contact app. That was the reason, why our QA didn't notice the issue.
