### ISSUE TITLE
OpenEUICC crashes on X23

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/volla-os-beta-test#152]
When I tap on OpenEuicc I get the message that no euicc is found , it closes within one second. Trying several times in order to read the message there is another message telling me the euicc app crashed several times ...

I do not know if the fact that I have installed two physical sims installed causes the crash.
![Unbenannt](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/2ff1971b-6a3a-442d-943a-954c566bcc4f)
![Unbenannt2](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/8d96c3b2-144b-45d8-bfd2-7c1827a3d6a6)

VOS 13-20240330-STABLE-vidofnir.

There is thread in the forum of somebody with a similar problem on the X23
https://forum.volla.online/viewtopic.php?f=4&t=1158

**Comment by franco-bez** [comment]
![image20240406_083400193](https://github.com/HelloVolla/volla-os-beta-test/assets/4195055/10b35ee3-be39-4dd2-b0bb-23a6872d75fe)

**Comment by wurzer** [comment]
We will try to reprocude it and provide an update of this app

**Comment by wurzer** [comment]
Can't reproduce it on a Volla Phone X23 with Volla OS 13. You may try to reset the app. However we will publish an update of this app in the next beta release.

**Comment by franco-bez** [comment]
13-20240430-STABLE-vidofnir Situation unchanged. OpenEUICC still crashes every time.
Maybe triggered by the fact that two physical sim cards are inserted.
Occasionally I will try with an empty sim slot.

**Comment by franco-bez** [comment]
I did a little more testing.
13-20240503-STABLE-vidofnir
1. no physical sim inserted - does not crash - good
2. SIM.de sim card in slot1, slot 2 empty - crashes immediately
3. SIM.de sim card in slot2, slot 1 empty - crashes immediately
4. Telekom sim card in slot1, slot 2 empty - does not crash - good
5. Telekom sim card in slot2, slot 1 empty - does not crash, but ERROR message "No eUICC found on this device" stays there.

It is the same SIM.de sim card that also makes trouble with Ubuntu Touch. See:
https://gitlab.com/ubports/porting/reference-device-ports/halium12/volla-x23/volla-vidofnir/-/issues/11

**Comment by franco-bez** [comment]
eSIM Manager still crashes when a physical SIM is in the phone and active.
14-20250723-stable-vidofnir

If the physical SIM is removed or at least deactivated, then the eSIM Manager does not crash.

**Comment by franco-bez** [comment]
seems to be fixed in 15.0-20250728-BETA-vidofnir.
Good job!
