### ISSUE TITLE
Battery charge limitation feature missing in VOS13

### ISSUE THREAD

**Issue by TFleury** [HelloVolla/volla-os-beta-test#154]
The battery charge limitation feature that was present in VOS12 is no more present in version 13.

Please bring it back.

Hardware : Volla Phone 22

**Comment by franco-bez** [comment]
It is still there, just the dialog for the configuration was changed.
In my german OS it's under
Einstellungen -> Akku -> Ladekontrolle -> Lademodus -> Begrenzung
in english should be
Settings -> Battery -> Chargecontrol -> Charging Mode -> Limit
There is a slider control where you can adjust the limit

**Comment by TFleury** [comment]
Thanks, I found it 👍

**Comment by wurzer** [comment]
1. Go to "Battery" in system settings
2. Go to "Charging control"
3. Activate charging control
4. Set the limit
