### ISSUE TITLE
Volla OS 13 battery consumption 6 times higher than on Volla OS 12

### ISSUE THREAD

**Issue by Termalator** [HelloVolla/volla-os-beta-test#155]
After the last system update (not Beta) is the battery consumption much higher then before.
This behavior already occurred when updating OS 12. I have already posted a threat in the forum.
[https://forum.volla.online/viewtopic.php?f=4&t=1004&start=20](url)
![Screenshot_20240404-032512_Einstellungen](https://github.com/HelloVolla/volla-os-beta-test/assets/34917750/4956242a-d99c-42b6-89c9-76ce1fb8a291)

**Comment by wurzer** [comment]
Can't reproduce a hiher battery drain. How do you compare the battery drain?

**Comment by Termalator** [comment]
Just that simple: same usage before the update to OS 13 the battery lasted 7-12 days, after the update less then 2 days. Of course i cannot go back to 12 and proof that, but interesting thing is that there is something that uses big amount of power  and is not listed in the battery usage.

P.S. I am not alone with that problem

**Comment by Termalator** [comment]
here are the last statistics there is definitively something wrong :
![Screenshot_20240414-174753_Trebuchet](https://github.com/HelloVolla/volla-os-beta-test/assets/34917750/8de6829e-82be-46b9-8d44-23e818acf11a)
![Screenshot_20240414-174803_Trebuchet](https://github.com/HelloVolla/volla-os-beta-test/assets/34917750/d1d916b3-cc93-46d7-a27c-583022a9d5d5)

**Comment by wurzer** [comment]
We can't reproduce this issue after some tests and investigation. So we need to know the special conditions of your system. The device specs of Volla Phine 22 are up to 250 hours idle time with one SIM card and 160 hours with 2 SIM cards. 

You have a significantly higher battery consumption (800%) than on my Volla Phone 22 for idle mode. Please check which background processes are active. 

I also recognize a significantly higher energy consumption (400%) for the connection in the mobile network. This could also indicate background processes with data connection.

Please activate the developer settings and check the active services. It could be helpful if you could share a screenshot of this.

**Comment by wurzer** [comment]
@techyminati @erfanoabdi Please have a look

**Comment by erfanoabdi** [comment]
i need bugreport from a whole day normal usage of android13 from 100 to 0:  

1. Enable [Developer Options](https://developer.android.com/studio/debug/dev-options).
2. In Developer options, tap Take bug report.
3. Select the type of bug report you want and tap Report.
4. After a moment, you get a notification that the bug report is ready.

To share the bug report, tap the notification.

**Comment by Termalator** [comment]
I am using the Volla X23, do You need a bug report for 100% - 0% load or for one Day?

**Comment by GreenwoodLMGU** [comment]
I can verify this on my Vollaphone **22** too. The power consumption screenshot would look just the same, so I desisted from posting it. Attached you find the bug report my phone has created.

It seems that the wifi connection is the culprit - when I turn that off, power consumption goes down. I have no background apps running (apart from the ones I think are necessary) and am in power saving mode. Activating some background processes does not lead not a noticably higher power consumption. Even restricting the Android system in power consumption does not change a thing.

It really is quite annoying.

The second Vollaphone 22 in my family has no such problems and I have not been able to find out why.

**Comment by Achim242** [comment]
I had already mentioned a deterioration in battery performance in the VOS 13 beta group.
In my observations, I noticed up to 7%/h with moderate use. Battery is only ever charged to 90%. (At night, without parallel use. )
 
System and sleep mode are rather inconspicuous for me. 
I now have the energy-saving mode running permanently, display brightness on automatic, and a few other background activities restricted, with no success. 
I unplugged it every day at 6 a.m.  at 90%, and after a good 10 hours I'm at ~ 40%. 
That's also 5%/h, which is still a lot.
Under VOS 12 it was still ~ 3.5%/h.

Last night i did a test: I charged up to 90%. Then I unplugged it at around 11 pm and left it switched on overnight. WLAN, mobile data and Bluetooth were switched off. 
This morning at 6 a.m. the battery was only at 47%! (without use!) That's 43% battery usage in 7 hours! (as I said: WITHOUT use) 
Sorry, but that is not acceptable. 
A screenshot from this morning follows.

**Comment by Achim242** [comment]
X23 13-20240330-STABLE-vidofnir
![Screenshot_20240424-054927_Einstellungen](https://github.com/HelloVolla/volla-os-beta-test/assets/140107687/cc922f54-860b-45da-96ed-8a52a4de528f)

**Comment by Achim242** [comment]
> i need bugreport from a whole day normal usage of android13 from 100 to 0:

Does it necessarily have to be from 100 to 0, or is it also possible to go from 90 to 10, for example?

**Comment by GreenwoodLMGU** [comment]
![Screenshot_20240424-163146_Einstellungen](https://github.com/HelloVolla/volla-os-beta-test/assets/146098739/9c0b34ee-8c7d-4f98-bdaf-91ea2920d10d)
Mainly the phone was just idle in this time. Some messaging and mail checks only.


For me battery performance has improved by doing two things:
a) charge to 100% (usually I only ever charge up to 85%)
b) change from "Trebuchet" to the default Volla launcher and back

Still, the drain is higher than it used to be.
Bug-report with a rundown from 100% to 2% follows.

**Comment by GreenwoodLMGU** [comment]
[bugreport-mimameid-TQ3A.230901.001-2024-04-24-16-29-08.zip](https://github.com/HelloVolla/volla-os-beta-test/files/15095971/bugreport-mimameid-TQ3A.230901.001-2024-04-24-16-29-08.zip)

**Comment by Termalator** [comment]
Sorry i had no time to reset my phone but curiously science last week the battery holds about a week again . I made no changes to the phone and no updates it just started to work again.  There is an update pending but i will not do that because it works now :).

**Comment by wurzer** [comment]
I have tested Volla OS 12 and Volla PS 13 on the same (not similar) device. I can't conclude a significant different battery drain.

![Screenshot_20240507-225046_Einstellungen](https://github.com/HelloVolla/volla-os-beta-test/assets/7789612/f7ada39a-2de2-426d-934f-537d81780617)
![Screenshot_20240510-215035_Einstellungen](https://github.com/HelloVolla/volla-os-beta-test/assets/7789612/8827271c-d31c-447a-b8d2-b0686d720a96)

**Comment by Termalator** [comment]
As already mentioned, the device worked normally after about two weeks. It was like there was some service running to complete some task and it completed it after two weeks. Very curious.

**Comment by wurzer** [comment]
@Termalator Maybe the backup?

**Comment by Termalator** [comment]
Nope i don't have any Backup running :), but thank you for the effort.

**Comment by Termalator** [comment]
Unfortunately the problem still exists. I just hadn't used the WiFi in the last few weeks and didn't think that the problem was related to that, since before that it also occurred with the WiFi turned off.

Now, after turning on the WiFi, I noticed that the runtime drops from over a week to under 3 days.

This was definitely not the case with “VollaOS 12”. I had over 7 days of battery life there with WiFi, Blutooth and location services turned on.

Blutooth seems to be working fine now, only WiFi is drawing an unusually high amount of power.
