### ISSUE TITLE
Volla Phone 22 - notification light does not work proper (VOS 13)

### ISSUE THREAD

**Issue by Affel24** [HelloVolla/volla-os-beta-test#156]
The notification light of my Volla Phone 22 (VOS13) stays always on, if I accept a call while screen is blocked.

If I disconnect from charger after the Phone got charged 100%, the problem seems to appear too.
I will have a look and check this again.

The notification light can be brought back in to a normal function by a reboot or by receiving an other notification.

**Comment by wurzer** [comment]
Just checked it. Can't be reproduced. 

1. Devide is in idle mode
2. Incoming call
3. Call is no accepted
4. Noficiation light is pulsating
5. Unlocking the device
6. Nofication light disappears
