### ISSUE TITLE
ClamV Hypatia system scan

### ISSUE THREAD

**Issue by LiviusMaximus** [HelloVolla/volla-os-beta-test#157]
![Screenshot_20240421-123848_Hypatia](https://github.com/HelloVolla/volla-os-beta-test/assets/128977279/0e76d951-df23-463c-83bf-29c1d093c125)

How to deactivate (erease ) infected system data without ROOT?
Redirect from Hypatia ...
https://www.virustotal.com/gui/file/ab0ce16eb885c4d202d45fa7a15236d4bc6035d3f2c80dba84c9d810d032efbb
Volla-os
12-20240228-STABLE-mimameid
Kernel build
4.19.191-g1a4eb972b195
#1 Wed Feb 28 18:51:07 UTC 2024
Volla 22

I know, the only protection again predator/Pegasus is to stay analog. Not to use any device that can decode/code binary

**Comment by LiviusMaximus** [comment]
I know, the only protection again predator/Pegasus is to stay analog. Not to use any device that can decode/code binary

**Comment by gbdomubpkm** [comment]
Hello.
See https://gitlab.com/divested-mobile/hypatia/-/issues/54 
@wurzer is sure it isn't a malware.
And as i had the same thing as you, it confirms.
Regard.

**Comment by wurzer** [comment]
Yes it's a false positive. It's build from source of a Lineage OS component
