### ISSUE TITLE
Flashlight Options not available

### ISSUE THREAD

**Issue by toby63** [HelloVolla/volla-os-beta-test#161]
When I search for the flashlight options in the system settings, they appear, but I can't click on them.

OS: Volla 12 (recent)
Volla Phone first generation I guess

**Comment by wurzer** [comment]
For which feature are you lookinr?

**Comment by toby63** [comment]
My original intention was to search for a setting to automatically turn-off the flashlight after some time.
I don't know whether such settings exist or not.

Then I came across an entry "Flashlight", but I could not click on it, so I reported this.

**Comment by toby63** [comment]
One addition:
I can find an option that I searched for in (german categorization):
`Einstellungen -> Tasten -> Taschenlampe automatisch ausschalten `
but this option is greyed out, it would be nice, if it could be activated.

**Comment by wurzer** [comment]
You need at enable the feature above: Activate the spotlight after long press.
