### ISSUE TITLE
Updater app keeps crashing

### ISSUE THREAD

**Issue by robbah** [HelloVolla/volla-os-beta-test#162]
Hello,

I have a issue where the updater app is crashing after pressing the Install button.

These actions i already tried:
- Restarted phone
- Wiped data of updater app
- Re-downloaded the update

Is this an issue with my phone (Volle Phone 22), or is it a bug in the update itself?

Regards,

**Comment by franco-bez** [comment]
several reports in the TG groups with similar problem.
Disabling "priorization" of the update seems to fix the problem.
In the Updater tap on the top-right menu ( three dots) and select settings. Switch off the priorization and try again, now the update should work.
Good luck

**Comment by wurzer** [comment]
There is no X22 in the market. Do you mean a Volla Phone 22 or Volla Phone X23? We can't reproduce the issue. You can do a sideload with an sd card.

**Comment by robbah** [comment]
> several reports in the TG groups with similar problem. Disabling "priorization" of the update seems to fix the problem. In the Updater tap on the top-right menu ( three dots) and select settings. Switch off the priorization and try again, now the update should work. Good luck

I noticed this already was disabled.

**Comment by robbah** [comment]
> There is no X22 in the market. Do you mean a Volla Phone 22 or Volla Phone X23? We can't reproduce the issue. You can do a sideload with an sd card.

I'm sorry, i mean Volla Phone 22 indeed.

**Comment by robbah** [comment]
@franco-bez @wurzer 
I noticed that the update eventually was installed while checking the fix from @franco-bez. So i would like to wait for a new update to check how the updater is responding to that one.

**Comment by wurzer** [comment]
Not reproducible
