### ISSUE TITLE
Volla OS 13 battery consumption high with WiFi on

### ISSUE THREAD

**Issue by Termalator** [HelloVolla/volla-os-beta-test#163]
I still have problems with the Battery runtime on Volla OS 13
see here: https://github.com/HelloVolla/volla-os-beta-test/issues/155#issuecomment-2119264911_

**Comment by wurzer** [comment]
It's probably related to the securoty mode, not wifi. 

To investigate in it we need some more details: 

- How long does a battery last with Wifi
- How long does a battery last without Wifi

The battery consumption fwfor Wifi depends very much on how much Wifi is used, i.e. how much data is transmitted and how strong or weak the signal is.

Otherwise, the consumption of the battery is determined by

- Mobile phone use
- telephone calls
- Video and music playback
- Tethering!
- Bames

**Comment by Termalator** [comment]
>     * How long does a battery last with Wifi
about 2-3 Days 
>     * How long does a battery last without Wifi
about 7-8 Days

> The battery consumption fwfor Wifi depends very much on how much Wifi is used, i.e. how much data is transmitted and how strong or weak the signal is.

The only usage is receiving mails (FairEmail but deactivated the receiving on standby so it so not running on standby) using MS-Teams and Nextcloud-Talk and using Linphone for SIP-phone

> Otherwise, the consumption of the battery is determined by
> 
>     * Mobile phone use
nearly none the phone is more then 95% of the time in stand by 
>     * telephone calls
not very intensive, maybe 2-3 calls a day
>     * Video and music playback
none 
>     * Tethering!
once a month
>     * Bames
i think you mean Games ;) but not one game installed

The only thing i use the Phone for, is to check the current time and sometimes use OSMAnd but that maybe every two weeks.

**Comment by wurzer** [comment]
Did you activate the security mode?

**Comment by Termalator** [comment]
Last time i checked it it was off but i never activated/used that and now i cannot find that :). Yesterday came a os update and i installed it. As i see, without WiFi nothing changed, i will test it with WiFi.

P.S. I am using Trebuchet as window management and if i remember it right the security mode is useless there.

**Comment by Termalator** [comment]
It seems that the last update fixed that issue, but i will test it for some days.

**Comment by Termalator** [comment]
I think it can be closed now, everything seems to be fine with the new system version
