### ISSUE TITLE
No preinstalled OsmAnd, please !

### ISSUE THREAD

**Issue by Thunichgud** [HelloVolla/volla-os-beta-test#164]
Mit Entsetzen musste ich feststellen, dass im VollaOs (Vers. 12.1) die eigentlich sehr gute App OsmAnd vorinstalliert ist. Eine dumme Idee von den Entwicklern.
Entgegen den Angaben an vielen Stellen handelt es sich dabei nicht um OsmAnd+, sondern um das kostenlose OsmAnd~. Ein wichtiger Unterschied.
Das vorinstallierte OsmAnd führt sich im VollaOS wie ein höchst eifersüchtiger Platzhirsch auf : Es lässt die Installation anderer Versionen von OsmAnd (Osmand+, OsmAnd+Live, OsmAndNB) nicht zu. Das Schlimmste: Da dieses OsmAnd~ mit dem ROM installiert wurde, lässt sich diese Version nicht wieder löschen, sondern lediglich deaktivieren. Jedoch auch das deaktivierte OsmAnd~ verhindert die Installation einer anderen OsmAnd-Version. Man kann lediglich ein Update der kostelosen Version vornehmen. Es ist auch absehbar, dass die vorinstallierte Version bald durch neuere Versionen veraltet. Dann liegt die veraltete Version weiterhin nutzlos im ROM und frist völlig unnötig Speicherplatz. Bei der Grösse der OsmAnd-App ist das keine Lapalie. 
OsmAnd ist für mich die wichtigste Anwendung im Handy. Dadurch ist mein Volla Phone 22 für mich vollkommen unbrauchbar und wertlos geworden.
Bitte in zukünftigen VollaOS-Versionen OsmAnd nicht weiter vorinstallieren. Bis dahin bitte einen Patch veröffentlichen, um das kostenlose OsmAnd~ vollständig aus dem ROM von VollaOS zu löschen.

**Comment by wurzer** [comment]
Wir verwenden die FOSS Version von OSMAnd. Über F-Droid kann diese regelmäßig aktualisiert werden. Andere Karten und Navigations Apps können problemlos parallel installiert werden.

**Comment by Thunichgud** [comment]
So läuft das bei Volla ? Bug-Report geschlossen, Problem gelöst ?
Kundenfreundlichkeit sieht anders aus.

Mein lieber Herr Wurzer,

über F-Droid kann nur die kostenlose Version mit eingeschränktem Funktionsumfang aktualisiert werden. Diese kostenlose Version verhindert jedoch die Installation der anderen kostenpflichtigen Versionen und der NightlyBuild-Version von OsmAnd. Das ist nicht akzeptabel !
Ist das Ihr Ernst ? Sie vertrösten auf die Möglichkeit der Installation anderer Karten- und Navigations-Apps ? Warum dürfen professionelle Versionen und NightlyBuilds von OsmAnd nicht im Volla Phone 22 installiert werden ? Ist das die neue Freiheit mit der Sie für das VollaOS werben ?
Ich werde also der grossen Gemeinde von OsmAnd+ -Nutzern vom Kauf dieser Geräte strikt abraten. 
Liebe Leser: Ich habe ab sofort ein Volla Phone 22 zu verkaufen, Kaum genutzt, Preis VB.
