### ISSUE TITLE
Dangerous bug during rooting

### ISSUE THREAD

**Issue by Thunichgud** [HelloVolla/volla-os-beta-test#165]
I rooted my VollaOS 12.1 using Magisk with no problems. 
After rooting I wanted to lock the bootloader again. But locking the bootloader after rooting with fastboot leads the device into an endless boot-loop. I solved this problem by not locking the bootloader again. This behavior after the rooting seems to be a bug. 
My device now works rooted but with still unlocked bootloader. At every booting of the system I get the message:
"Orange State. Your device has unlocked and can't be trusted ...". After that message the device boots normal and works without any problem.

**Comment by wurzer** [comment]
This won't be fixed. I strongly recommend not to root any Android device. It causes serious security leaks.
