### ISSUE TITLE
Again: Dangerous bug during rooting

### ISSUE THREAD

**Issue by Thunichgud** [HelloVolla/volla-os-beta-test#167]
I rooted my VollaOS 12.1 using Magisk with no problems.
After rooting I wanted to lock the bootloader again. But locking the bootloader after rooting with fastboot leads the device into an endless boot-loop. I solved this problem by not locking the bootloader again. This behavior after the rooting seems to be a bug.
My device now works rooted but with still unlocked bootloader. At every booting of the system I get the message:
"Orange State. Your device has unlocked and can't be trusted ...". After that message the device boots normal and works without any problem.

Wurzer commented:
This won't be fixed. I strongly recommend not to root any Android device. It causes serious security leaks.

Wurzer closed this issue

Thunichgud commented:
It seems to be the standard behavior at Volla to ignore bugs and problems.
It is not a bug, it is a feature ?
Rooting is not criminal and it is the reality at advanced android users. When you promote VollosOS with the slogan "Get your freedom again." you should give the users the real freedom, not only a virtual freedom.

**Comment by Thunichgud** [comment]
Give us our freedom back !!

**Comment by toby63** [comment]
To be fair, most companies will deny support for cases of rooting/hacking etc.
Still logically it is not right to do so.

**Comment by luka177** [comment]
You are excepted to lock bootloader only if you are running official signed VollaOS. In any other case bootloader should be unlocked. Its implemented that way on most modern android devices.

**Comment by wurzer** [comment]
@toby63 Yes, we always strongly recommend not to root any device, it opens serious security leaks. Volla Phones come with OEM lock and bootloader lock.
