### ISSUE TITLE
skip-songs-with-volume-buttons-android

### ISSUE THREAD

**Issue by Dricc123** [HelloVolla/volla-os-beta-test#17]
In any case I looked in Spotify and AntennaPod settings and found nothing. Can you forward this idea to the devs please?On Dec 6, 2020 00:20, "Dr. Jörg Wurzer" <info@volla.online> wrote:

Thanks for your inspiration. I think it’s an app feature. You may find this feature in serveral music apps

Am 05.12.2020 um 23:10 schrieb Cedric D <cedricoola@free.fr>:

Hello Team,
Could you set this up in Volla OS? It's an essential function that I got used to on my previous phone when listenning to music/podcasts: https://techwiser.com/skip-songs-with-volume-buttons-android/

Regards,
Cedric

**Comment by wurzer** [comment]
This is an app feature. I would like to encourage you to file this feature request to the open source project of our music app: 
https://github.com/MaxFour/Music-Player

**Comment by Dricc123** [comment]
In any case I looked in Spotify and AntennaPod settings and found nothing. Can you forward this idea to the devs please?

**Comment by wurzer** [comment]
Do you mean the volume button of the device or the headphone?
Have you successfully installed the skip button app?

**Comment by Dricc123** [comment]
Thanks for your answer. I mean the volume up and down button on the Volla phone. On my previous phone I could use these buttons for music playback without using the phone screen, so when the phone was in my pocket and I was reaching it with one hand for example.
I'm not aware of an app named Skip Button. On what store is it?

**Comment by wurzer** [comment]
I mean this app https://play.google.com/store/apps/details?id=com.flar2.volumeskip

The Volla phone has this capability, but it’s mainly an app feature to make use of control buttons. To avoid using the special permissions, I would prefer using the button of a headset. I have used it for iOS and Sailfish OS. This is much easier to implement by an app. This might already work with our music app. Otherwise I would like to encourage you to post that feature request on the Github page of our music app

**Comment by Dricc123** [comment]
Well, my Fairphone 2 has /e/ os installed and the up and down buttons skipping to the next track when screen off and I long-press the buttons. I use it for Spotify and AntennaPod mostly. I haven't setup anything in the apps themselves to make it work. It worked from scratch. Android version is Pie 9.
Why does Volla behave differently. Why do you insist on saying that it is an app feature. I don't see why I would buy new headphone that have up and down buttons, or have Volume Skip app running in the background to make it work. Btw, I tried the app and it works but it costs 4 euros and I used to have this function built-in on my Fairphone 2

**Comment by wurzer** [comment]
The app needs to respond to the buttons. It’s not the system, that manages the playback of music.

**Comment by Dricc123** [comment]
But the Spotify and AntennaPod apps are identical on both phones, so how could the function lay on the app side? Can you reopen this ticket to involve developers please

**Comment by wurzer** [comment]
I will discuss it with our developers. What do you think about controlling the music with the headset button? It’s in my point of view much more convenient?

**Comment by Dricc123** [comment]
For that I would have to buy a headset with this function. The handfree JBL headset that I got extra with the Volla phone (free of charge, nice surprise) for example, has one button that pauses the audio. I would need a headset with next and previous buttons. I'm not so keen on buying something to get back the same experience I had earlier with my older phone. Yes please discuss it internally and come back to me. Also if you can explain why it is an app feature in your opinion, what makes you think so, that would help us all.

**Comment by Dricc123** [comment]
new ticket opened: https://github.com/HelloVolla/volla-os-beta-test/issues/21

**Comment by wurzer** [comment]
Did you manage to install the workaround, that you linked in your initial email? This would activate the feasture you would like to have. 

I know the music track control through double or triple clicking the start and stop button of a headset. That is the common control of music on an iPhone for instance.
