### ISSUE TITLE
Option to merge/split contacts

### ISSUE THREAD

**Issue by anulin** [HelloVolla/volla-os-beta-test#170]
Might be good to add feature to be able to split/merge contacts. Currently the app automatically merges contacts if they have the same name and user has to manually remove contact number and create a new contact and type the number.

 This is especially painful when using messenger apps such as Telegram where users can set their names and then end up merged with random people in the contact book

**Comment by wurzer** [comment]
The contacts are usually merged by the phone number. How Telegram is assigning a Telegram contact to a contact of the system is a feature of Telegram. Is recommend to file this feature or enhancement to the FOSS telegram project.

**Comment by anulin** [comment]
well it does merge by name as well. 
Steps to reproduce:
   1)create contact 'delete' with phone number 123
   2)create contact 'delete' with phone number 321
   3)check your contact book. You will see that there is just one contact with name 'delete'. Moreover, you can only edit the 123 phone number and cannot see 321 in edit menu

Perhaps I should send this issue to fossify instead

**Comment by wurzer** [comment]
This feature request should be postes on the issue board of the Telegram project

**Comment by anulin** [comment]
the problem happens even if done without telegram, just using Contacts app or Dialer

**Comment by anulin** [comment]
https://github.com/FossifyOrg/Contacts/issues/37
