### ISSUE TITLE
Bluetooth devices, which are labelt as "keyboard"  are no longer found

### ISSUE THREAD

**Issue by tux4us** [HelloVolla/volla-os-beta-test#172]
VollaPhone 22
Android Version: 13
VollaOS Version: 13-20240529-Stable-mimameid

BT - Device: Selfie stick "Atumtek" ATSS002  (Suitable for Android 5.0 and higher)

The stick is not recognised via Bluetooth.

What have I tried?

- Reboot the phone
- Switch off and restart the phone
- Empty BT device list
- Deactivate and reactivate BT

Unfortunately, the cache and data of the BT app can no longer be cleared via the system settings since VollaOS 13 (greyed out).

Observation: the stick connects to VollaOS 12 devices and GoogleAndroid devices without any problems.

What is known?
According to user forums, this stick does not cause any problems with BT and no problems are known.

There is another user in the VollaTelegram group who is also unable to connect her SelfieStick via BT under VollaOS 13 with VollaPhone 22.

*******************************************

I suspect the problem could be bigger, because I have now noticed the following:

I've just been to the electronics store and tried to pair other BT selfie sticks there. No chance. They are not found.

On the seller's phone, these selfie sticks all appear as a "keyboard" symbol. I suddenly had a suspicion.

I drove home and tried to connect my BT keyboard "Logitech K480" (I've been using it for years without any problems, I've just never needed it under VollaOS13). Ooohhh...it is no longer found.

I'm afraid there is a problem with the recognition of BT keyboards under VollaOS 13.

******************************************************
I have now completely reset the network settings once.
However, only Bluetooth devices that are not labelled as keyboards are still recognised.
BT keyboards and selfie sticks (which are labelled as keyboards) are not recognised. Even a previously functioning selfie stick is no longer recognised.

**Comment by wurzer** [comment]
I can't reproduce this issue. I was able to connect a Bluetooth keyboard of Satechi with no issues onf a Volla Phone 22 with the recent public release.

**Comment by erdzas** [comment]
I’m trying to connect my amazfit balance watch (zepp OS) to my volla phone 22 (VollaOS) with the official app. I have the following message (pairing code) in loop and the connection is never established.
![Screenshot_20240704-210301_Trebuchet](https://github.com/HelloVolla/volla-os-beta-test/assets/79719717/361c3ba6-e286-4904-a741-6c1e3ff2af41)

Since I tried to connect the watch to an xperia X and everything is working fine.
I don’t know if it’s the same problem.

**Comment by wurzer** [comment]
Unfortunately, I don't have this smartwatch to reproduce this issue. 

1. Try resetting the bluetooth settings in system settings, system, reset options.
2. Check wether the watch requires an app for connection, that requires Google Play Services. If so, try activating and confirguring microG

**Comment by erdzas** [comment]
OK, I used two other apps to connect my watch (gadgetbridge and notify) and it works.
Thank you.
