### ISSUE TITLE
V22 Problems with Update and Dualboot

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/volla-os-beta-test#173]
there are reports in the telegram group that the latest release 13-20240629- mimameid can not be successfully installed when a dual boot SD card is present.
Update run through to the end,  but the phone does not reboot. after several tries the phone boots the old VOS Version.

When the SD card is removed, the update runs through and reboots into VOS  13-20240629- mimameid.

When the SD card gets reinstalled the phone fails to boot both, VOS and UT.
Only removing the SD card from the phone helps.

**Comment by franco-bez** [comment]
it seems that only V22 are affected.

**Comment by gbdomubpkm** [comment]
All right. I hadn't looked here and that probably explains why the latest update never showed up in the updater for my Volla 22. For the Volla under Android 12, everything went well and it works well.

**Comment by wurzer** [comment]
I'm using a Volla Phone 22 as my daily driver with two SIM cards an one MicroSD card. I could easily do the September update and reboot the device afterwards with no issues.
