### ISSUE TITLE
ATTACK on WiFi - No internet while connected to WiFi

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/volla-os-beta-test#175]
Seems there has been an attack on Volla OS 13.0. I have the 29 Jun 2024 version installed on my Volla Phone 22. It was NOT triggered by any update. I woke up this morning and turned on wifi, received notifications for emails, then BOOM - no WiFi.

What I tried:
- I have reset my internet, router etc.
- restarted my phone several times
- removed my battery
- removed my SIM
- reset/forget all wifi connections and reconnected

Seems to be an attack, possibly from Android 13 level. LTE still works and is my only way of connecting to internet. WiFi connects but shows no Internet.

WiFi still works on other devices, such as LineageOS, Windows, Ubuntu etc. Issue seems to be Volla OS specific - I can confirm this has happened to BOTH Volla Phone 22 that we own

Any help appreciated. Thanks

**Comment by wurzer** [comment]
It's just because of our network check server is offline. We'll restart this service asap.

**Comment by CubedApple** [comment]
> It's just because of our network check server is offline. We'll restart this service asap.

Thank you very much Dr. Jörg Wurzer. You are right. WiFi is working fine now. Much appreciated :)

**Comment by CubedApple** [comment]
I love Volla!

**Comment by CubedApple** [comment]
Hi @wurzer - looks like we have this issue again. Can you please restart the network check server? Thanks

**Comment by CubedApple** [comment]
this was fixed again 2 weeks ago
