### ISSUE TITLE
Notification Light Remains ON after Charging to 95%  and uplugging (VP22)

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/volla-os-beta-test#177]
Volla Phone 22
VollaOS 13.0 (29 Jun 2024 build)

I charge my phone via USB-C cable. Whenever I charge my phone upto 95% (I have set my limit in the settings to 95%, not sure if this is of significance), after unplugging when the battery reaches 95%, the notification light remains steadily lit and constantly ON.

The only way I've tried that works, to get rid of it, is to turn the phone off and back on again.

Steps:
1. Plug device via USB-C to charge
2. Wait until charge reaches maximum (or 95% in my case, with limit set to 95% in settings)
3. unplug usb-c cable (stop charging)
4. Notification Light Remains ON
5. To get rid of notification light, turn off phone and back on again

**Comment by wurzer** [comment]
I can't reproduce it. Please note that the notification light is also used for other use cases.
