### ISSUE TITLE
Audio (music) stutters when screen goes on/off while playing audio in background (VP22)

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/volla-os-beta-test#178]
Volla Phone 22
VollaOS 13.0 (29 Jun 2024)

When I play music (FLAC audio) using the built in 'Music Player' version 1.3.4. in the background, and the screen turns off or on, sometimes the audio stutters. I think the stutter is triggered by the screen ON/OFF activity.

**Comment by wurzer** [comment]
I can't reproduce it. Here is my test approach

1. Start playing an album in music app (m4a)
2. Listening with wired headset
3. Starting the launcher
4. Starting other apps
5. Switching of the screen

Looks like the device was to busy or the app has an issue wit flac. You can check CPU load is this happens.
