### ISSUE TITLE
Mobile internet on second SIM always disconnecting

### ISSUE THREAD

**Issue by p-heeb** [HelloVolla/volla-os-beta-test#179]
Samr issue as some month up to a year ago. The connection to Mobile is always disconnecting after like a minute. By enabling airplane mode and disable again it works again for some minutes. This issue happens to me since I use the second SIM for mobile starting like one week ago, never used it before.

**Comment by wurzer** [comment]
Just tested it and can't reproduce it on my Volla Phone 22 with the recent Volla OS version from June. Please reset the wireless settings in the system settings, system, reset options.
