### ISSUE TITLE
Firewall whitelisting broken

### ISSUE THREAD

**Issue by bonnepioche** [HelloVolla/volla-os-beta-test#180]
Hi there!

I have a Volla phone 22 running Volla OS 13-20240629-STABLE-mimameid.

A big part of why I purchased a Volla phone (and the Volla Tablet by the way), is to be able to give this phone to a child and be sure that he cannot access web sites I have not explicitely approved. This seems to be what the "firewall" should do.

* Said differently, **I want to forbid access to anysite, unless they have been _explicitly_ whitelisted (whatever application is used).**

* I have tried different combinaisons:
(i) Setting up a whitelist (in "Firewall setting") and activating the security mode: When I launch Fennec (for instance), Fennec can still access everything on the web. **I would have assumed that everything that is not in the white list would be unaccessible but this is not the case -> bug?**
(ii) Setting up a blacklist and activating the security mode: when I launch Fennec, Fennec can not access the blacklisted sites, which is the expected behaviour.

Unfortunalty, attempting to black lists top level domains like ".com" for instance, is not allowed by the security mode.

Since I cannot blacklist every single internet domain one by one, and that adding sites to a whitelist is not automatically blacklisting anything else, the question remains, how do I do?

Thanks for your input, I may be missing something,

Here is the link to the discussion on the volla forum, where this has been discussed (wich ended by the suggestion to open a ticket):
https://forum.volla.online/viewtopic.php?f=36&t=920

Best regards,

Patrick

**Comment by wurzer** [comment]
I just tested the feature. This issue can't be reproduced. 

Please make sure, that the securoty mode settings are stored poperly and the securot ymode is activated. If in doubt, you can reset the app data of the security mode

It's correct, that the securoty mode doesn't support whildcards yet. Thanks for the inspiration. We'll take it up for ourdevelopment.

**Comment by bonnepioche** [comment]
Dear Dr Wurzer,

Thanks for looking into the issue. I however do confirm the behaviour that I have described above.

Maybe there is something that I am doing wrong, or the firewall is not working as I am expecting.

Would you have a userguide for firewall proper usage?

Many thanks in advance,

Patrick
