### ISSUE TITLE
Volla X23 light 

### ISSUE THREAD

**Issue by anulin** [HelloVolla/volla-os-beta-test#181]
Might be good to add option to turn on the Spotlight ring without turning on the flashlight and/or make the torch brightness adjustable

**Comment by wurzer** [comment]
Both LEDs are already controlled seperately. You find settings for the spotlight ring in the system settings.

**Comment by anulin** [comment]
there are only settings for various animations and battery status. No setting to just turn it on. Also no setting for flashlight brightness adjustment
