### ISSUE TITLE
Volla22 after July update battery icons not visible on lock screen anymore

### ISSUE THREAD

**Issue by Danfro** [HelloVolla/volla-os-beta-test#182]
Volla22, VOS 13 stable

I updated the phone from VOS May version to July version (31.07.2024) on the weekend. After this update the battery icons are not visible on the lockscreen anymore.

The pure text like "73%" is shown, but neither the circle nor the battery icon are visible anymore.

Text, visible in both places:

![photo_3_2024-08-05_23-49-04](https://github.com/user-attachments/assets/fc0185e0-8eef-4d67-9ee0-9e38e5fcbb22)

![photo_4_2024-08-05_23-49-04](https://github.com/user-attachments/assets/2cdc11b9-ced7-4d9d-bbc1-f990b9170c61)

Battery and circle, not visible on lock screen:

![photo_1_2024-08-05_23-49-04](https://github.com/user-attachments/assets/ad6d1e5e-f71a-4f27-b665-56dd4ff574cf)

![photo_2_2024-08-05_23-49-04](https://github.com/user-attachments/assets/ecbf9409-02f3-485f-a01f-70ee8b28523f)

![photo_6_2024-08-05_23-49-04](https://github.com/user-attachments/assets/f242f87e-5801-4462-ab61-5944b4499185)

![photo_5_2024-08-05_23-49-04](https://github.com/user-attachments/assets/0171d259-a482-46ec-b0ee-036aef85089c)

**Comment by Danfro** [comment]
This has been confirmed by some other users in Telegram group. But also others don't have this issue. Some managed to solve it by changing text and/or icon size. This did not help here.

**Comment by tux4us** [comment]
I can confirm the error.
VollaOS13 (July update) on VollaPhone 22.
Regardless of the set display and font size, the battery symbol is no longer displayed on the lock screen. The text with the battery charge level is displayed.

**Comment by Achim242** [comment]
I can also confirm this here. 
Neither the battery symbol (upright) nor the circle are displayed. Only the pure text (xy%) appears as the display format. 

13-20240731-STABLE-vidofnir

**Comment by franco-bez** [comment]
confirmation also 13-20240731-STABLE-vidofnir

**Comment by gbdomubpkm** [comment]
Confirmed. I didn't find a workaround.

**Comment by Achim242** [comment]
> Confirmed. I didn't find a workaround.

A short workaround:
Minimize the font size, the circle with the percentage appears again. 
After a restart it is unfortunately gone again and you have to run the workaround again.

**Comment by Achim242** [comment]
I have the solution to the puzzle. 
If you leave the font size at "small", the battery symbol remains even after a restart.

**Comment by wurzer** [comment]
Will be fixed next release.

**Comment by franco-bez** [comment]
fixed in 13-20240818-BETA-vidofnir
