### ISSUE TITLE
X23e screen keeps flashing when in call

### ISSUE THREAD

**Issue by lightcrater** [HelloVolla/volla-os-beta-test#184]
Whenever I am in a call, whatsapp or regular the screen keeps turning off and on at random, the phone doesn't lock but I cannot make any inputs so i don't know if turning on caffeine would fix this issue

**Comment by wurzer** [comment]
I can't repriduce this issue: 

I startet a call to a Volla Phone X23, accepted the call and the screen was stable. i tested to switch of the screen with the power button and reactivated the screen with the fingerprint sensor with no issue. 

You are welcome to post stepts to reporoduce this issue.
