### ISSUE TITLE
Accepting customer payments via the Sumup app using ‘tap-to-play’ via NFC not possible

### ISSUE THREAD

**Issue by tux4us** [HelloVolla/volla-os-beta-test#185]
VollaPhone 22
VollaOS 13 
Version  13-20240818-BETA-mimameid
microG - activated

Affected app - "SumUp" - App for payments used worldwide - [Link](https://play.google.com/store/apps/details?id=com.kaching.merchant)

Affected function -  tap to pay (Payment by debit card via NFC function)

When trying to use the tap-to-pay payment function with a correctly set up app, the process is cancelled with the message: 
`activate_terminal_other_device_error`

The identical procedure can be carried out on a Huawei P30pro without any problems.

According to https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android
the following device requirements must be met: 

-    Contains functioning NFC antenna and chipset
-    Isn’t rooted and device bootloader is locked and unchanged
-    Runs a current version of Android (Android 11 or above)
-    Uses Google Mobile Services and has the Google Play Store app installed
-    Has a hardware backed keystore
-    Supports generating key pairs using a variety of key algorithms, including RSA and AES from the Android keystore
-    A stable connection to the internet

I suspect that it is the point: Uses Google Mobile Services - or is it due to another cause?

![Screenshot_20240822-223850_SumUp](https://github.com/user-attachments/assets/6366f021-1cb1-4ab8-b0b3-d622dac0026e)

**Comment by wurzer** [comment]
Please ask the developer for assistance.

Some apps require Google Play Services. In this case you can activate and configure microG in system settings.

In addition some of these apps require, that the operating system fulfills Google SafetyNet "security level" or the subsequent Goolge Play Integrity "security level". Volla OS fulfulls security level 1. 

It's not possible to fullfill a higher "security level" if the operating system ist not certified ba Google, in other words: if it is not a Stock Android. 

However the SafetyNet or Google Play Integrity is not really related to any securoty.
