### ISSUE TITLE
Firewall  Documentation

### ISSUE THREAD

**Issue by bonnepioche** [HelloVolla/volla-os-beta-test#186]
Dear Dr Wurzer,

Thanks for looking into the issue #180. I however do confirm the behaviour that I have described in the bug #180.

Maybe there is something that I am doing wrong, or the firewall is not working as I am expecting.

Would you have a userguide for firewall proper usage?

Many thanks in advance,

Patrick

_Originally posted by @bonnepioche in https://github.com/HelloVolla/volla-os-beta-test/issues/180#issuecomment-2310917870_

**Comment by wurzer** [comment]
With the recent release we fixed an issue, that defined domains are not removed, if the user switches from black list to white list or vice versa. 

If you define domains for the black list or white list please use a simple syntax like `google.com` or `web.de`
