### ISSUE TITLE
Volla X23 camera resolution problem

### ISSUE THREAD

**Issue by anulin** [HelloVolla/volla-os-beta-test#187]
Hello! Looks like the camera is stuck at 8Mp. The picture quality does not increase with increasing resolution setting. The grains on photos are noticeably larger than pixels. Also when I compare images with my old 13Mp Lg G3 - Lg has higher resolution photos. I assume this is a program bug

**Comment by wurzer** [comment]
Please note, that the camera has three modes

1. Front cam
2. Rear cam with super wide angle (8 MP)
3. Rear cam with wide angle (48 MP)

**Comment by anulin** [comment]
I am using the rear 48MP camera
