### ISSUE TITLE
Security mode crashing

### ISSUE THREAD

**Issue by bonnepioche** [HelloVolla/volla-os-beta-test#188]
Dear all,

When trying to configure the "Security mode", it keeps on crashing (ie: it goes back to the previous screen and Android displays "Application keeps on crashing, what do you want to do?....".

Please find the screenshot showing the security mode configuration and the parts that surprise me highlighted:

- In non restricted apps, I have applications with the same icon than the "restricted applications" (for exemple: Aurora Store or MS Authenticator). If I try to put them in the restricted category by clicking on them, the application crashes.

How can I fix that?

Volla phone 22, Volla OS 13 (latest).

Many thanks,

Patrick
![Volla-Secumode](https://github.com/user-attachments/assets/8ad80f73-9554-4995-b620-1888bf1a7c70)

**Comment by wurzer** [comment]
You can either block an app or block internet access of an app
