### ISSUE TITLE
Can't open .apk file (Vivaldi browser) workaround is to download from Aurora store

### ISSUE THREAD

**Issue by Dricc123** [HelloVolla/volla-os-beta-test#19]
Dr. Jörg Wurzer:

Good news: I’m able to install the Vivaldi Browser from the Aurora Store sucessfully.

Kind regards

Dr. Jörg Wurzer

Am 02.12.2020 um 10:39 schrieb Cedric D <cedricoola@free.fr>:

https://vivaldi.com/download <https://vivaldi.com/download>/
Where it says 'download the apk file here'

Cedric

On Dec 2, 2020 10:21, "Dr. Jörg Wurzer" <info@volla.online> wrote:
Then it seems not to be a valid apk file. Can you send me a link?

Am 02.12.2020 um 10:14 schrieb Cedric D <cedricoola@free.fr <mailto:cedricoola@free.fr>>:

Here we go!
Now what should I open the apk file with, for it to install? See attached.
Thank you,
Cedric

On Dec 2, 2020 10:09, "Dr. Jörg Wurzer" <info@volla.online <mailto:info@volla.online>> wrote:
Hello, Yes you haven’t granted the permissions to the Browser to save files. These permissions are available in „Apps and Notification“ settings for the Browser.

Enjoy your day!

Am 02.12.2020 um 10:01 schrieb Cedric D <cedricoola@free.fr <mailto:cedricoola@free.fr>>:

Hello Jörg,
Thank you, I am sure this will help but for the moment it is the actual download that does not take place. See attached. Can you help?
Kind regards,
Cedric

On Dec 1, 2020 23:31, "Dr. Jörg Wurzer" <info@volla.online <mailto:info@volla.online>> wrote:
Hello Cedric,

Thanks for your question. Sure, you can install any downloaded APK, but you must grant the right to the browser to install apps. You find this permission setting in the system settings „Apps and Notifications“, „Extended“, „Special App …“ and „Install unknown apps“

Let me know, if this does not work for you.

Enjoy your day!

With kind regards

Dr. Jörg Wurzer

Your Email cedricoola@free.fr <mailto:cedricoola@free.fr>

Hello
I don't want to bother everyone in the Telegram group so i ask it here: can you help me download vivaldi browser apk. I'd like to install the app, but it says download failed without explanation.
Thanks and regards,
Cedric

![Screenshot_20201202-101302](https://user-images.githubusercontent.com/75565258/101278294-b8df0380-37ba-11eb-839f-18a0d502ec9c.png)

**Comment by wurzer** [comment]
After you have downloaded the .apk file you can open the File Manager and tap on the file in the download folder. You wll be asked to grant the permission to install apps from the File Manager

**Comment by Dricc123** [comment]
For people who are interested, Dec. 11, 2020 post on Vivaldi blog, about Vivaldi efforts to address users that don't use Google Play services: https://vivaldi.com/blog/app-store-alternatives-uptodown-vivaldi/
