### ISSUE TITLE
Possibility to compile Jolla OS on other devices (Snapdragon)

### ISSUE THREAD

**Issue by pachof** [HelloVolla/volla-os-beta-test#190]
Hello, I am interested in compiling for Redmi note 8 (Ginkgo), I want to know if it is compatible with Snapdragon vendor and kernel, and what version of Android it has, Sorry for the inconvenience

**Comment by wurzer** [comment]
Good morning. You would need the kernel and vendor part of the Redme note 8 to port Volla OS to this device like we share our kernel to enable developers to port other operating systems for Volla devices.
