### ISSUE TITLE
Volla Quintus - Multi Boot functionality not working for me

### ISSUE THREAD

**Issue by jlllopez** [HelloVolla/volla-os-beta-test#195]
Device: VollaPhone Quintus
OS: 14-20241021-STABLE-algiz
Volla Boot Manager Version: 0.3.0-m0

Description:

I want to install a dual boot setup on the internal memory with Ubuntu Touch on the Quintus.

I followed these steps:
- Update system
- Go to Volla Boot Manager
![Screenshot_20241127-095225_Trebuchet](https://github.com/user-attachments/assets/eb861641-5af2-4504-adf6-cd93aeacb763)
![Screenshot_20241127-095209_Trebuchet](https://github.com/user-attachments/assets/4e646896-364b-49b4-a5c2-067c4ba47bdc)
- Attempt 1:
  - Tried the `+` button
  - Message pops up `select free space . . .`
  - Press `ok`
  - Nothing happened
![Screenshot_20241127-095236_Trebuchet](https://github.com/user-attachments/assets/aa3fb929-3a6d-4d82-b56d-5cbddfaedba4)
![Screenshot_20241127-095246_Trebuchet](https://github.com/user-attachments/assets/c55dd10e-bb7e-48f2-b3e7-6152cabedf5b)
- Attempt 2:
  - Tried the top left menu
  - Settings is grayed out
![Screenshot_20241127-095251_Volla Boot Manager](https://github.com/user-attachments/assets/55ac784b-dd6d-4052-876b-2b9fe87b349d)
- Attempt 3:
  - Tried the install button
  - App crashes

I would like to know which steps should I take to install Ubuntu Touch alongside Volla OS. Maybe I am missing some steps, e.g. Allowing some permissions, etc.

Thanks for your time :)

**Comment by tux4us** [comment]
My knowledge of the enquiry:

The Volla Quintus does not have an SD card option.

Therefore, the multiboot manager must first be modified by the developer to be able to install and start another OS in the main memory.

I assume that we will receive this option on the Quintus in a future update of the VollaOS.

**Comment by jlllopez** [comment]
> My knowledge of the enquiry:
> 
> The Volla Quintus does not have an SD card option.
> 
> Therefore, the multiboot manager must first be modified by the developer to be able to install and start another OS in the main memory.
> 
> I assume that we will receive this option on the Quintus in a future update of the VollaOS.

Thanks! I will wait for the update then.

**Comment by tux4us** [comment]
However, please don't put my answer on the next update of the VollaOS. I know it's on the roadmap, but I have no knowledge of the progress.

**Comment by wurzer** [comment]
This feature is planned with an update: https://www.indiegogo.com/projects/volla-phone-quintus/x/22905832#/updates/4
