### ISSUE TITLE
Lack of Push notification breaks Microsoft Authenticator

### ISSUE THREAD

**Issue by bonnepioche** [HelloVolla/volla-os-beta-test#196]
Dear all,

I am the happy owner of a Volla phone 22 and a Volla phone Quintus (and waiting for the Volla Tablet).

Experience is very good, but I have 2 applications that are not working on the devices (all of them):
- MS Authenticator: my organization requires MS Authenticator to be able to log on enterprise network. When I setup MS Authenticator on my volla phones, I got an error message asking to check if "Push notifications" are activated.
- My banking application (from a very large bank) also has an issue with their 2FA setup.

I am aware that "Push notifications" are evil (https://volla.online/en/resources/documents/Press-Release---No-Surveillance-of-push-notifications.pdf) , but apparently without it, I cannot use MS Authenticator, and without it, I cannot work.

And yes, I am aware that MS allows third party 2FA applications usage, but my organization has disabled this option. So it is MS Authenticator or nothing.
Micro G is enabled.

I had no difficulties on my previous Samsung Galaxy.

how can I do? I do not mind toggling on/off a feature when I need to use MS Authenticator, but I need to find a solution.

Any ideas any one?

Thanks!

**Comment by brodymillington** [comment]
I used these steps to get push notifications working, go into Settings>System>MicroG Settings

Once in there enable Device Registration and then also Cloud Messaging. I also enabled SafetyNet but not overly sure if that's needed.

**Comment by bonnepioche** [comment]
Dear [dillymyers](https://github.com/dillymyers),

It works! Thanks a lot! No need in my case for SafetyNet.

Thanks again!
