### ISSUE TITLE
[Feature request] Power menu extension

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/volla-os-beta-test#2]
It would be helpful to be able to reboot directly into recovery via the power menu when developer settings are enabled (don't know if this is possible to implement)

**Comment by nift4** [comment]
This is available on LineageOS as reference

**Comment by SHA-NDY** [comment]
Magisk also provides these reboot options. For advanced users this should be sufficient I think...

**Comment by wurzer** [comment]
Solved in Volla OS 11.1. Enter "restart" in the system settings search field to find the setting for an extended reboot menu
