### ISSUE TITLE
Volla 22 and volla OS 14: light theme inactive in quick settings

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#200]
Hello
Update to Volla OS 14 performed on Volla 22.

I noticed that the light theme applies well everywhere EXCEPT in quick settings where the dark theme remains active when the light theme is activated.

Never noticed this before this update.

**Comment by wurzer** [comment]
Can't reproduce it on my device. Please reset your start app. Maybe the setting is not stored properly.

**Comment by gbdomubpkm** [comment]
> Please reset your start app

What do you mean by that ? How to do that ?

**Comment by gbdomubpkm** [comment]
Please, explain how to solve the issue, i can't find the way. Always here for me after reset quick settings or delete cache of all apps. What did you mean in 'reset your start app'?
Because i always get dark theme in quick settings as in the screenshot on my Volla 22 and i am in light theme !
Thanks in advance ! 

 
![thème sombre désactivé](https://github.com/user-attachments/assets/af34f874-4083-4aca-8394-6f83a33a1a47)

**Comment by gbdomubpkm** [comment]
Problem confirmed again for me with yesterday update on Volla 22.
