### ISSUE TITLE
Volla Phone X23: Camera shutter won't open properly

### ISSUE THREAD

**Issue by timothee-muller** [HelloVolla/volla-os-beta-test#202]
When launching the default camera app (com.mediatek.camera), the camera view seems pitch black but it's actually not. This is due to the shutter of the rear camera being stuck in an almost completely closed position. The solution to open it is to switch to the front/selfie camera, then switch back to the rear camera (see pictures below). 
<br><br>
<figure>
  <img 
    src="https://github.com/user-attachments/assets/06872295-0f46-4e6c-84a0-ce8bb684960a" 
    width="20%" height="20%">
  <br>
  <figcaption><i>A picture of a lit light-bulb taken right after opening the camera app.</i></figcaption>
</figure>
<br>
<figure>
  <img
    src="https://github.com/user-attachments/assets/a2726b74-f84b-418d-aeca-bc81422116fa" 
    width="20%" height="20%">
  <br>
  <figcaption><i>A picture of the lightbulb taken after switching to the front camera, then back again to the rear camera.</i></figcaption>
</figure>
<br><br><br>
Also, the flashlight only works when the shutter is closed. After the fix, it doesn’t and the button to set it even disappears.

<br><br>
<figure>
  <img
    src="https://github.com/user-attachments/assets/f76c7908-c60b-4970-ae5a-e3df5619bd39" 
    width="20%" height="20%">
  <br>
  <figcaption><i>Before the fix, the flashlight button is visible.</i></figcaption>
</figure>
<br>
<figure>
  <img
    src="https://github.com/user-attachments/assets/761158e9-5eae-443a-99cb-c3186590a8f4" 
    width="20%" height="20%">
  <br>
  <figcaption><i>After the fix, the flashlight button has disappeared.</i></figcaption>
</figure>
<br><br><br>
I think I've had this problem since the last update (Volla 13, November 4). And there's no way to get other apps working with the camera (<i>e.g.</i> Messenger, Instagram, code bar reader, …)

**Comment by wurzer** [comment]
Please note, that the camera app has three modes:

1. Front camera
2. Rear wide angle with high resolution
3. Rear suer wide angle with lower resolution

We changed the sequense of camera moders. After front cam you get the high resolution cam. 

For hardware issues, please send the camera to phone-serice.de/volla.

**Comment by timothee-muller** [comment]
> Please note, that the camera app has three modes:
> 
>     1. Front camera
> 
>     2. Rear wide angle with high resolution
> 
>     3. Rear suer wide angle with lower resolution
> 
> 
> We changed the sequense of camera moders. After front cam you get the high resolution cam.
> 
> For hardware issues, please send the camera to phone-serice.de/volla.  
  
<br>
Well I did try different modes, but to no avail. And while I did that, some options started disappearing in the parameters tab. Sounds more like a software issue than a hardware one, don't you think?
I neither let the phone fall down even once nor did it sustain any kind of shock, on the camera or anywhere else.

Thanks for the "help" I guess. Now I'll try to install your beta version of VollaOS 14. But I don't think it's gonna change anything. Then I might try to flash LineageOS to see if it works better with your hardware.
