### ISSUE TITLE
Volla OS 14  / Skype Compatability Issue

### ISSUE THREAD

**Issue by PilotiOne** [HelloVolla/volla-os-beta-test#203]
Since the upgrade to VOS 14 Skype will not launch. 
- Device model used : Volla 22 and Quintus
- Operating system version and last update : 14-20241124-STABLE-mimameid
- Other hardware and software components that are related to the problem
- If applicable, affected app including version number or source reference : com.android.dialer Version 23.0 
- What problem is occurring? Above script.
- Is another profile or shelter active? : No
- Is the Volla OS security mode active? : No

MS Teams works OK. 
MS Copilot also OK.

https://github.com/user-attachments/assets/9b880ce8-020e-4115-82e4-14e1af49c9d1

**Comment by wurzer** [comment]
I can confirm it. I suggest to contact the support of Skype. 

Looks like Skype needs Google Play Services and API 34.  But in this case, I would expect an error message after starting the app without microG.

**Comment by PilotiOne** [comment]
Hello .....
This was my thought, [without the detail of the skill to be able to test] about skype /now/ needing google. 

I have raised a case with MS. Also there was a MicroG update within the last few days, maybe there will be a further update. I will workout how to / if it is possible to raise something with MicroG as well.

Danke.
MXD,

--
