### ISSUE TITLE
Display colored icons setting won't stay on

### ISSUE THREAD

**Issue by wmburke** [HelloVolla/volla-os-beta-test#205]
I'm only a few days in to my Volla Quintus experience and am overall loving it.

Whenever I turn on the Use colored app icons setting under Display and menus however, they only stay on until I open an app and then return to the launcher screen.

Any suggestions on how to debug or what to do to fix this? Feel free to tell me I'm asking in the wrong place, as well.

Best,
Wayne

**Comment by wurzer** [comment]
Please reset the app by removing the app data.

**Comment by wmburke** [comment]
i must have done that somehow, although it was not intentional for the problem has resolved itself.

Thank you!
