### ISSUE TITLE
Enable Lineage feature: System->Buttons-> skip track on long-press of volume keys

### ISSUE THREAD

**Issue by Dricc123** [HelloVolla/volla-os-beta-test#21]
Please re-enable it. It's built-in in AOSP. I don't know why you removed it.
These are screenshots from /e/os (E.Foundation)

![Screenshot_20201209-205604_Settings](https://user-images.githubusercontent.com/75565258/101681049-de416b00-3a61-11eb-874e-ff12acf39fa1.png)
![Screenshot_20201209-205519_LineageOS_Settings](https://user-images.githubusercontent.com/75565258/101681050-deda0180-3a61-11eb-8739-87ea58d8dd7b.png)

**Comment by wurzer** [comment]
It’s not an AOSP 9 feature.

**Comment by Dricc123** [comment]
OK, maybe not, but most custom ROMs have this menu feature, look it up.

**Comment by Dricc123** [comment]
I see that these Button control option in the settings are actually something of Lineage OS.
Therefore, the ROMs that are forked from Lineage have it.
https://www.howtogeek.com/192602/8-REASONS-TO-INSTALL-CYANOGENMOD-ON-YOUR-ANDROID-DEVICE/

**Comment by wurzer** [comment]
Volla OS is not a fork of Lineage OS

**Comment by wurzer** [comment]
With Volla Os 12 button funktions can be configured
