### ISSUE TITLE
[question/feature request] Wake up screen in case of notification

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#23]
Is there under android 9 with the Volla a mechanism to wake up the screen in case of email notification for example? If not, I think it is essential, especially since the Volla has no notification LED.
I couldn't find any compatible non-intrusive android wake up screen app. Is there?

**Comment by gbdomubpkm** [comment]
What about this ?

**Comment by wurzer** [comment]
Thanks for the inspiration. I'll check this

**Comment by gbdomubpkm** [comment]
Can you please check?
Does 'wake screen when notification is received' exist on Volla based on Android 10 ? This option exists on Android 11. I saw this on the smartphone of a colleague at work.
Thanks

**Comment by wurzer** [comment]
The API of the system is in place. Apps can use it. 
https://exceptionshub.com/android-how-to-turn-screen-on-and-off-programmatically.html

You can have a look at some Apps, that enable a wakeup screen.
https://duckduckgo.com/?q=android+Wake+up+screen+notifications&t=osx&ia=web

**Comment by gbdomubpkm** [comment]
I will test SimpleEmail (Distopico) with the OTA-10 update.

**Comment by wurzer** [comment]
Fine. Let us know your experience.

**Comment by gbdomubpkm** [comment]
FairEmail, sure !
