### ISSUE TITLE
Issue after using installer

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#25]
After flashing Volla OS, there was first UT  OTA-15  on the smartphone, i get this issue after each reboot of the smartphone and when the SIM is unlocked : 
![image20210130_043821412](https://user-images.githubusercontent.com/50362604/106356242-87883d00-62fe-11eb-842e-2a0b351e8804.jpg)

Cellular data  are OK, and internet work.
What does this issue mean?

**Comment by saidinesh5** [comment]
This is a known issue, whose fix will be coming in the upcoming update. One of the preinstalled apps - SimpleGallery - doesn't have enough permissions.

**Comment by gbdomubpkm** [comment]
Good to know. Thanks for the info.
