### ISSUE TITLE
Shortcut Maker

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#26]
As far as I know, there is no shortcut maker in Volla OS and i don't see non-intrusive compatible app in stores.
The non-intrusive Shortcut Maker app on Aurora Store seemed fine, but it is incompatible with the Volla launcher : can't run.

![SHORTCUT MAKER](https://user-images.githubusercontent.com/50362604/107118433-443f4880-6881-11eb-92cc-aaee86ee106f.jpg)

**Comment by gbdomubpkm** [comment]
I've seen that Shortcut Maker works now very  well with the very good discreet launcher https://f-droid.org/en/packages/com.vincent_falzon.discreetlauncher/ which works well with the Volla. I close the feature request.

**Comment by gbdomubpkm** [comment]
@wurzer please read https://github.com/falzonv/discreet-launcher/issues/114 and more specifically
the end of the issue : maybe you (and Volla team) will find  some usefull info in it.

**Comment by wurzer** [comment]
Thanks for your suggestion. I think it's a feature request, that matches our plans with the red dot menu. With the nightly release 1.5.x we have already introduced the definition of own shortcuts for installed apps. 

However, futher ideas to improve or flexibilize the definition of shortcuts is welcome. Any help and contribution to the launcher project is welcome.
