### ISSUE TITLE
Change NTP Server away from time.android.com

### ISSUE THREAD

**Issue by ymer66** [HelloVolla/volla-os-beta-test#27]
While NTP is not really critical for privacy, I strongly recommend to change away from time.android.com in the loaded image to pool.ntp.org (which seems to be called sometimes). I changed mine to our own Meinberg NTP Server and it work perfect.

Command uses: adb shell settings put global ntp_server pool.ntp.org

Thanks, Rémy

**Comment by Idcrafter** [comment]
A toggle or textfeld to choose the desired ntp would be better. (It would also be great to route all traffic to a vpn if one is in use and it would need to be patched in because google doesn't seee this as a problem)

**Comment by wurzer** [comment]
Done
