### ISSUE TITLE
Springboard does not work when rights are not granted to "Gallery" app

### ISSUE THREAD

**Issue by ymer66** [HelloVolla/volla-os-beta-test#28]
With error on pictue at boot or while accessing the Gallery app, Springboard is unable to place calls. Adding rights to Gallery app remove error at boot time and while accessing Gallery app. With this changed, placing calls from Springboard does work.
Rights set/granted to Springboard might be incorrect.

![Screenshot_20210321-182406](https://user-images.githubusercontent.com/69969283/111915604-6bd82200-8a77-11eb-98fb-6d2f19beda66.png)

**Comment by wurzer** [comment]
Please go to the System settings, 
open "Apps and Notifications", 
select the settings for the Volla App,
select permissions
deselect (if selected) and select the permission for the storage

**Comment by ymer66** [comment]
Well that is not my point! I needed to grant the right via the "Gallery" app to remove this error!

**Comment by ymer66** [comment]
Duplicated issue https://github.com/HelloVolla/volla-os-beta-test/issues/25

Please do not close issues that are not resolved!

**Comment by wurzer** [comment]
It's not an issue, You can solve it by setting the storage permission of the Gallery app. We are shipping Volla OS is very strict permission setting. But we learned, that some users have a problem with these strict presets. Therefore we will change these strict presets to basic permission presets with the next major update.
