### ISSUE TITLE
Import of calendar and gallery settings not possible

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/volla-os-beta-test#3]
When trying to import calendar or gallery settings from simple calendar or simple gallery (which I also used before) the respective app crashes. My exported settings originate from Android 10 but when exporting inside the app on Volla Phone it also crashes.

I'm not familiar with grabbing logs so I gave it a try. Please tell me which logs you need and how/when to take them.
[2020-07-06_19.05.zip](https://github.com/HelloVolla/volla-os-beta-test/files/4880297/2020-07-06_19.05.zip)

**Comment by wurzer** [comment]
I can't reproduce it. Could you try the following? Go to the settings / apps / calendar and enable access to the storage. If it is already activated, try to de- and re-activate this permission.

**Comment by SHA-NDY** [comment]
The permissions weren't set correctly. That solved the problem.
