### ISSUE TITLE
Springboard don't show option for creating new e-mail

### ISSUE THREAD

**Issue by 0xOGeek** [HelloVolla/volla-os-beta-test#32]
If i type @contactname in the Springboard. it just show up the option to make a call.
It does not show up the possibility to send an e-mail, also when the contact has an address assigned.
Hint: I uninstalled the default e-mail app and use FairEmail, if that makes a difference.

**Comment by 0xOGeek** [comment]
Btw. funfact: I gave the phone to 3 people. The first thing each of them tried is to type "mail" in the Springboard. :)

**Comment by wurzer** [comment]
This is the expected behavior. If the user doesn't enters a text, there is no message to send.
