### ISSUE TITLE
Not able to send SMS via Springboard -> "Contact has no mobile number"

### ISSUE THREAD

**Issue by ghost** [HelloVolla/volla-os-beta-test#33]
Type @contactname word1 word2. (Found out email works that way too, thx)
Click on "Send SMS" (translated).
You will get the message that your contact has no mobile number.
I'm able to call the contact via Springboard, so number is present also appears correct in the "mobile" field of the contact.

**Comment by wurzer** [comment]
I see, what you mean, the launcher includes the rule, that is can derive the intention to write an email, if the user enters more than two words. 

We will investigate in the second issue. As a workaround you can force the launcher to stop in the system settings. Then the contacts are reloaded. Usually that fixes the problem.

**Comment by wurzer** [comment]
Should be solved. Please recheck.
