### ISSUE TITLE
Changing Android system language should affect the Volla App too

### ISSUE THREAD

**Issue by 0xOGeek** [HelloVolla/volla-os-beta-test#37]
I tried to swap to english to get rid of the need to translate everything for reports.
But nothing happens.
So i rebooted the phone to give it a try, but the only thing happens is, that i can't scroll to the right side anymore to see my conversations.
When i open once my conversations with help of the red dot (love it), i can scroll again to the right side and see my stuff.

**Comment by wurzer** [comment]
I does, but not live. You need to restart the app

**Comment by 0xOGeek** [comment]
Shouldn't that then happens when i reboot my phone?
Ok, let me try to be more clear: I go in settings/system/language&input/languages
There i have 2 entrys: English (Germany) and Deutsch (Deutschland).
When i have the entry "English (German)" on top, the Android system language seems to swap to english everywhere.
Then i reboot my phone.
The Volla App is still running on german language and does not change.

**Comment by 0xOGeek** [comment]
Okay, found a way now.
If you delete (in my case) the second language (DE) in the android language settings, reboot your phone, it's done:
Volla App in english. :)

**Comment by wurzer** [comment]
Did you check the priority of the languages?

**Comment by 0xOGeek** [comment]
So the Volla App is not able to deal with two languages, where english had the priority.

Expected behavior? Fine.

**Comment by wurzer** [comment]
No, what I mean is, that the first language in the list is taken. This is the expected behavior of Android. If an App doesn't support the first language, it would talke the second one. Let's assume you have defined the languages Chinese, Japanese and English. The first two languages are not supported by the Volla App, yet. So it would take the Enhlish language.

**Comment by 0xOGeek** [comment]
So as i wrote i had "English (Germany)" and "Deutsch (Deutschland)" in the list, in this priority.
So an App should take "English (German)", right?
Is "English (German)" not supported by the Volla App yet, do i got it now? :)

**Comment by wurzer** [comment]
I think the language code is something like EN_de, that is not supported.

**Comment by 0xOGeek** [comment]
Aaaaahhh. Thanks. :)
