### ISSUE TITLE
Camera app lacks settings

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/volla-os-beta-test#4]
Fdroid shows for "Open Camera" an installed version so I assume the camera app on Volla OS is "open camera".

In the settings one can't manage many things, shutter sound and storage location etc. is missing. Only settings for the current shooting mode are visible.

**Comment by wurzer** [comment]
Open camera won't be the recommended camera app and will be removed for the release. We recommend the Mediatek app, that you can start with the shortcut menu.

**Comment by SHA-NDY** [comment]
In the beginning I thought it was OpenCamera what I was using but it was Mediatek camera app. The settings issue applies to Mediatek camera.
