### ISSUE TITLE
Phone call - make it possible to return to and end your call an easy way (usabillity)

### ISSUE THREAD

**Issue by ghost** [HelloVolla/volla-os-beta-test#41]
Hello again,
would be nice to be able to return to your "call screen" in an easy way to handle the call.
Atm. you need to use the "Taskmanager Overview" (all your running apps there as little pictures idk. the name for it).
Nowhere else i find something to return to a call.
Have a nice week. :)

**Comment by wurzer** [comment]
Sorry, I don't know, what you mean

**Comment by 0xOGeek** [comment]
Ok just tested it again, it works actually.
I had the issue that when i like to end a call, the "telephone screen" disappeared.
Also, but not 100% sure, i had at first the lock screen in front of me.
So i unlocked the phone and i was on the Springboard again but the call was still running.
From my old Android phone i know there was the possibility to drag from top to bottom to see the "running phone call", tap on it, and so i was on the phone screen again to end the call.
 Make this more sense to you? :)

**Comment by 0xOGeek** [comment]
Just had a longer call which i tried to end a minute ago. The phone definitely locks the screen while you are still in your call.

**Comment by wurzer** [comment]
This is a different use case than the initial post, isn't it? 

You expect the following: You are calling with a headset an you want to check some information while you are calling, but the phone app is blocking any further interaction?

**Comment by 0xOGeek** [comment]
Ich telefoniere und möchte dann den Anruf beenden.
Ich schaue auf's Handy und stelle fest das es im Lockscreen steht und ich mich erst anmelden muss.
Mache ich das, passiert es dass ich nur das Springboard sehe und ich muss mir die App mit dem Call wieder nach vorn blättern (evt. klappt das auch mit dem roten Punkt und "show dialer" k.A.),
damit ich den Anruf beenden kann. No headset involved.

**Comment by wurzer** [comment]
I have problems to reproduce it. I have checked the following:

1. Call from another device
2. Phone app pops up
3. I take the call
3. I wait until the screen is dark
4. I activate the screen an can see the phone app
5. I switch off the screen with the power button
6. I activate the screen with the power button
7. I can see the phone app
8. Hang up
9. Call to another device
10. I wait until the screen is dark
4. I activate the screen an can see the phone app
5. I switch off the screen with the power button
6. I activate the screen with the power button
7. I can see the phone app
8. Hang up

I checked this scenario with and without a cable headset. could you specify your scenario?

**Comment by wurzer** [comment]
Can you re-check with the recent Volla OS 11.1?

**Comment by wurzer** [comment]
You have also now a setting in the simple phone app to show phone calls always with the full screen view.
