### ISSUE TITLE
Adjusting the brightness of the screen

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#42]
Under the android 9  base (maybe it will be better under the  android 10 base), I am not totally satisfied with the progressiveness and the intensities obtained concerning the brightness of the screen :
To summarize:
- the minimum light seems to me too high (screen not dark enough) ;
- the maximum of light too low (screen not bright enough).
- it is necessary to position the luminosity slider at least 80% on the bar to have a correct lighting.

What do you think ?

**Comment by wurzer** [comment]
The maximum screen brightness is related to the hardware. We can't modify it with a software update.

**Comment by gbdomubpkm** [comment]
Did you test on the Androïd 10 base ?
If yes, is the behavior of the brightness management the same in progressiveness and intensity?
If the behavior is the same, does it mean that no improvement at any level can be made?

**Comment by wurzer** [comment]
Regarding the darkness. I can't see any difference between the black background and the black hardware frame of the screen. Regarding the brightness, it is a hardware specification. For my daily use I anyway switched of the automatic brightness control. Outside I select full brightness and the light mode for the Volla launcher. Night Light is switched off. You can also improve contract with accessibility settings.

**Comment by gbdomubpkm** [comment]
Apart from these common sense solutions, I haven't found any apk to force the screen brightness. Should I leave this request open?

**Comment by wurzer** [comment]
Oh, I wasn't aware of that open issue. I allways use a forced screen brightness. You just need to switch of automatic brightness cotnrol ins the system setting for the screen.

**Comment by gbdomubpkm** [comment]
I wish the brightness could have been higher than the maximum threshold, which is not always sufficient in my opinion. A brightness booster. But it doen't exist i think.
Therefore, I close this issue that seems insolvent.

**Comment by wurzer** [comment]
We tried to modify the kernel to increase the brightness. Unfortunately it is hardware limitation. The screen of the Volla Phone X  ist much brighter, but it is anyway made for outdoor.

**Comment by wurzer** [comment]
I recommend to use the light mode outside. We are currently working on a better contrast of the system font to increase the readability.

**Comment by gbdomubpkm** [comment]
> hardware limitations

What do you mean by that ?  because...

.... having said that, I notice, and I'm sure you do too, that the screen brightness can be more powerful on the UT Volla than on the Volla OS Volla :  it's the same Volla with the same 'hardware specifications'...

**Comment by gbdomubpkm** [comment]
Are there any improvements to see/test with the upcoming update regarding this problem ?

**Comment by wurzer** [comment]
We have to take into account the hardware specs according the maximum brightness. However we are soon publishing Volla OS 11.1 for the Volla Phone and Volla Phone X .

**Comment by gbdomubpkm** [comment]
I don't understand that the screen lighting management is much better with UT than Volla 0S on the Volla. It is a fact that with the same hardware basis of the Volla, 50% of the maximum light intensity with UT (slider setting)  corresponds to over 90% with Volla OS (slider setting).

**Comment by gbdomubpkm** [comment]
Is the screen of the Vollaphone22 under AOSP brighter and therefore more suitable for outdoor use?

**Comment by wurzer** [comment]
The brightness will be 430 cd/m2 (min.) / 450 cd/m2 (typ.). Regarding brightness I would recommend our Volla Phone X with 580cd/m².

**Comment by wurzer** [comment]
> I don't understand that the screen lighting management is much better with UT than Volla 0S on the Volla. It is a fact that with the same hardware basis of the Volla, 50% of the maximum light intensity with UT (slider setting) corresponds to over 90% with Volla OS (slider setting).

Thanks for that observation. I'll open a ticket to check it. However we should wait for VollaOS 11.1. It might be fixed.

**Comment by gbdomubpkm** [comment]
> However we should wait for VollaOS 11.1

Let us wait and see indeed.

**Comment by gbdomubpkm** [comment]
OTA-11 does not improve on this. However, I wonder about the fact that the VLC player software seems, by its own video playback setting, to provide an amplification of the brightness greater than that provided by that of Android.

**Comment by wurzer** [comment]
Thanks for your report. We will investigate in the behaviour
