### ISSUE TITLE
Volla launcher improvements

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#43]
- Adjustment of the degree of blurring of the transparent mode: personally, I would like to have a transparent mode not blurred.

- Provide a color mode for the app icons which would allow to keep the original colors of the app icons.

**Comment by wurzer** [comment]
Yes, we have setting for the degree of blurr filter on our agenda.

**Comment by gbdomubpkm** [comment]
Ok thanks for point one.
Is point two also being considered?

**Comment by wurzer** [comment]
I see, yes. I'll put it on our agenda. Thanks!

**Comment by gbdomubpkm** [comment]
Hello.
I saw that there is now an experimental mode for colored icons, Thanks for this,  but not all icons can be displayed colored (currently ?) For example, Aurora, F-Droïd, Files, 'Browser' icons can't be colored.
I think 'Browser' should be called with the real name : Fennec.

**Comment by wurzer** [comment]
That's true. Our designer has replaced icons of system apps by our own icon, that follows the minimalistic design language. However we can't prepare custom Volla icons only for a set of common apps. The desaturation was a compromise to align the design of apps with no custom icon. We will probably do both, extending the set of custom app icons as well as grouping apps to have a cleaner and constent design.

**Comment by gbdomubpkm** [comment]
@wurzer Thank you very much for the now adjustable background blur (v 1.5.10 volla launcher): it's a nice improvement. 👍

**Comment by wurzer** [comment]
You are welcome. Thanks for the motivation.
