### ISSUE TITLE
F-Droid and Volla Launcher updates

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#44]
It would be nice to specify on the F-Droid Launcher update page which points are improved of the launcher compared to the previous version. We don't see any info.
Thank you.

**Comment by gbdomubpkm** [comment]
Volla launcher v 1.8.1 update  brought  instability to Volla for me.

**Comment by wurzer** [comment]
Could you explain the issue?

**Comment by gbdomubpkm** [comment]
After installing this version, the integrated applications (gallery, file managers, contacts...) crashed one by one when opening by losing their color customization, which I can restore. I also had crashes when switching from Volla launcher to discrete launcher. It seems that by completely resetting the Volla launcher (cache and data), the system is stable again. But I'm doing and will do more tests and verifications in the evening.

**Comment by gbdomubpkm** [comment]
When I had my problems this morning, I also had a crash of the Volla launcher when I tried to add to the home screen the shortcut to https://devices.ubuntu-touch.io using the Fennec function. I haven't tried again since then for fear of not being able to easily restart the Volla launcher. Can you confirm this or not?

**Comment by wurzer** [comment]
I have added the mentioned page to the app grid and it works fine on my device. No crash. Did you shorten the title? 

You can remove the links at any time by deleting the store and cache of the Volla app, if something is going wrong. The intended way to remove links in an option in the context menü, that pops up if you long press the icon.

However I can conform, that the link is not shown properly in the overvieW unless I restart the launcher. It's surprising because I have fixed this particular behavior. I will re-check it.

**Comment by gbdomubpkm** [comment]
> deleting the store 

The store ? What do you mean ?

**Comment by wurzer** [comment]
The data store of the app

**Comment by gbdomubpkm** [comment]
Yes. I did that yesterday.

**Comment by gbdomubpkm** [comment]
Does the Volla launcher handle Widgets? Not the shortcuts but the widgets.

**Comment by wurzer** [comment]
Not yet, because the UI concept is different. However we will reflect your requirement. 
We think about an open APi for plugins to extend the skills of the smart textfield. 
The lock screen for sure supports widgets. And if you like you can change the default launcher to the 2nd pre-installed one.

**Comment by gbdomubpkm** [comment]
Thanks for your answer.
In fact, I was asking for this for a specific purpose: to get the widget to activate and cut the synchronization of FairEmail (as i don't want always use my client mail and a VPN together) in a non brutal way and I found the solution: by creating a shortcut with shortcut maker which switches directly to TREBUCHET which handles the widgets and the one I am interested in. But if the Volla launcher can manage widgets later, it will be good.

**Comment by gbdomubpkm** [comment]
Is it the more recent working TREBUCHET update on the Volla ?

**Comment by wurzer** [comment]
Thanks for your inspiration. I'll think about a widget page or maybe a position right on the springboard. 
The Trebuchet launcher is updated with the system updates. Do you miss a feature?

**Comment by gbdomubpkm** [comment]
> The Trebuchet launcher is updated with the system updates

Ok. So, it is the last update of TREBUCHET if i understand well

> Do you miss a feature?

I don't know exactly what you mean by that, but I don't think.

**Comment by wurzer** [comment]
I tried to understand the motivation behind your question. anyway, the updates come with the system update. The next reliease with the January security patch is in the final quality test and will come soon.

**Comment by gbdomubpkm** [comment]
No. No particular motivation. Only to know if TREBUCHET was up to date. Like the integrated music player by the way.

>  The next reliease with the January security patch is in the final quality test and will come soon.

Good !

**Comment by gbdomubpkm** [comment]
> It would be nice to specify on the F-Droid Launcher update page which points are improved of the launcher compared to the previous version. We don't see any info.
Thank you.

Reminder 😉

**Comment by wurzer** [comment]
You mean release notes. Sure. we should do that! Thanks for the reminder

**Comment by gbdomubpkm** [comment]
Unless I am mistaken, the latest version of the volla launcher does not work normally: more often, double tap to open apps, appearance of the red menu of an app with a single tap whereas not wanted ? do you know that ?

**Comment by wurzer** [comment]
I can't reproduce this issue. 

You may reset the launcher app in the system settings for the launcher or the launcher settings. You find the launcher settings if you swipe two times to the right. 

For the long press gesture you can set the duration in the operating aids settings.

**Comment by gbdomubpkm** [comment]
> For the long press gesture you can set the duration in the operating aids settings

I don't find to check if it solve my problem.
Can you give me the path please ?

Seems the issue i have is on the volla, not on the volla 22.

If you confirm that on the volla you have no problems with the volla launcher, can there also be the possibility that the launcher has installed incorrectly due to a temporary lack of network, for example? In this case, a next update will confirm it to me. Unless I can reinstall this version of the same level launcher.

It would be nice to have the option to simply reinstall the latest available version of the Volla launcher in in the event of a supposedly faulty installation.

**Comment by wurzer** [comment]
Sure

1. Open system settings
2. Accessibility
3. Touch & hold delay

I use a Volla Phone of the first generation as my daily driver. 

You can try to reset the launcher:

1. Swipe to times to the right
2. Tap on options to reset
3. Tap on reset start app

Let me know, if it helps. How many apps have installed? If there are many apps, I recommend the grouped grid. It would incease the perfomance.

**Comment by gbdomubpkm** [comment]
Thank you for your help. I have tried everything but it doesn't change anything. Always the same issues. Maybe an improper installation of this update ? I will see with new update of the Volla launcher.
I use currently https://f-droid.org/en/packages/com.vincent_falzon.discreetlauncher  . Works very well on the Volla.

**Comment by wurzer** [comment]
What is the concrete issue? Tapping on an app icon in the grid opens the context menu?  
Did you modify the delay in the system settings?  
Did you activate grouped apps, if you have installed many apps?

**Comment by gbdomubpkm** [comment]
Yes, I changed the delay by extending it.
Yes I have grouped the apps.
Yes I have reset everything several times.

There are several problems:
- the context menu can open too quickly when it is not desired.
- pressing an icon makes the app open on second tap (sometimes the first).
- it happens that when pressing an icon, the whole launcher jumps very briefly without the app icon opening.

**Comment by wurzer** [comment]
* The source code for the quick menu didn't change in the recent release.
* Did you increase the delay for a long touch in the system setting? How many apps have you installed?
* Are you sure, you have reset the launcher, by forcing quit and deleting app data? Which apps cannot be opened?

**Comment by gbdomubpkm** [comment]
The issues are independent of app icons.

Yes, I have a lot of icons (shortcuts or apps) more than 100  but they are closed as I go. And i haven't the problems with discreet launcher.

I can't guarantee that the issues are related to the latest version of the Volla launcher as it hasn't been my daily launcher for some time.

I will wait for the next releases of Volla OS and Volla launcher to see if the issue gets fixed.

**Comment by wurzer** [comment]
Are you using the grouped grids? If not, is the behavior different with grouped grids?  
I'm using only 28 apps and with activated security mode even less.

**Comment by gbdomubpkm** [comment]
I uninstalled several heavy apps and it didn't change anything. Surprised that's just my problem.I stop the investigation.

Edit : Last attempt last night by checking how the Volla launcher reacted by changing the wallpapers through the system parameters. This seemed to fix the problem at first but it didn't last. That being said, I don't really understand how the launcher reacts to changing wallpapers.

**Comment by gbdomubpkm** [comment]
How to make the orange heart-shaped 'Thank you' icon reappear in the launcher if the icon has been hidden for a while (THANK YOU settings option) ? It says to redownload THANK YOU, which is impossible since it is an integrated app that is always there!

**Comment by wurzer** [comment]
This app is hidden in the launcher, because it has the only function to support the color control of the launcher. If you choose another launcher, the app would appear.
