### ISSUE TITLE
Only upgrades, no downgrades of integrated apps

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#46]
Why can't integrated apps, such as for example  Fennec, be downgraded ? Only upward updates (upgrades) are accepted.. In case of a malfunctioning update (upgrade), it is impossible to go back ; or by personal choice of this or that version.

**Comment by wurzer** [comment]
It's a system rule of AOSP. It's usually even not possible to update system ups as long it's not done by a system update. We want to endure more frequent updates for the system updates, that our users benefit from fixes and improvement as soon as possible.

**Comment by gbdomubpkm** [comment]
Yes Android can not downgrade an apk unless you uninstall it completely and then reinstall the desired apk, or other workarounds not simple to not lose data. And here for AOSP, when it is a faulty apk integrated into the system, we are therefore obliged to wait for a next functional update of the apk...
