### ISSUE TITLE
Apps filter response is slower then it was.

### ISSUE THREAD

**Issue by 0xOGeek** [HelloVolla/volla-os-beta-test#48]
When i go on the Apps screen and clear the filter, it seem to be slower then it was at the beginning.
It takes a second to list the apps now, sadly i can't say after what update that behavior started.
Not a big deal but it don't feel that smooth anymore.

**Comment by wurzer** [comment]
1. Do you mean filter the apps with the textfield above the app grid in the Volla Launcher?
2. How many apps do you have installed?

**Comment by 0xOGeek** [comment]
1. Sure, how else to filter them?
2. 48 Icons on the App Screen (Or App grid as you call it) including preinstalled stuff and things like "settings".

Anyway, according to issue #49 you wrote "Thanks for this idea. We want to prepare a solution to tidy up the app grid to be aligned to the allover UX idea" so i will stop reporting for now on "App Screen Stuff" and wait for what will happen.

Issue can be closed.

**Comment by wurzer** [comment]
1. How many apps do you have installed?
2. Did you check the DuraSpeed settings, if you have many apps? You may deaktivate them or DuraSpeed
3. Did you check to restart the Volla launcher?

**Comment by 0xOGeek** [comment]
Deactivated DuraSpeed, rebooted the phone, no change.
We can stop here.
