### ISSUE TITLE
Apps screen improvement

### ISSUE THREAD

**Issue by 0xOGeek** [HelloVolla/volla-os-beta-test#49]
Would be nice to be able to click and hold an app icon for ~3 seconds, to pin it as a favorite on top of the app list (and vice versa).
The goal is to reach the favorite apps with one click and not to click in the search field first then typing  a name.

**Comment by wurzer** [comment]
Thanks for this idea. We want to prepare a solution to tidy up the app grid to be aligned to the allover UX idea
