### ISSUE TITLE
Back button always jumps to launcher

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/volla-os-beta-test#5]
Using the navigation button "back" inside apps in most cases jumps to the volla launcher. The app then has to be reaccessed via the recents menu.

**Comment by wurzer** [comment]
I can only reproduce it, if you haven't navigated inside an app and you are able to go back to the previous view. This is the expected behavior. Could you describe a use case to reproduce the issue?

**Comment by SHA-NDY** [comment]
> I can only reproduce it, if you haven't navigated inside an app and you are able to go back to the previous view. This is the expected behavior. Could you describe a use case to reproduce the issue?

This was opened many weeks ago and I can't remember well. I am now testing phh's Android 10 GSI and don't actually know when I will return to VollaOS.

**Comment by SHA-NDY** [comment]
True, this behaviour can't be reproduced now. Closing...
