### ISSUE TITLE
Android 10: opening and saving files may not be possible

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#50]
Hello.
Since the switch to Android 10, some apps that worked normally in Android 9, no longer work when it comes to using the functions related to the file manager: impossible to access files, save a file..

The identified apps:

Pdf Viewer Plus
https://f-droid.org/en/packages/com.gsnathan.pdfviewer 
Unable to select a file via the app

SimpleTexEditor
https://f-droid.org/en/packages/com.maxistar.textpad
Unable to select (or save) a file by the app : crash at the time of the operation

Editor
https://f-droid.org/en/packages/org.billthefarmer.editor
Wanting to use the 'storage' access tab crashes the app.

Simple Notes (your note manager)
https://f-droid.org/en/packages/com.simplemobiletools.notes.pro
Unable to open a file by the app : crash

No authorization settings have been changed since the switch from Android 9 to 10.

Can you confirm these problems? Thanks

**Comment by wurzer** [comment]
Please update to the recent Volla OS 10 release from August, 16th

**Comment by gbdomubpkm** [comment]
It's really a coincidence !!  first I opened this issue and a few hours later I checked if there was an update (not necessarily related to this issue).

But I confirm that everything seems to be fixed 🙂 by the August 16 update and is working normally again. Thanks to the developer(s). 👍
