### ISSUE TITLE
Problem to choose number from contact with multiple numbers incl. - with standard dialer App

### ISSUE THREAD

**Issue by ghost** [HelloVolla/volla-os-beta-test#51]
Imaging you have a contact with, lets say, a mobile and a "work" number included.
When i type in the name of the contact on the dailer pad, it just shows me the mobile number and i have no choice to choose.
When i change the standard phone app to then second option (looks like the good old "google dial pad"), then it shows me two options to choose the number from, so this way it works for me.

**Comment by wurzer** [comment]
Can you explain your use case? On the dialer pad, you can only enter numbers.

**Comment by 0xOGeek** [comment]
I'm talking about phonewords like you may notice when dialing "0800 VOLLAPHONE" which would result in "0800 8655274663",
or in this case it will show you the corresponding contact on top.

Remember a contact on your phone, go to the dialer pad, look at the letters under the numbers on the dialer pad (like 2 (a,b,c) 3 (d,e,f) and so on).
Then while focusing on them, try to type the name of your contact this way.
The contacts will get filtered on top, but if your contact has multiple numbers, you are lost cause you can just choose 1.

**Comment by wurzer** [comment]
Yes, the Dialer app takes the first phone number, that is listed in your contact. If you 

If you touch a contact longer, a menu changes at the top. Tap the icon with the magnifying glass and then dial the desired number. 

A more convenient way is the springboard. After an @ sign, enter letters to filter displayed names or select one directly. The Volla app will now show them a choice of whether you want to call the person mobile, at home or at work. 

Finally you can change the dialer in the system settings for apps and notifications, standard apps.

**Comment by 0xOGeek** [comment]
Okay, so i changed the std. dialer to the google variant.
Then i started to type on the Springboard @MycontactName... and choosed "Call mobile number".
Then the phone can't go on, and tells me that i have to set the other dialer app as standard, elseway dialing will not work from Springboard.
So changing the default dialer app seems not to be an option, when you like to use the springboard too.

I also found a little typo in the german translation.
If you click on the contact in the springboard it will show you "Alterntive Nummer anrufen" as second option. :)
But what i found strange is, that it shows me this second option also on contacts that does not even have a second number.

I think what stopped me from using the springboard for dialing is that i need to "click" at least 4 times before i can start typing the contact name itself. As i wrote in another comment, it would be nice to have the "@" directly accessible on the keyboard without the need to change to "the second page of the keyboard" and back again, before you can start typing the contact name.

**Comment by wurzer** [comment]
Please go to the system settings and select the AOSP (not Google) Dialer as a default phone app. 
If you then open the Dialer within the Volla pp, the AOSP dialer will be shown.

If you type an @ all Contacts should be shown and you can tap on a contact to dial it.

You have a third option for frequent contacts: You can call the contacts collection with the red-dot-menu and long press on any contact to trigger a call quickly.

I notice, that you are opening many tickets. I Invite you to contact our support to get help for using the Volla Phone as your daily driver. We can clarify your questions in phone or video conference.

**Comment by 0xOGeek** [comment]
:facepalm: 

Well, will stop spamming you, sorry for the wasted time.
Comments on the Matrix channel some time ago should even told me not get into this project to much.
Have a nice day.

**Comment by wurzer** [comment]
Bug reports, feature requests and enhancement suggestions are always welcome. That's the intention of this issue board. Thanks for your contribution. My comment was a service offering for you to solve the issues you have with your device.
