### ISSUE TITLE
VollaOS 10.0 - 15 August update does not appear

### ISSUE THREAD

**Issue by lhooge** [HelloVolla/volla-os-beta-test#52]
Hi, 

according to the Wiki there should be an update available since August.

But if I search for new updates it does not appear. 
Currently VollaOS 10.0 - July 26 is installed. Build number: QP1A.190711.020

Are there any problems with the update server? 

(Would be nice to have increased minor version numbers)

**Comment by wurzer** [comment]
Yes, this updates will be re-published after this weekend at the latest.
