### ISSUE TITLE
Add Aurora Services into Volla OS 10

### ISSUE THREAD

**Issue by pekrahulec** [HelloVolla/volla-os-beta-test#53]
Hello,

can you please add Aurora services into the Volla OS 10 on the Volla Phone?
Because of the lack of this, user has to manually tap "Install" whenever installing or updating apps from Aurora store. This is really inconvenient when user has many apps installed using Aurora.

**Comment by wurzer** [comment]
i remember, that there was a reason, not to do so. I'll check

**Comment by pekrahulec** [comment]
Would you please look into it, then?

Thank you very much.

**Comment by wurzer** [comment]
I put the evaluation on our agenda
