### ISSUE TITLE
[question] connection sharing /hotspot, maximum number of devices connected

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#58]
Maybe I have a memory lapse because I was convinced that the function existed but I can't find it...

I am looking for the place to set or check the maximum number of devices that can be connected to the Volla Hotspot.

Where is it if the function exists?
Thanks

**Comment by wurzer** [comment]
These additional settings are unfortunately not part of the Android open source project and therefore not from Volla OS

**Comment by gbdomubpkm** [comment]
Ok. Too bad, it would have been good for security. I must have had this mechanism with sailfish OS in one of my tests and got confused.

**Comment by wurzer** [comment]
It's not a hardware limitation. It's just a matter of settings user interface. With the Ubports installer you can switch to Sailfish OS.
