### ISSUE TITLE
User agent : block by default the use of the hardware name 'Volla Phone'

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#59]
Hello

I  had the (not necessarily good) surprise to see that the hardware name 'Volla Phone' appeared in the Vivaldi mobile browser user agent.

To me, this is a serious privacy flaw for a browser.

Vivaldi is most certainly aware of this issue, but they are moving at a snail's pace to fix the problem (if they really want..).

Is it possible, in a global way, i.e. at the level of the smartphone, to make it so that the model name (Volla Phone) cannot be used / appear in any user agent (of any browser).

![image20211106_115041203](https://user-images.githubusercontent.com/50362604/140607880-8ff8ce4b-79c2-4cb0-8055-a5af1c49544f.jpg)

To be taken as a feature request if feasible.

Best regards

**Comment by wurzer** [comment]
With the pre-installed browser for Volla OS, the device and vendor is unknown. What you see in the screenshot might be the device name, that you can change in the system setting.s You can call the device name Samsung Galaxy 10 for instance.

**Comment by gbdomubpkm** [comment]
No, you can't change that : you can try

**Comment by wurzer** [comment]
Please go to system settings, then the entry about the device and then tap on device name.

**Comment by gbdomubpkm** [comment]
Yes. I know that. I tried. But change the name has no effect on the user agent string : always shows Volla Phone for me. I think the user string shows the phone model (hardware), also called 'Volla Phone', not the name of the phone.

**Comment by wurzer** [comment]
I have checked several user agent tests. With Fennec I have a unknown device and vendor. I recommend to use our preinstalled browser with a high security level in the settings. Alternatively you can install plugins, that allow agent spoofing. By the way: Our recommended browser allows plugins for several security topics.

**Comment by gbdomubpkm** [comment]
I use alternately 4 browsers  : Fennec, Vivaldi, Brave and F-Droid Privacy Browser (Soren Stoutner)  : this last good browser is the more efficient to manage and change easily user agent string.
These four browsers are good,  but vivaldi is the worst about user agent string i think.

Not necessary to leave this request open.
Thanks
