### ISSUE TITLE
Updater does not update

### ISSUE THREAD

**Issue by tux4us** [HelloVolla/volla-os-beta-test#6]
The VollaOS updater does not update, even when refreshing. It brings: " The search for updates failed. Please check your internet connection. "
This error occurs when activated wifi and/or mobile data.
VollaOS 9.0 from July 01, 2020

**Comment by wurzer** [comment]
Thanks, this is a known issue of the update server.

**Comment by tux4us** [comment]
Okay, I guessed it in that direction. Thank you for the information.

**Comment by tux4us** [comment]
Updater works and seems to be fixed. Thanks.
