### ISSUE TITLE
no connection to wifi with hidden SSID

### ISSUE THREAD

**Issue by chrnit** [HelloVolla/volla-os-beta-test#60]
It is not possible to connect to a wifi that has its SSID hidden. The system always says that the network is not in range.

**Comment by wurzer** [comment]
Which release (date) do you use?

**Comment by chrnit** [comment]
Volla OS 10.1 of 4th Dezember 2021

**Comment by gbdomubpkm** [comment]
@chrnit You speak of the Volla phone X, isn't it ?

**Comment by chrnit** [comment]
> @chrnit You speak of the Volla phone X, isn't it ?

Yes

**Comment by wurzer** [comment]
We will try to reproduce this issue

**Comment by wurzer** [comment]
Which protocol and frequency do you use? The Volla Phone X supports IEEE 802.11 b/g/n 2,4 GHz + 5 GHz

**Comment by chrnit** [comment]
802.11 b/g/n WPA 2 PSK

**Comment by wurzer** [comment]
It works, if you expand additional setting for the Wifi network you want to connect with. In the extended settings you need to set the property for hidden network to yes.
