### ISSUE TITLE
VPN tethering is not available under hotspot settings

### ISSUE THREAD

**Issue by Danct12** [HelloVolla/volla-os-beta-test#62]
At least on LineageOS, under the hotspot settings you can allow hotspot clients to use the phone's VPN if it's available.

This option however does not exist under VollaOS.

**Comment by wurzer** [comment]
If you enable VPN on your Volla Phone and use tethering for your PC, the PC is also using implicitly the VPN of the phone.

**Comment by Danct12** [comment]
What about as a Wi-Fi hotspot? That's what I tested and it didn't use phone's VPN.

**Comment by wurzer** [comment]
This is, what I have tested. I switched on VPN on my Volla Phone and made a IP security check on my MacBook, that was connected with the Wifi hotspot on my volla Phone. I could see, that the VPN was used and the connections on my MacBook have been protected.

**Comment by gbdomubpkm** [comment]
@wurzer I can't confirm that it works with my ubuntu 20.04 laptop. And I'm surprised it works for you, because I've always read that, 'Android' doesn't allow VPN hotspot except maybe rooting exceptions or others.

**Comment by wurzer** [comment]
Let me resume my setup:

1. Recent version of Volla OS 10 from December on Volla Phone 
2. Activated VPN with Hide.me app.
3. Activated Hotspot with mobile data. 
4. Switched off VPN on my MacBook Pro
5. Wifi connection of my MacBook Pro with the hotspot of my Volla Phine.
6. IP privacy check on my Macbook confirms my VPN connection.

**Comment by gbdomubpkm** [comment]
Ok. I confirm, it doesn't work for me but i don't use Hide.me app. I use another VPN provider (app). Does it mean there was a specific work on the Volla so as to use VPN tethering with Hide.me (only) ? Or VPN tethering should work with other VPN providers ?

**Comment by wurzer** [comment]
I haven't tested another VPN, but it also should work. The fact, that Hide.me app is preinstalled could make a difference to the system behavior. Did you try to activate the strict use of VPN in the Network settings?

**Comment by gbdomubpkm** [comment]
What do you mean ? if you speak of permanent vpn, yes, it doesn't change anything. Before buying a Volla, i used Protonvpn and always now. Maybe you can test with a free account if vpn tethering works for you with proton.

**Comment by Danct12** [comment]
I assume "Always-on VPN" is what you mean by permanent VPN. I also tried it but it doesn't work.

**Comment by wurzer** [comment]
Here is the support answer of Proton mail:
https://protonvpn.com/support/share-vpn-connection-android-hotspot/

So I recommend to use our (privileged) hide.me app or VPON on your PC, if your are using the Volla Phone as a hotspot.

**Comment by gbdomubpkm** [comment]
I know this link with protonvpn answer. You confirm only what i said in my first comment. It would have been " a plus" if, with the Volla, VPN tethering had worked with all VPN providers but, personally,  i (we) can do without. So ONLY VPN tethering with Hide.me should work because Hide.me app is integrated/built  into the Volla.

**Comment by gbdomubpkm** [comment]
IF the VPN tethering cannot be implemented for other providers than hide.me, the request has in my opinion no reason to remain open.

**Comment by gbdomubpkm** [comment]
Good news : VPN tethering IS available with  Volla update based on AOSP 11.1, and works with Proton VPN for me: it should work with all VPN providers.
**Allow customers to use VPNs**
![Screenshot_20220521-145113_Paramètres](https://user-images.githubusercontent.com/50362604/169652763-6f2c6af9-9e6a-4144-bbdf-a0a7ac109fda.png)
Does it work because of the feature implementation (Volla team)  or the feature was in AOSP 11.1 ?

**Comment by wurzer** [comment]
Good to hear. Android 11 comes with a lot of enhancements.

**Comment by Danct12** [comment]
I saw the A11 update a few weeks ago and it even mentioned in the changelog but for some reason it doesn't show up in OTA. I'll check again today.

**Comment by wurzer** [comment]
Hello, you need to install the latest Volla OS 10 or Volla OS 10.1 release first to the the Volla OS 11.1 update.

**Comment by Danct12** [comment]
I just updated to Volla OS 11, loving the new features (double tap on the top bar to go sleep) and the new revised UI design.

I see the VPN option there, and it does work with my VPN provider as expected. Closing.
