### ISSUE TITLE
Refreshing of update list not possible

### ISSUE THREAD

**Issue by toby63** [HelloVolla/volla-os-beta-test#63]
When I click the refresh button in the Updater section (Settings->System->Updater), I get an error:
"Check your internet connection"

I tried it multiple times via Wlan and usb tethering.
It is like this for three days now.

**Comment by wurzer** [comment]
The OTA service is up and running please check it again. Usually this error message occurs, if your are not connected to the internet of the OTA server is down. 

USB tethering means, that your Volla Phones provides other devices like your laptop internet access using the USC connection. So, this feature has no impact on accessing the update on your device.

You Volla Phone must be connected to your WLAN or the cellular network. If you choose cellular network for data, you neet to take care, that the update feature is not deactivated, if you use the cellular network.

What is the version and data of your currently installed Volla OS? Please only download and install the update from the top of the list. 

You are welcome to open a ticket at https://volla.online/de/support/

**Comment by toby63** [comment]
Thx for the help.

I tried it again and now it works and shows that there are no new updates.
Most recent available update is from 1. February.

But I can't seem to install it.
When I click install, the installation starts and also seems to proceed, then the smartphone reboots, but when I check, the update is not installed.

My installed version is Volla OS 10 from 31. January.
Strangely this version is not shown anymore in the update list.

Is the recent security fix for february included in this?

**Comment by wurzer** [comment]
Please note, if you install the recent update from 1 February, the system updater shows 31 January afterwards. The reason of the slightly different date is difference of build time and deployment time.

**Comment by toby63** [comment]
Ok, thx for the info.
Then everything is good for now I think.

But I think it would be good to fix this mismatch (in the future), so users aren't confused and don't try to install "newer" updates, even though the update is already installed.
