### ISSUE TITLE
Some non-existent files are shown on native android File Manager 'Files'

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#64]
The native file manager of android AOSP (used for downloads) named 'Files', keeps track (name + extension) of some files in the folders 'Downloads' and 'Recent files' which do not exist at all on the Volla (Discreet Launcher of Vincent Falzon allows me to have access to 'Files'). Impossible to delete these files, I'm told that they don't exist,  which is logical..!
Did you notice that and do you know why ? Do you know how to clean that ?
Maybe a/the new update of AOSP will give the good info in 'Files' ?
It also seems that 'Files' on the Volla AOSP is also restricted in its use.

**Comment by wurzer** [comment]
You find both on the Volla Phone with Volla OS, the file manager of ASOP and the simple file manager, that you can open from the app grid. With both apps you can delete visible and hidden file, if you grand the permission to do so. 

You can find the file manager of AOSP by searching for files in the system setting.

**Comment by gbdomubpkm** [comment]
Hello.
As i said before, i speak of some Non-existent files, so they can't be deleted : only the name of some files that don't exist.

**Comment by wurzer** [comment]
So you see files in the file manager, that don't exist? In some cases the file manager app doesn't refresh the view properly until it is restarted. So try to force closing the file manager apps and restart it, so previously removed files are not visible any more.

**Comment by gbdomubpkm** [comment]
Doesn't change anything for me.
Did you check is everything is ok about this problem on your Volla ?
Maybe the next update of Volla AOSP will solve this issue (clean install).

**Comment by wurzer** [comment]
Please try to force closing the file manager app and clean cache and data before restarting it. The simple apps are frequently updates, that I'm confident, that a fix will be available. 

And yes, we will provide a major system update soon, that will also change a lot.

**Comment by gbdomubpkm** [comment]
Very happy to have regular updates. Thanks

**Comment by gbdomubpkm** [comment]
Just curious: I reinstalled the February 1st update from the update manager :  it didn't change anything: still the same tracks of files that no longer exist.
We'll see if the next update of AOSP and Volla solves this. There is also a system cleaner under F-DROID, 'LTE CLEANER' (Hunter Drum) but I didn't try it because I don't really know how much this program preserves confidentiality.

**Comment by wurzer** [comment]
Did you remove the cache and data of the simple file manager? Did you compare the directory in the AOSP file manager? If you are familiar with Android tools, you can list the files with afb shell. This should show you the truth.

**Comment by gbdomubpkm** [comment]
I did the right thing i think.
In fact, as far as I'm concerned, File Manager and File (native in AOSP) are not working/showing right info properly:
- with File Manager, the subdivisions 'Archives' and a little in 'Others' of the tab 'Storage analysis' show files which do not exist any more;
- with File, it is 'Downloads' and a little in 'Recent files' that are erroneous.

And No, I know very little about Android or AOSP; I'm discovering with the Volla, my first and single 'android' phone.

**Comment by wurzer** [comment]
Good morning, 
Did you remove Cache and Data of the File Manager app?
Do you also see the files in the AOSP File Manager app?
What is the full parch of the files you mention? Can you delete the upper folder,if files in it are not used any more?

**Comment by gbdomubpkm** [comment]
I noticed AOSP  11.1 update seems to have solved the issue so i close it.
