### ISSUE TITLE
SD card write access rights [VLC only?]

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#67]
Hello
Could you check how VLC works for you with the latest Android 11 update regarding SD card access.
In any case, it is impossible for me to obtain write rights, therefore to delete a video file from the SD card from the VLC player. Is this normal? It worked fine under AOSP 10.
Regards

**Comment by wurzer** [comment]
The recent release from 15 May should fix this issue. Android 11 is much more strict regarding file access for apps. However I see all music files on an external microSD card in my pre-installed Music player. 

I have checked the VLC Player successfully. You need to grand all access rights and you can even define, wether the external storage should be considered or not. Please check the app permissions.

**Comment by gbdomubpkm** [comment]
So, you confirm that you can delelete a video file from the SD card using VLC ?

**Comment by gbdomubpkm** [comment]
Yes there is with the three vertical dots of a video.

**Comment by wurzer** [comment]
You need to select the directory to grant write permission. This is the sandboxing feature of Android 11.

**Comment by gbdomubpkm** [comment]
I agree with you but something goes wrong when i try to delete a SD video file. Did you try to delete a video file ? All goes well in the full procedure for you ?

**Comment by wurzer** [comment]
The permission process is working, but it seems, that write access is not properly implemented.

**Comment by gbdomubpkm** [comment]
Yes.
I think you are facing the my problem: it is as if in fact the write permissions procedure seems to be accepted but which in the end does not work.

**Comment by gbdomubpkm** [comment]
I confirm the problem in the last update of May 17th.

**Comment by wurzer** [comment]
It's a known general issue of the app: https://code.videolan.org/videolan/vlc-android/-/issues/1796

**Comment by wurzer** [comment]
I think the reported issue includes a WRITE permission issue. We have fixed the access rights, that are now similar to Android 10. It seems, that VLC is not properly prepared for Android 11.

**Comment by gbdomubpkm** [comment]
> that VLC is not properly prepared for Android 11

If you think (or you are sure) that this is unrelated to your port of the Volla to android 11. I'll post the question at https://code.videolan.org/videolan/vlc-android/-/issues?sort=created_date&state=opened for know if there is a VLC problem about card write access on android 11 and will link this issue link.

**Comment by gbdomubpkm** [comment]
Fixed on the today Aurora Store VLC update 3.5.0 (allow manage **all** files in VLC for this to work).
