### ISSUE TITLE
Datepicker in first-time-setup shows white text on white background

### ISSUE THREAD

**Issue by everyusernameistaken123** [HelloVolla/volla-os-beta-test#69]
Hi,

Received the Volla Phone 22 yesterday. Expect some more questions / issues ;) 
During the first-time-setup, I tried to set the date and time manually (not sure how many people would do that...). And the date-picker was almost un-usable. The days / numbers and also month-selection on the top was not readable, it was all white-on-white.

Unfortunately, I didn't make a photo, but the "steps to reproduce" are quite easy: Take a Volla phone 22 out of the box and do first time-setup.

I was able to puzzle around it, trying blindly some places (when the day is selected, it is readable). While this is not a major bug, it makes the "out of box experience" really bad.

Volla OS version 11.1-20220719-STABLE-mimameid

**Comment by wurzer** [comment]
Can't reproduce this issue.
