### ISSUE TITLE
English EULA contains "Weiterentwicklung"

### ISSUE THREAD

**Issue by everyusernameistaken123** [HelloVolla/volla-os-beta-test#70]
When choosing English during first-time-setup, the headline "VII. Weiterentwicklung" is shown in German in the EULA (body-text is English, it's just this word as far as I noticed)

**Comment by wurzer** [comment]
Thanks for the hint. We'll fix it.

**Comment by wurzer** [comment]
Fixed in recent Volla OS update, already published for Volla Phone 22, soon for Volla Phone and Volla Phone X

**Comment by wurzer** [comment]
Fixed with update
