### ISSUE TITLE
Why are "Wireless emergency alerts" included?

### ISSUE THREAD

**Issue by everyusernameistaken123** [HelloVolla/volla-os-beta-test#74]
Hi,

As far as I learned, "Wireless emergency alerts" are a "feature" of US-government (source: https://www.fcc.gov/consumers/guides/wireless-emergency-alerts-wea )
According to the manual of Volla Phone 22, it is only allowed to be used in EU (+Switzerland). So why does it include things for US market?

(Don't get me wrong, I think WEA are a good idea and could have helped the people in EU in some situations. I just feel something "formally wrong" with it when the phone is not approved for the US.)

**Comment by wurzer** [comment]
There is no limitation to use SMS broadcasts only in EU and Switzerland.
