### ISSUE TITLE
Performance issues Volla Phone 22

### ISSUE THREAD

**Issue by robs-fotoalbum** [HelloVolla/volla-os-beta-test#76]
There were discussions regarding slow performance and lag issues. Some can be worked around via deselecting animations but they are still noticeable and prevent fluent typing and working.

There were discussions about similar issues with the GS5 model and the Helio G85, a firmware update similar to the one for GS5 was discussed as well.

I don't know if this is the right place to put this topic or if it is already on your list. I would consider this as a higher priority issue as it was reported by several users.

**Comment by wurzer** [comment]
GS5 is another model and not related to Volla Phone 22.
