### ISSUE TITLE
Volla OS - Springboard - deleting notes

### ISSUE THREAD

**Issue by vollaxrocks** [HelloVolla/volla-os-beta-test#77]
Dear Dr. Wurzer and Volla OS Team,

I must say the Volla Phone X is the best phone I've ever used,  

-I am unable to delete notes created on Springboard; pressing the delete/trash can icon does not delete the notes. Is there a way to do this?

-Can I link the notes created on the phone's native Notes app with Springboard?

Many thanks

**Comment by wurzer** [comment]
Hello, 

Thanks for the motivating words! 

1. Indeed, thanks for your hint. This is broken in the recent release. I'll fix it at the weekend.
2. Currently not. Notes are written and read in the .notes.json file I'll take it as an inspiration.

Enjoy the day!

**Comment by wurzer** [comment]
Fixed with update. Please re-check
