### ISSUE TITLE
Volla 22: accidental screen wake-up

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#79]
The proximity sensor does not seem to work on the Volla 22 since there is a screen awakening by bringing the Volla 22 close to the body and then moving it away or by passing your fingers against the switches ('prevent accidental awakening' enabled in system settings 'Screen').

**Comment by gbdomubpkm** [comment]
I found that disabling only the 'lift to activate' option solves the problem.

**Comment by wurzer** [comment]
Can't reproduce it. The proximity sensor doesn't wake up the device, since you haven't installed an app, that offers this kind of feature.
