### ISSUE TITLE
Android Auto does not work

### ISSUE THREAD

**Issue by HeeLoco** [HelloVolla/volla-os-beta-test#8]
Hello,

As soon as I try to connect the Volla Phone to the car an error occurs. I tried it several times. Unfortunately always the same result.

**Steps to reproduce:**

1. Connect the Phone via USB Cable
2. Push the hardware button in the car to open the menu

**Expected:** 

- Display is showing up correctly with several information

**Actual:** 

-  An error occurs

**Further Information:**
OS Version: 9
Build number: PPR1.180610.011 dev-keys
Custom bild version: alps-mp-p0.mp7-V2.51_prize.p0mp7.k57pv1.dm.64_P7
Car System: Opel Crossland X Version unfortunately unknown

**Pictures:**
Here an attempt is made to establish a connection
![IMG_20200825_170536_8](https://user-images.githubusercontent.com/66466597/91413696-c85dc080-e84b-11ea-974b-f8c72f970c11.jpg)

Here is the error message
![IMG_20200825_170520_1](https://user-images.githubusercontent.com/66466597/91413716-ce53a180-e84b-11ea-9bf2-50636553834e.jpg)

BR HeeLoco

**Comment by wurzer** [comment]
I think you need to install Android Auto, which requires Google Play Services, that are not part of Volla Os to protect the users privacy. As a solution you may install microG as an alternative for Google Play Services or you check an alternative for Android Car itself.

- https://www.giga.de/downloads/android-auto/tipps/android-auto-einrichten-anleitung-und-problem-loesung-so-geht-s/
- https://support.google.com/androidauto/answer/6348029?hl=en
- https://www.getdroidtips.com/top-5-android-auto-alternatives-for-your-car/
