### ISSUE TITLE
Volla Laucher 2.0.44

### ISSUE THREAD

**Issue by epimazzo** [HelloVolla/volla-os-beta-test#80]
Hi there,

The latest build 2.0.44 is not performing well as expected. Whatever app you load from the list crashes. If you open settings, it brings you back to the app list without even opening it, and a few other apps, such as F-Droid, crash with a pop-up error "Volla Keeps Stopping." Close App or Info as options.  I tried to downgrade to earlier 2.0.39, but it says you cannot due to a newer version already installed. Can't downgrade. The only launcher interface it works in this context is the Trebuchet. 
Any possible way to roll back? 
Thanks.

**Comment by wurzer** [comment]
II can't reproduce this issue. There are probably special conditions for your reported issue. Please reset the launcher by forcing to close the app and deleting data and cache.
