### ISSUE TITLE
Ubuntu Touch doesn't work with dual boot option in VollaOS on VollaPhoneX

### ISSUE THREAD

**Issue by SebastianTelt** [HelloVolla/volla-os-beta-test#81]
I have installed VollaOS in the newest available version. I bougth the VollaPhoneX with VollaOS preinstalled and just updated it.
With the last update there is the dual boot option available on the VollaPhoneX. I installed UbuntuTouch with this option (following the instructions on https://volla.online/en/faqs/ under "How can I install another operating system?"), but when restartung the device and choosing the ubuntuTouch system  the screen shows up the volla logo like when starting the vollaOS, but nothing other happends. After 30 Minutes I restart the device and starting the VollaOS that works fine.

How I installed the UbuntuTouch:
- Insert a microSD card (128 GB from ScanDisc)
- go in Setings -> dual boot and select formart microSD
- go to the menu point sd card and create the meta data partion
- create a partition for operating system data and confirm the suggested area size
- create a partition for OS user data and select 50 GB
- tap on the remaining free memory to create a memory area for a shared external memory area
- go to the ROM menu point and select UbuntuTouch and followed the instructions and selecting the partitions

After sucess installation restart the device and choose UbuntuTouch system, but nohting happens just the label volla is shown on screen.

**Comment by wurzer** [comment]
This is not re-producable as a general issue. Please contact our support at volla.online/en/support.
