### ISSUE TITLE
Add a calculator app

### ISSUE THREAD

**Issue by TFleury** [HelloVolla/volla-os-beta-test#84]
It could be nice to have a basic calculator included.

**Comment by leonryrko** [comment]
There is the [Simple Calculator](https://f-droid.org/en/packages/com.simplemobiletools.calculator/) from the Simple Tools suite. No need to make yet another calculator, IMHO.

**Comment by wurzer** [comment]
Thanks for the suggestion. I can conform. We suggest the simple calculator. We want to preinstall a minimum number of apps But we may offer additional apps in the setup wizard or even better, integrate a calculator right in the springboard.

**Comment by StaffanMelin** [comment]
I like the way that you do not install a lot of apps from the start.

But when you mentioned integrating it into the springboard, I agree with the OP. Bring it in! :) There is so much more to do with the Springboard!
