### ISSUE TITLE
turning on the light does not work (or very badly) in some apps

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#85]
With Volla OS 11.1 (tested on Volla and Volla 22), I can't get the Barcode scanner light to work from barcodescanner https://f-droid.org/en/packages/com.atharok.barcodescanner/ or Binary Eye https://f-droid.org/en/packages/de.markusfisch.android.binaryeye/ for example, while it works very well with a classic android. With Volla OS 11.1, the light works well with the Camera or an app like Flashy https://f-droid.org/en/packages/rocks.poopjournal.flashy/ for example.

What is the nature of the problem?

**Comment by wurzer** [comment]
Beide Anwendungen laufen problemlos unter Volla OS. Bitte prüfen Sie, ob Sie das Zugriffsrecht auf die Kamera erteilt haben.

**Comment by gbdomubpkm** [comment]
Hello.
You speak german here now ? 😉
So, you confirm that for you the flash ⚡ / the light for these two apps work as expected ?

**Comment by wurzer** [comment]
I'm sorry. I switch between two languages so many times. I have tested the apps on my device. They are working properly. Please make sure, that you grant the permission for the camera.

**Comment by gbdomubpkm** [comment]
For my tests, the access authorization to the camera was activated and I indeed confirm that the barcode scanners work but what does not work is the light which should light up and which does not light up when you press ⚡. With android, it lights up.

**Comment by wurzer** [comment]
Please take care, that the flash-icon is not stroked through.

**Comment by gbdomubpkm** [comment]
This is indeed the case. I confirm what I say: ⚡ is not crossed out and the light does not turn on when scanning a barcode, or the light does not remain permanently on when ⚡ is not crossed out, as with android. The flash can be triggered in low light but it is useless, no barcode scanning is done. It should be the same for you.

**Comment by wurzer** [comment]
I can't confirm your issue. I can make barcode scans. You can check the flash light with the default camera app or lashlihgt quick setting, whether it's properly working.

**Comment by gbdomubpkm** [comment]
Never mind. I said everything. There will be many other testers.

**Comment by wurzer** [comment]
Your are welcome. If the flash light works in the camera app, the hardware and API is working. So I suggest to contact the app developer to fix the issue you have realized. I the flash light with the camera app or quick setting is not working, I invite you to contact our support at volla.onlline/de/support to check the hardware as part of our warranty.

**Comment by gbdomubpkm** [comment]
No problem with my Volla , ⚡ works very well with the camera or for the flashlight. As I said clearly, it is ⚡ which cannot be activated (no lamp) during a barcode scan. BUT the scan works. I'm only talking about the lighting.
The problem is for ALL barcode scanning software. I have tested several. So if it's not a Volla OS problem, it's an android AOSP problem. Can you have what I say confirmed by a developer from the Volla OS team?

**Comment by wurzer** [comment]
Thanks. I'll ask my team

**Comment by gbdomubpkm** [comment]
> Thanks. I'll ask my team

Thank you.

**Comment by gbdomubpkm** [comment]
Hello.
Before i thought it was with all barcode scanners, i had open an issue. Maybe something useful here for your team : https://gitlab.com/Atharok/BarcodeScanner/-/issues/17

**Comment by gbdomubpkm** [comment]
cameraX API integration in v 1.8.0 of Barcode Scanner app (Atharok)  fixed the issue of ⚡ not working with this app. Now the lighting works with this app on the Volla.

**Comment by wurzer** [comment]
Good news. Thanks for the note.
