### ISSUE TITLE
Volla Launcher flickers

### ISSUE THREAD

**Issue by toby63** [HelloVolla/volla-os-beta-test#87]
After the recent update from 29. Dezember 2022 I can't see and use my regular launcher.
I regulary use the Volla launcher with the following details:
- dark mode
- app grid enabled

After entering my PIN in the login screen, the screen is black for a second and then it flickers with bright white flashes, and an animation looks like the program wants to "slide to the right", but it does not succeed.

I have now set the launcher to "Trebuchet" instead, and this is working correctly.

**Comment by wurzer** [comment]
I can't reproduce this behavior. Please reset the launcher app in the system settings or the reset option in the launcher settings.

**Comment by p-heeb** [comment]
Same issue here, I have already tried to reset the launcher, but this did not solve the problem. I still cannot use the launcher.
Switching to the Volla launcher is only possible with a restart, but switching to the Trebuchet launcher is no problem.
