### ISSUE TITLE
Volla Boot Manager: open "ROMs" Tab crashes the app

### ISSUE THREAD

**Issue by p-heeb** [HelloVolla/volla-os-beta-test#88]
After trying to install Sailfish OS on the SD card (failed), I can no longer open the "ROMs" tab in the Volla Boot Manager without the app crashing. All other tabs work without any problems.

Error notice:
Volla Boot Manager keeps stopping.

**Comment by wurzer** [comment]
Please remove the partitions for Sailfish OS on your SD card and re-partition your SD card. Maybe the SD card or data structure is corrupt. I possible, you can remove all partitions for a clean restart

**Comment by p-heeb** [comment]
I tried already but nothing changed with an empty SD card, prepared for installing a new OS.

**Comment by wurzer** [comment]
Did you follow the steps, described on our help page?
https://volla.online/en/faqs/

**Comment by p-heeb** [comment]
Yes, everything looked fine to me, like in the description.

**Comment by wurzer** [comment]
Download of Sailfish OS worked on Volla Phone 22 inside the Volla Boot Manager installation wizard?
How did you name the ROM? Try "SailfishOS" without a blank.
Did you complete the installation in Volla Boot Manager successfully? Does it end up with "OK"?
Can you open the partition list? 
Is the home view showing a green check mark?

**Comment by p-heeb** [comment]
Download of Sailfish OS worked on Volla Phone 22 inside the Volla Boot Manager installation wizard?
_Yes, it worked inside the Volla Boot Manager without any problems._

How did you name the ROM? Try "SailfishOS" without a blank.
_I used the default name which is "SailfishOS"._

Did you complete the installation in Volla Boot Manager successfully? Does it end up with "OK"?
_I thought it was, but I think there was an issue because of the Volla Manager problem I have now to show me the ROMs. The problem here is that I cannot delete or change anything with the installation because of the crash of the app. Is there another option to delete the installed Sailfish OS ROM?_

Can you open the partition list?
_Yes, I can open the partition list from the SD card and can also manipulate it. Before and after the issue I've gotten._

Is the home view showing a green check mark?
_After setup, the SD card as in the description (faq) explained the green check mark is showing. Even now._

**Comment by wurzer** [comment]
So, your Volla Boot Manager shows a valid partitioning map (see screenshots). You have to set **two** names. One is suggested by the wizard, the other might be modified to SailfishOS without a blank (see screenshot).

Are you using the recent Volla Os version from 28 December?

Another reason could be a damaged sd card. 
How large is your SD card? You should use one with 128 GB ore more. 

![Screenshot_20230103-100438_Volla_Boot_Manager](https://user-images.githubusercontent.com/7789612/210327721-e64c977e-7675-4139-9741-838cc5f369fc.png)
![Screenshot_20230103-100451_Volla_Boot_Manager](https://user-images.githubusercontent.com/7789612/210327729-e5b6c3a1-2701-408e-9d64-5d58ae0044ff.png)
![Screenshot_20230103-100459_Volla_Boot_Manager](https://user-images.githubusercontent.com/7789612/210327731-fb9499b1-f410-4726-9692-cb594ed1b892.png)

**Comment by p-heeb** [comment]
I use a new SD card with 128 GB, before I tested it and everything worked fine for me with the SD card. And the partitioning looks exactly like in your screenshots.
![image](https://user-images.githubusercontent.com/106586339/210334396-d377dfea-9991-404d-bc85-f88280b0dbf6.png)

![image](https://user-images.githubusercontent.com/106586339/210334445-95a7f1de-38b0-45d5-9593-859a2172a320.png)

Yes, I use the Volla OS version from 28. December. 

![image](https://user-images.githubusercontent.com/106586339/210334472-558736b7-a9b5-438a-b972-a65bafeb2476.png)

The ROM side can not be visualized there the app crashes.
![image](https://user-images.githubusercontent.com/106586339/210334507-c534c4a1-f423-426b-aa7a-ff82c5dd09f1.png)

**Comment by wurzer** [comment]
Do you remember the naming for ROM and operating system? If not, I suggest to re-format and re-install Sailfish OS.
Did you try to remove, re-start and re-insert the SD card?

**Comment by wurzer** [comment]
Please also format the free space as external data

**Comment by p-heeb** [comment]
I already delete all partitions of the SD card and re-inserted the SD card, but nothing helped me out. I'm still not able to open the ROMs tab in the Boot Manager.

Even not with formating the free space as external data.

**Comment by wurzer** [comment]
Did you try to install Ubuntu Touch? If this also fails, your SD card could be corrupt. 

We plan to publish a video on our YouTube channel soon to demonstrate the installation. That might help. Do you know this video?

https://t.me/hello_volla/67079

**Comment by p-heeb** [comment]
No, because I can not start the ROMs tab of the Volla Boot Manager to install another OS like UT.

**Comment by p-heeb** [comment]
I will try now to re-setup the whole SD card, maybe this will solve the problem.

**Comment by wurzer** [comment]
If you remove all partitions and re-partition the SD card, can open the ROM tab ?
Please try to format the free space as external storage.

**Comment by p-heeb** [comment]
No, I tried it before and nothing changed. With my SD card inserted, the ROM tab won't open.

I will try to insert the SD card into the PC to check if the card is still working. Maybe the card is broken somehow... I don't see any other reason for this behavior.

**Comment by wurzer** [comment]
Installation of Ubuntu Touch is working?
Did you format the free space? I saw in your screenshot, that the partitions haven't been complete.

**Comment by p-heeb** [comment]
I do not try to install UT. But it worked now, I inserted the SD card to the computer and delete there all partitions. Then I tried it again with the same steps as last time, but now it worked.

I assume that there was something wrong with the partitions but after a complete erase of the SD card it worked now.

@wurzer Thank you very much for the support, I appreciate that.
