### ISSUE TITLE
Volla Launcher issue

### ISSUE THREAD

**Issue by p-heeb** [HelloVolla/volla-os-beta-test#89]
Same issue as (closed): https://github.com/HelloVolla/volla-os-beta-test/issues/87#issue-1514825103

I have already tried to reset the launcher, but this did not solve the problem. I still cannot use the launcher.
Switching to the Volla launcher is only possible with a restart, but switching to the Trebuchet launcher is no problem.

**Comment by wurzer** [comment]
For resetting the launcher, you need to force the app to quit and delete the storage of the app. Then the launcher is working again.
