### ISSUE TITLE
Cannot use USB ethernet adapter

### ISSUE THREAD

**Issue by robbah** [HelloVolla/volla-os-beta-test#90]
When i am inserting my USB-C ethernet adapter to my Volla Phone 22. I cannot use it, but it is detecting the usb device.
My old (non Volla) phones are successful working with this ethernet adapter.

So i suspect it is a driver issue. Can you please help me?

**Comment by wurzer** [comment]
Please make sure, that the Ethernet adapter supports USB 2.0 and/or USB-OTG.

**Comment by robbah** [comment]
I tried a different ethernet adapter, and it is working. Thank you!
