### ISSUE TITLE
Corruption in android.R ?

### ISSUE THREAD

**Issue by mtotschnig** [HelloVolla/volla-os-beta-test#91]
A user of my app reported that on a certain dialog (generated with Jetpack Compose) a button which uses "android.R.string.Cancel" as text is rendered  in a strange way on his Volla OS phone, when the locale is set to English. He provided me with the following screenshots that show the difference between German and English. The only explanation I am currently able to think of is that there is some corruption in how Volla OS sets up the android.R resources. It seems as if the system resolves android.R.string.cancel to the expression Cancel preceded by some white space.

![Screenshot_20230120-144427_Trebuchet](https://user-images.githubusercontent.com/1485456/213909946-2191cbda-ad83-43f4-811e-ad85f94c0c13.png)
![Screenshot_20230120-144510_Trebuchet](https://user-images.githubusercontent.com/1485456/213909948-44de41e4-6da2-401d-bf2b-3f0d93882907.png)

**Comment by wurzer** [comment]
This is an issue of the app not the operating system. Android.R is a frequently used reference in many apps

**Comment by mtotschnig** [comment]
Still, the problem only occurs on Volla OS, which made me assume some misbehavior on OS level. Unfortunately I do not have access to a Volla phone, which would allow me to create a minimal project showcasing the problem.

**Comment by wurzer** [comment]
Thanks for the reply. As a developer I'm using Android.R in our Volla launcher for sure. And this works. I also think, that almost all Android apps make use of that basic concept. 

I don't want to carry owls to Athens. So excuse my question: Did you include the translation in your app instead of using the preference framework strings of the Android API? 

By the way: We can offer you as a developer a special 20% discount for Volla devices.

**Comment by mtotschnig** [comment]
I am definitely using "android.R.string.cancel". If I had access to a device, I could test if replacing "android.R.string.cancel" with an app specific resource or a hardcoded string would make a difference.
Thank you for the offer, but I am not able to afford to buy every potential device for which users report problems.
It would be great, if Volla OS could be tried out on an Emulator.

**Comment by mtotschnig** [comment]
By the way, my app is Open Source (https://github.com/mtotschnig/MyExpenses), in case someone with access to Volla Os wants to give it a try. The bug is generated by code in this file:
https://github.com/mtotschnig/MyExpenses/blob/master/myExpenses/src/main/java/org/totschnig/myexpenses/compose/CategoryEdit.kt

**Comment by Antiwhore** [comment]
The device in question is mine. In case it helps it is Volla Phone X with Volla OS version 11.1 with updates from October 29, 2022.

**Comment by wurzer** [comment]
I have just installed the app on my Volla Phone. I can't reproduce the issue. I'm using Volla OS 11.1 from 11 January 2023.

**Comment by Antiwhore** [comment]
Go to system settings, set the font size to Maximum and then back to app settings and set font size to default + 20%. The language in the app must be English.

**Comment by wurzer** [comment]
Can't reproduce it. I can see "Cancel" and "Save"

**Comment by Antiwhore** [comment]
Have you set both font sizes - in system and app?

**Comment by wurzer** [comment]
Yes. Maybe there is an additional condition. Maybe some accessability setting.

**Comment by mtotschnig** [comment]
@Antiwhore Your version (October 29, 2022) seems to be older than the one @wurzer is using (11 January 2023). Any chance for you to update to that latest version?

**Comment by wurzer** [comment]
By the way. I check the dialog for an additional category. Is that correct?

**Comment by Antiwhore** [comment]
You mean adding a category? Yes, it's right. You can also edit an existing category by tapping it, the problem is the same.
What other settings influence windows' appearance?
I will update to the latest version, but don't think it will make any difference.

**Comment by wurzer** [comment]
Maybe you have modified the colors in the accessibility settings? Unfortunately I can't reproduce this issue. I have used this advice: 

> Go to system settings, set the font size to Maximum and then back to app settings and set font size to default + 20%. The language in the app must be English.

**Comment by Antiwhore** [comment]
I've updated the system. Nothing changed.
Here are my accessibility settings: 
![Screenshot_20230123-155736_Trebuchet](https://user-images.githubusercontent.com/121800962/214046683-89a8168f-dd99-4f79-b093-838760bba5e9.png)

**Comment by wurzer** [comment]
Thanks. Looks fine. Did you try to reset the app?

**Comment by Antiwhore** [comment]
No. What does it mean?

**Comment by wurzer** [comment]
You can do it this way:

1. Open system settings
2. Go to apps & notifications
3. Go to all installed apps
4. Go to the MyExpenses app settings
5. Force quit
6. Delete app data
7. Reopen the app

Please not, that the data of the app will be removed. You may want to make a backup of the app data before.

**Comment by Antiwhore** [comment]
No, I'm not doing that. And the reason I'm not is that now you're not identifying the problem, but guessing the problem. And guessing is an extremely ineffective way of troubleshooting, which always leads to wasted time and rarely to solving the problem.
The reasonable way of troubleshooting here would be to look through system logs or application logs if they exist and locate the line which describes what happens when that category addition window opens.

**Comment by wurzer** [comment]
As I said. I can't reproduce the issue. So I couldn't even debug the issue. 

My suggestion is therefore to reset the app or modify the settings. You could keep the default scaling of the font in the app and scale the display instead.

**Comment by mtotschnig** [comment]
Based on the information I got from @Antiwhore, I conclude that the problem would not be dependent on font-scale settings. It is just made worse with larger font-settings because the Save button is pushed out. Even with smaller font size, the Cancel button which should be right aligned has this unwarranted left margin.
![Screenshot_20230110-192014_Trebuchet](https://user-images.githubusercontent.com/1485456/214637712-e4ad954d-f65e-49b3-bbc7-b4d7048503f7.png)
@Antiwhore Could you provide a screenshot with English language and the minimal system font size, and with no increase on app level?
@wurzer In your case you see the Cancel button with English locale correctly left aligned in any configuration?

**Comment by wurzer** [comment]
So it looks like a layout issue. Different behavior of different devices can be caused by different display resolution. I have checked the use case on a Volla Phone of the first generation. Like the Volla Phone 22 it has display has a higher resolution than the Volla Phone X. This could also be a reason for different results on devices of another brand. Anyway, it looks like a corner case, because the scaling is extremely high.

**Comment by Antiwhore** [comment]
Here it is.
![Screenshot_20230126-183610_Trebuchet](https://user-images.githubusercontent.com/121800962/214880379-5949d2fc-47a3-4843-8cc7-7db8afc4e919.png)

**Comment by mtotschnig** [comment]
@Antiwhore May I ask you for another peace of information/check? Are you using the language selection feature integrated into the app? If yes, could you verify if it makes a difference if you select English as the device language (and the in-app language selection set to "System default). Eventually kill the app and restart it after having modified these settings.

**Comment by Antiwhore** [comment]
Yes, I used the language selector from the app. When I followed your sequence, the window appearance recovered - now the buttons are exactly where they are supposed to be.

**Comment by mtotschnig** [comment]
@Antiwhore That is interesting. I suppose when you selected English from the System settings, you selected "United States" or "United Kingdom" as region. My Expenses sets Locale("en") without a region, so it seems that this makes a difference. So I suppose by using "en-US" instead, I might be able to solve the problem on app level, but there still might be something wrong on the OS level. Of course it is a corner case, because Android normally does not allow users to set a region-less English locale. 
@wurzer Out of interest, even if you set English on MyExpenses settings screen, you cannot reproduce the problem?

**Comment by wurzer** [comment]
I can confirm. If I select the language in the app, the button disappears. However I think, its a layout issue. I you don't scale the font in the app to plus 20%, you can see, that the button label "save" is shown in two lines.

**Comment by mtotschnig** [comment]
There is a layout issue, insofar that if for a given locale "android.R.string.cancel" resolves to a String with an unusual length, and in addition the font is scaled up, the Save button should remain visible, and I will fix this in the next version of the app.
But I also assume a broken behavior on OS level which resolves "android.R.string.cancel" to "Cancel" for locale en-US, and to something like "               Cancel" (i.e the word Cancel preceded by unusual white space")  for locale en.

**Comment by mtotschnig** [comment]
If I had access to a Volla phone, I would try to validate that assumption by writing an app, that outputs the translations of "android.R.string.cancel" for different locales. If someone is willing to test this, I could send an APK, or publish a test project to Github.

**Comment by mtotschnig** [comment]
Emulating my assumption: I replace
`
stringResource(id = android.R.string.cancel)
`
with
`"                  Cancel"`
and I get the behavior that @Antiwhore reported
![grafik](https://user-images.githubusercontent.com/1485456/215264926-338f24a8-d882-46b3-9474-d9ae6afa646b.png)

**Comment by wurzer** [comment]
Please also note, that the font on the Volla Phone is different to the default Android font. It's wider. I recommend to place the two buttons "cancel" and "save" with a flexible (no predefined) width. There should be enough space in the line. Also the button group shouldn't have a fixed width. Anyway. It looks like a corner case. almost no one will scale the text system wide to maximum and in addition in the app.

**Comment by Antiwhore** [comment]
Actually it's not true for font sizes. Now I'm using Maximum size in system settings and +10% in the app, because this combination gives the minimum size that doesn't put strain on your eyes when reading (+20% is even better). And if I left the system size on default, reading would be a horrible experience in the whole system. So I think fixing this is worth the effort.
As far as I understand from your discussion, the OS itself contributes to the problem. So is it a laborious task to fix it in the system?

**Comment by mtotschnig** [comment]
There is no consensus and clear understanding yet what exactly happens on VollaOS (different from other Android devices) that causes the white space in front of the Cancel button (independent of any font scale). But for My Expenses, 3.5.0 will have a workaround, that prevents the Save button from disappearing.

**Comment by Antiwhore** [comment]
I see your contribution to solving the problem on the app side and it is good. But as we understand now there's something wrong on the OS side that causes this, so it would be nice to hear from @wurzer as well that they do something about it, cause this may cause problems in other apps too.

**Comment by mtotschnig** [comment]
I think it is an edge case, because the problem seems only to happen with Locale "en", but normally Android does not use this Locale without a region, but always uses "en-US", "en-GB" etc.
