### ISSUE TITLE
Our app starts with black screen on volla-os

### ISSUE THREAD

**Issue by doums** [HelloVolla/volla-os-beta-test#92]
Hi!
We're currently developing an android application to bring a bridge to our [mixnet](https://nymtech.net/docs/stable/architecture/network-overview) other apps could use to empower privacy.
We have a beta version for now which works properly on "regular" android devices. But one of our users reported that on volla-os powered devices, the app starts and just shows a black screen.
We are using tauri mobile framework to build the app. It uses [webview](https://github.com/tauri-apps/wry) as frontend solution.

You can find the app's code here https://github.com/nymtech/nym/tree/develop/nym-connect-android/src-tauri/gen/android/nym-connect-android
Also you can test the app directly -> https://www.dropbox.com/s/nj1t9ikchcayck6/nc-debug.apk?dl=0 (yea you have to trust me on this)

Maybe you know what could be the issue? I'd be really grateful if you could help us to figure out what the problem is.

**Comment by wurzer** [comment]
I can conform a working start view on a developer device

![Screenshot_20230203-001432_Nym_Connect](https://user-images.githubusercontent.com/7789612/216472517-90bc77d0-2240-498e-bf2e-b0c4dfbc0123.png)

**Comment by doums** [comment]
Hey finally good news, thx for the feedback. Can you share your rom version please? So we could compare with the one of the other user. Thx!

**Comment by wurzer** [comment]
Hi , I'm using Volla OS from January, 11 th.

**Comment by rachyandco** [comment]
> Hi , I'm using Volla OS from January, 11 th.

I am the one testing, i am still on Jan 31 2022 version

**Comment by rachyandco** [comment]
i have a second Volla phone and updated to Volla OS from January, 11 th. and it does work.
i guess i should update the phone
