### ISSUE TITLE
System image for installing on tablet

### ISSUE THREAD

**Issue by Antiwhore** [HelloVolla/volla-os-beta-test#94]
Hello!
I don't have a system issue here, but a question about it. 
I'm using your phone already, but now I need a tablet as well. And same as with the phone, I don't want any Google stuff on it. But as you don't sell tablets, I'll have to buy it from someone else and install a degoogled system on it. As I'm familiar with Volla OS already, it would be the simplest to install it on the tablet.
Hence the questions: can you provide me with Volla OS image ready for installation and how easy would it be to install it on a tablet by myself? Is it like Android or more complicated?

**Comment by wurzer** [comment]
Unfortunately each operating system needs to be ported to the specific hardware. Volla OS is only available on Volla Phone devices. We are currently investigating in the economic and technical feasibility of a Volla tablet. In the meantime, you may have look at the supported devices of Ubuntu Touch: https://devices.ubuntu-touch.io

**Comment by Antiwhore** [comment]
Well, for tablets this list is very small and those devices don't satisfy my requirements. Not to mention that application selection for UT is narrow compared with Android.
However if you're considering a tablet release, I want to give you an advice on this. I think you've done a great job after the first Volla Phone with X and 22 models because you've provided users with not just outstanding system, but outstanding devices as well. X has shock resistance, bright screen, big battery and powerful speaker. 22 also has some rare features. And I suggest that you continue this course with a tablet.
This point is super important considering the fact that a tablet is a much less needed device than a smartphone. In fact, it's a device for special use cases. It means that in order to be desirable for customers it must possess a maximum amount of useful uniqueness. Ergo it must have more than just private OS.
As an example of this I want to share with you a tablet that I've recently discovered. You can check it out here:
https://oukitel.com/pages/oukitel-rt2
This tablet is remarkable in many ways. It is shock resistant, has a really huge battery, powerful speakers. But the greatest feature it has is this hand strap on the back. It's utility can't be overestimated - it replaces the inconvenient hold of a tablet with both hands and trying to press the screen areas with your thumbs with holding it by one hand and freely interacting with the other! That is, you attach the strap, put three middle fingers of your hand under it, the edge fingers above and voila - your second hand is totally free and easily interacts with the screen. And it's technically simple to implement - just two clamps and a strap with a velcro. The Chinese have made a huge mistake by not putting the main emphasis on this feature.
But you can correct their mistake by implementing something like that yourselves and making it a center of the device's attraction.
What do you think?

**Comment by wurzer** [comment]
Thanks for your proposal. The connected question is the price range, that would be acceptable for consumers. we are investigating in low cost production as well as premium devices.

**Comment by Antiwhore** [comment]
As for the price, this Oukitel tablet represents the low boundary of the price range for such set of features. They sell it from their own shop on AliExpress called like Oukitel Factory shop or something, you can check out the price there. I don't know how they achieve it, I suppose it's either low-quality components or super-low markup. Both variants are obviously unacceptable.
On the other side of the range there's another rugged device called Samsung Galaxy Tab Active Pro. It has the same screen size and a feature of a special stylus they call pen and its price is about 3 times that of the Oukitel. This option is also bad, because even people who need it for work may not be able to afford it.
I suppose that something in the middle of this range would be acceptable, but a certain price value mustn't be a purpose. I would choose a set of useful features that are a must for special use cases that the tablet is meant to solve, then pick the components of decent quality which are able to provide these features, sum up their prices and assembly cost and make a decent, but not big markup.
For example, Samsung also has another version of that tablet called 4 and it has quite bright screen unlike the Oukitel model. For special use cases Samsung's choice is the right one, because these cases most probably include the need to use the tablet outside in direct sunlight, where only a bright screen will provide good visibility.
But what other properties does this screen need to have? Does it need a 90 Hz refresh rate for example? Definitely no, because such rate is needed for watching smooth videos with high fps value. Watching such videos implies that the viewer wants a truly enjoyable viewing experience, but this experience also requires other conditions that only a desktop computer or TV can provide. Hence this screen feature would be useless in a tablet and must be excluded.
So what you need is a clear list of use cases which will dictate a suitable list of components, which in turn will dictate the final price.

**Comment by wurzer** [comment]
Thanks for the detailed requirement list. Let me also know, what you think about an accessory for the convergence use case? Take a larger screen and even keyboard, if you need it for your current activity.
