### ISSUE TITLE
no google maps alternative available

### ISSUE THREAD

**Issue by Idcrafter** [HelloVolla/volla-os-beta-test#95]
Normaly should microG contain mapbox to use inplace of any google maps api but on the latest volla os is this not the case which causes this error
![PXL_20230307_121435654](https://user-images.githubusercontent.com/50270538/223419781-7ffedbd5-951d-42a8-8113-a3bb0b770df0.jpg)

I have configured every Option on that needs to be on in microG
![PXL_20230307_121441197](https://user-images.githubusercontent.com/50270538/223420008-07e90b94-ce2b-4a7c-b30f-f27ef763df9a.jpg)

**Comment by wurzer** [comment]
@luka177 Can you check this?

**Comment by Idcrafter** [comment]
how the Status on this?

**Comment by wurzer** [comment]
Our current development focus is Volla OS 12. Afterwards we can address enhancements of  microG

**Comment by Idcrafter** [comment]
Oh that's nice to see, will it be based ln Android12?

**Comment by wurzer** [comment]
> Oh that's nice to see, will it be based ln Android12?

Yes, it will be based on Android 12

**Comment by ghost** [comment]
https://osmand.net/ This is available from F-droid. It uses google?

**Comment by wurzer** [comment]
> https://osmand.net/ This is available from F-droid. It uses google?

This app is pre-installed in Volla OS and doesn't use Google services.

**Comment by ghost** [comment]
> > https://osmand.net/ This is available from F-droid. It uses google?
> 
> This app is pre-installed in Volla OS and doesn't use Google services.

Then why this issue? I see it as a google map alternative.

**Comment by Idcrafter** [comment]
No there is no shipping with volla os

**Comment by Idcrafter** [comment]
Google maps api, i phrased wrongly. MicroG normaly replaces google maps api calls with mappbox which doesn't happen on VollaOs

**Comment by wurzer** [comment]
Yes, we have this feature on our agenda.

**Comment by wurzer** [comment]
> > This app is pre-installed in Volla OS and doesn't use Google services.
> 
> Then why this issue? I see it as a google map alternative.

OSMAnd is using Open Street Maps

**Comment by Idcrafter** [comment]
sorry i should clarify what i meant, the application on top is calling the maps api which shouldn't work because microG is installed, i have also another phone with a custom rom on it which ships microG and on it does it default to handling google maps api calls to use mapbox to not break apps that need the google maps api like Wiggle Wifi (the version which has the map to show how many networks are in a place). it will probably also help with apps like Uber and similar ones that need a map to function.

**Comment by wurzer** [comment]
Thanks for your post. We will add it to our backlog. @luka177 Can you check, how e could enable Google MAps with microG?

**Comment by wurzer** [comment]
Please re-check. I just checked the Google Maps app successfully with activated migroG on a Volla Phone 22 with Volla Os 12.1

**Comment by Idcrafter** [comment]
thanks for the info, but i didin't mean the application google maps which just works, i meant google maps integration into applications like Wiggle wifi, Uber, and more, the shown example was a small app i am working on and it uses google maps and just works on my pixel with replacing it with here maps but it threw this error out with Volla os and microG activated

**Comment by wurzer** [comment]
Thanks for the note. I have just installed Woggle Wifi on a VollaPHone 22 with Volla Os 12 and activated microG. I can see the map inside this app. If you are a developer you may post the errorlog sdnipped for accessing the Goolgle Map API.

**Comment by Idcrafter** [comment]
i will retest it with my app but i need to order a replacement screen

**Comment by wurzer** [comment]
> i will retest it with my app but i need to order a replacement screen

Which Generation of the Volla Phone? For volla Phone 22 you can order it here: https://volla.online/de/shop/spare-display-22/ You can alos send it to phone-service.de/volla.

**Comment by Idcrafter** [comment]
thanks, i am able to replace the screen myself

**Comment by Idcrafter** [comment]
and yes i finally could use it again and it works correctly and shows me mapbox instead of Google maps, thanks
