### ISSUE TITLE
Increase notifications volume steps

### ISSUE THREAD

**Issue by TFleury** [HelloVolla/volla-os-beta-test#96]
I just installed Volla OS 12.1 and i'm unable to fine tune notifications volume. Even at minimum it's too loud.

Device : Volla Phone 22 (mt6768)

**Comment by wurzer** [comment]
I can conform, that the loudness is quite high, but I can set the volume down in the system settings. Can you conform?

**Comment by TFleury** [comment]
There are only 7 steps in the volume slider (8 values possible including mute) in system settings.
The first value after mute is too loud.

**Comment by TFleury** [comment]
It seams to be fixed in latest betas.
