### ISSUE TITLE
After update, the phone isnt charging

### ISSUE THREAD

**Issue by huseyinkogo** [HelloVolla/volla-os-beta-test#97]
Yesterday i just updated on the latest update for volla phone 22 
SInce yesterday after the update, i thought i was charging my phone, however it wasn't.
However if i charge it from the usb to type -c from the pc. then it charges. however in the "slow charging' mode with a estimation of 8 hours for full charge.

I also removed the battery, reinstalled it back, lol it lost 10% of its charge. so it didnt make a benfit to the issue.
I also tried chaging when the phone is fully turned off, no hope. (but charging from pc works)

Device : Volla Phone 22
Update 19. June 2023 (Volla Phone 22)

**Comment by wurzer** [comment]
There was no modification of the charging features. May device is fully charged this morning as usual Please check your charging cable. In the system settings for the battery you can check, which app or seervice is consuming the power at most.
