### ISSUE TITLE
Wide angle option of the pre-installed camera app

### ISSUE THREAD

**Issue by tux4us** [HelloVolla/volla-os-beta-test#98]
The wide-angle option of the pre-installed camera app is no longer available in Volla OS 12 beta.

VollaPhone 22
12-20230531-BETA-mimameid

**Comment by wurzer** [comment]
Is fixed in the recent RC

**Comment by tux4us** [comment]
Thanks

**Comment by tux4us** [comment]
Today with VollaOS 12 update it works. Thank you
