### ISSUE TITLE
Volla Volla OS 12 :  Suspicion of instability of the internet connection (cellular data).

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#99]
Hello.

Thank you for the update under android 12. It brings more fluidity I think.

However I have found that occasionally the internet (cellular data) seems to disconnect after some time of non-use (standby) or maybe randomly. I'm not sure.
On the other hand, the network indicator indicates that the internet is still connected: weird..

Have you noticed an unstable internet connection? Is it a known bug ?

**Comment by wurzer** [comment]
I have not yet been able to observe this behavior. Do you use W-LAN in parallel? The smartphone usually switches to the stronger network. How do you realize this issue? Can youo reproduce it?

**Comment by gbdomubpkm** [comment]
It requires more observation to try to understand. I don't know if the supposed bug is artificially reproducible. No I don't use W-Lan in parallel, only a vpn from time to time. Cutting the cellular data and putting it back fixes the problem for what i have seen.

**Comment by wurzer** [comment]
I see, please also check, wether you are using a VPN kill switch. That could also cause diconnection from the internet.

**Comment by gbdomubpkm** [comment]
I indeed almost always use the Kill switch while not being able to conclude if the problem is related but it is possible. However, I never had this problem on Android 11.

**Comment by gbdomubpkm** [comment]
@wurzer I confirm: by disconnecting from the permanent VPN, the kill switch button is deactivated. After that a test on Fennec confirms to me that the Internet connection is not restored. Turning cellular data off then back on restores internet. This problem did not exist with Android 10 and 11.

Edit : Clarification: the problem occurs when you deactivate the permanent vpn when the kill schitch is activated. When you disable the kill switch and then the permanent vpn, the problem does not exist.

**Comment by wurzer** [comment]
@luka177 @erfanoabdi Have you seen this behavriour before? I think we need a logcat?

**Comment by gbdomubpkm** [comment]
With my VPN provider app (Proton) when I want to switch from one country to another while keeping the (permanent vpn + kill switch) conf,  the reconnection does not happen in the second country. No problem with android 11.
Please check this general switch  case. Thanks.

**Comment by wurzer** [comment]
I'm afraid it's an issue of the Proton app.

**Comment by gbdomubpkm** [comment]
> I'm afraid it's an issue of the Proton app

It worked fine with android 11. Do you mean you have no problem on your end regarding this with the Volla android 12 ?

**Comment by wurzer** [comment]
I think, it's a logical issue. If you only allow VPN and change the entry point for the VPN, the VPN app disconnects from the VPN and tries to establish another VPN tunnel. If the device is not connected with a VPN, the last step fails.

**Comment by gbdomubpkm** [comment]
I can only say that this problem was non-existent on android 11. If you didn't have this problem on android 11 (if you know) and you also have it now on android 12, it's not from proton. On my side this problem also impacts the volla 22 under android 12 (not 11). I'm always on time to ask proton support what they think about that.

**Comment by wurzer** [comment]
Sounds strange. If only VPN traffic is allowed, then there must be an exception for the new connection setup. This could work with Spril tunneling. The Hide.me app offers this option.

@erfanoabdi Any idea on this?

**Comment by gbdomubpkm** [comment]
I downgraded my version of the proton app where there was no problem on android 11. And the problem still exists on android 12. Also, proton support cannot reproduce the bug. It seems that the proton app is not the cause of the problem. However, I am awaiting a more complete analysis from them.

**Comment by wurzer** [comment]
Please note, that a VPN app can only establish a tunnel if the system setting for blocking non-VPN-connection is disablerd.

**Comment by gbdomubpkm** [comment]
Hello. What think your team about the problem i mentionned  ? Did they do some tests with android 11 (no problem for me) and after android 12 (problem). Thanks.

**Comment by wurzer** [comment]
We are currently invetigating, if this is a default Android 12 bhaviour. For me it's the expected behaviour for the VPN setting. If only VPN is allowed, a VPN app can't establish a VPN connection from ourside a VPN. The system settings works only for a static VPN, that you configure in the system settings.

**Comment by gbdomubpkm** [comment]
Just seen your update this morning : thank you again as you take my comment seriously : i really point out always what i think is a problem and there, i think there is one at a certain level because no network very often after disconnecting from the permanent vpn (with the kill switch that was activated and disable, what is normal), which is not normal. I've never known that with the previous aosp. It is totally abnormal (in my opinion) to be obliged to activate and then disable flight mode, or to disable/reactivate the cellular data to reconnect to firefox for example.

**Comment by gbdomubpkm** [comment]
Other than that, I have to say that volla OS 12 works perfectly fine for me. I haven't encountered any other 'bugs'. 🙂

**Comment by gbdomubpkm** [comment]
Hello.

I saw in wiki :

. Fix for lost internet connection if permanent VPN connection is activated in system settings

Is it a fix for this issue ?

**Comment by wurzer** [comment]
Yes, there will be a fix. You are invited to test the public beta release

**Comment by gbdomubpkm** [comment]
If the beta is a classic installation by the update manager, I will test.

**Comment by wurzer** [comment]
You need to download the Volla Channel Switcher at F-Droid with activated Volla Nightly Build Repository. Than you can switch to beta and use the Ubpadter app

**Comment by gbdomubpkm** [comment]
Are there any risks of data loss or other risks by going to the volla os beta channel?

Is the problem already fixed on the beta ?

Can we reverse easily to stable ?
other things to know ?

Il would be the first time i use the switcher so questions before..
Thanks

**Comment by wurzer** [comment]
Known issues  of the beta version are

* Volla Phone 22: Some beta testers report an increased battery drain
* Volla Phone X23: Some beta testers repport, that some SIMs are not recognized. So you may need to use the other slot.

**Comment by gbdomubpkm** [comment]
Confirmed fixed in last stable update.
Thanks.
